'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const SKILL = path.resolve(__dirname, '../../../plugins/distillery2/skills/d2-foundation');
const script = path.join(SKILL, 'scripts/genRules.js');
const adrDir = path.join(__dirname, 'fixtures/adr');

function tmp() { return fs.mkdtempSync(path.join(os.tmpdir(), 'd2-rules-')); }
function run(cwd, args) {
  try { return { code: 0, out: execFileSync(process.execPath, [script, '--cwd', cwd, ...args], { encoding: 'utf8' }) }; }
  catch (e) { return { code: e.status, out: (e.stdout || '') + (e.stderr || '') }; }
}

test('genRules: deterministic across two runs', () => {
  const a = tmp(), b = tmp();
  run(a, ['--adr', adrDir, '--out', 'docs/rules']);
  run(b, ['--adr', adrDir, '--out', 'docs/rules']);
  for (const f of fs.readdirSync(path.join(a, 'docs/rules'))) {
    assert.equal(fs.readFileSync(path.join(a, 'docs/rules', f), 'utf8'), fs.readFileSync(path.join(b, 'docs/rules', f), 'utf8'), `differ: ${f}`);
  }
});

test('genRules: proposed ADR is excluded', () => {
  const c = tmp();
  run(c, ['--adr', adrDir, '--out', 'docs/rules']);
  const all = fs.readdirSync(path.join(c, 'docs/rules')).map(f => fs.readFileSync(path.join(c, 'docs/rules', f), 'utf8')).join('\n');
  assert.ok(!all.includes('proposed なので rules に出てはいけない'), 'proposed rule leaked');
});

test('genRules: rules land under correct scope file', () => {
  const c = tmp();
  run(c, ['--adr', adrDir, '--out', 'docs/rules']);
  const backend = fs.readFileSync(path.join(c, 'docs/rules/tier-backend.md'), 'utf8');
  const common = fs.readFileSync(path.join(c, 'docs/rules/common.md'), 'utf8');
  const testing = fs.readFileSync(path.join(c, 'docs/rules/testing.md'), 'utf8');
  assert.ok(backend.includes('domain は infrastructure に依存しない'), 'backend rule missing');
  // 依存の向き (arch_test 付き) は表、それ以外は ADR ごとの見出し。平坦な "(ADR nnnn) ..." 箇条書きにしない
  assert.ok(backend.includes('## 依存の向き (アーキテストが強制する)'), 'arch table heading missing');
  assert.match(backend, /\| `apps\/backend-api\/src\/domain\/\*\*` \| 禁止 \| `apps\/backend-api\/src\/infrastructure\/\*\*` \|[^|]*\| domain は infrastructure に依存しない。? \| ADR 0002 \|/);
  assert.ok(!/^- \(ADR \d+\)/m.test(backend), 'flat attributed bullets must not remain');
  assert.ok(common.includes('## 決定ごとのルール') && /^### ADR \d{4} /m.test(common), 'per-ADR headings missing in common');
  assert.ok(common.includes('契約型 (packages/contracts) を直接編集しない'), 'common rule missing');
  assert.ok(testing.includes('pglite の実体で検証する'), 'testing rule missing');
  // scope 分離: common の決定にレイヤ規則が混ざらない
  assert.ok(!common.includes('domain は infrastructure'), 'backend rule leaked into common');
});

test('genRules: only present tier kinds get files', () => {
  const c = tmp();
  run(c, ['--adr', adrDir, '--out', 'docs/rules']);
  const files = fs.readdirSync(path.join(c, 'docs/rules')).sort();
  assert.ok(files.includes('tier-backend.md') && files.includes('tier-frontend.md') && files.includes('tier-worker.md'));
  assert.ok(!files.includes('tier-cli.md'), 'cli not declared but emitted');
  assert.ok(files.includes('index.md'));
  // index.md は各ルールへのリンクを持つ (雛形の `tier-<kind>.md` ではなく実在するファイル)
  const index = fs.readFileSync(path.join(c, 'docs/rules/index.md'), 'utf8');
  assert.match(index, /\| \[common\.md\]\(common\.md\) \| 全ティア共通 \|/);
  assert.match(index, /\| \[testing\.md\]\(testing\.md\) \|/);
  for (const f of files.filter((n) => n.startsWith('tier-'))) assert.ok(index.includes(`[${f}](${f})`), f);
  assert.doesNotMatch(index, /tier-<kind>|rules:files/);
});

test('genRules: hand-written rule ファイルは上書きせず exit 1、--force で上書き', () => {
  const c = tmp();
  const common = path.join(c, 'docs/rules/common.md');
  fs.mkdirSync(path.dirname(common), { recursive: true });
  fs.writeFileSync(common, '# 手書きルール (basis ヘッダなし)\n');
  const r = run(c, ['--adr', adrDir, '--out', 'docs/rules']);
  assert.equal(r.code, 1, r.out);
  assert.ok(r.out.includes('hand-written') || r.out.includes('lacks basis'), r.out);
  assert.equal(fs.readFileSync(common, 'utf8'), '# 手書きルール (basis ヘッダなし)\n', 'must not overwrite');
  // 他のファイルは生成される
  assert.ok(fs.existsSync(path.join(c, 'docs/rules/testing.md')), 'other files should still be generated');
  // --force で上書き
  const r2 = run(c, ['--adr', adrDir, '--out', 'docs/rules', '--force']);
  assert.equal(r2.code, 0, r2.out);
  assert.match(fs.readFileSync(common, 'utf8'), /generated by d2-foundation genRules\.js/);
});

test('genRules: unknown scope exits 1', () => {
  const c = tmp();
  const bad = path.join(c, 'adr');
  fs.mkdirSync(bad, { recursive: true });
  fs.writeFileSync(path.join(bad, '0001-x.md'), '---\nid: 1\nstatus: accepted\nscope: [backend]\nrules:\n  - scope: tier:nonsense\n    text: "bad"\n---\n');
  const r = run(c, ['--adr', bad, '--out', 'docs/rules']);
  assert.equal(r.code, 1, r.out);
  assert.ok(r.out.includes('unknown rule scope'), r.out);
});
