-- generated by distillery2 — do not edit

DO $$ BEGIN
  CREATE TYPE "audit_logs_actor_role" AS ENUM ('librarian', 'patron');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "books_media_type" AS ENUM ('paper', 'ebook');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "books_status" AS ENUM ('available', 'on_loan', 'awaiting_pickup');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "loans_status" AS ENUM ('on_loan', 'returned', 'overdue');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notification_attempts_result" AS ENUM ('sent', 'failed');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notifications_notification_type" AS ENUM ('return_notice', 'reminder', 'overdue_notice');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "reservations_status" AS ENUM ('waiting', 'notified', 'completed', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "audit_logs" (
  "audit_id" uuid NOT NULL,
  "actor_subject" text NOT NULL,
  "actor_role" "audit_logs_actor_role" NOT NULL,
  "action" text NOT NULL,
  "target_type" text NOT NULL,
  "target_id" text NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("audit_id")
);
CREATE INDEX IF NOT EXISTS "audit_logs_target_idx" ON "audit_logs" ("target_type", "target_id");

CREATE TABLE IF NOT EXISTS "books" (
  "book_id" uuid NOT NULL,
  "title" text NOT NULL,
  "author" text NOT NULL,
  "isbn" text,
  "publisher" text,
  "genre" text,
  "media_type" "books_media_type" NOT NULL,
  "status" "books_status" NOT NULL,
  "registered_on" date NOT NULL,
  "deleted_on" date,
  "version" integer NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("book_id")
);
CREATE INDEX IF NOT EXISTS "books_isbn_idx" ON "books" ("isbn");
CREATE INDEX IF NOT EXISTS "books_status_idx" ON "books" ("status");

CREATE TABLE IF NOT EXISTS "book_events" (
  "event_id" uuid NOT NULL,
  "book_id" uuid NOT NULL,
  "sequence" integer NOT NULL,
  "event_type" text NOT NULL,
  "payload" text NOT NULL,
  "actor_subject" text,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "book_events_book_sequence_uq" UNIQUE ("book_id", "sequence")
);

CREATE TABLE IF NOT EXISTS "idempotency_keys" (
  "idempotency_key" text NOT NULL,
  "principal_subject" text NOT NULL,
  "operation_id" text NOT NULL,
  "request_hash" text NOT NULL,
  "response_status" integer NOT NULL,
  "response_body" text,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("idempotency_key", "principal_subject", "operation_id")
);

CREATE TABLE IF NOT EXISTS "patrons" (
  "patron_number" text NOT NULL,
  "idp_subject" text,
  "name" text NOT NULL,
  "email_encrypted" text NOT NULL,
  "registered_on" date NOT NULL,
  "deleted_on" date,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("patron_number"),
  CONSTRAINT "patrons_idp_subject_uq" UNIQUE ("idp_subject")
);

CREATE TABLE IF NOT EXISTS "reservations" (
  "reservation_id" uuid NOT NULL,
  "patron_number" text NOT NULL,
  "book_id" uuid NOT NULL,
  "received_at" timestamptz NOT NULL,
  "queue_position" integer,
  "status" "reservations_status" NOT NULL,
  "notified_at" timestamptz,
  "completed_at" timestamptz,
  "cancelled_at" timestamptz,
  "version" integer NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("reservation_id")
);
CREATE INDEX IF NOT EXISTS "reservations_book_status_idx" ON "reservations" ("book_id", "status");
CREATE INDEX IF NOT EXISTS "reservations_patron_idx" ON "reservations" ("patron_number");

CREATE TABLE IF NOT EXISTS "loans" (
  "loan_id" uuid NOT NULL,
  "patron_number" text NOT NULL,
  "book_id" uuid NOT NULL,
  "reservation_id" uuid,
  "loaned_on" date NOT NULL,
  "due_date" date NOT NULL,
  "returned_on" date,
  "status" "loans_status" NOT NULL,
  "version" integer NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("loan_id")
);
CREATE INDEX IF NOT EXISTS "loans_patron_idx" ON "loans" ("patron_number");
CREATE INDEX IF NOT EXISTS "loans_book_idx" ON "loans" ("book_id");
CREATE INDEX IF NOT EXISTS "loans_status_due_idx" ON "loans" ("status", "due_date");

CREATE TABLE IF NOT EXISTS "loan_events" (
  "event_id" uuid NOT NULL,
  "loan_id" uuid NOT NULL,
  "sequence" integer NOT NULL,
  "event_type" text NOT NULL,
  "payload" text NOT NULL,
  "actor_subject" text,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "loan_events_loan_sequence_uq" UNIQUE ("loan_id", "sequence")
);

CREATE TABLE IF NOT EXISTS "notifications" (
  "notification_id" uuid NOT NULL,
  "patron_number" text NOT NULL,
  "email_encrypted" text NOT NULL,
  "loan_id" uuid,
  "reservation_id" uuid,
  "notification_type" "notifications_notification_type" NOT NULL,
  "requested_at" timestamptz NOT NULL,
  PRIMARY KEY ("notification_id"),
  CONSTRAINT "notifications_loan_type_uq" UNIQUE ("loan_id", "notification_type")
);
CREATE INDEX IF NOT EXISTS "notifications_patron_idx" ON "notifications" ("patron_number");

CREATE TABLE IF NOT EXISTS "notification_attempts" (
  "notification_id" uuid NOT NULL,
  "attempt_no" integer NOT NULL,
  "result" "notification_attempts_result" NOT NULL,
  "error_message" text,
  "attempted_at" timestamptz NOT NULL,
  PRIMARY KEY ("notification_id", "attempt_no")
);

CREATE TABLE IF NOT EXISTS "reservation_events" (
  "event_id" uuid NOT NULL,
  "reservation_id" uuid NOT NULL,
  "sequence" integer NOT NULL,
  "event_type" text NOT NULL,
  "payload" text NOT NULL,
  "actor_subject" text,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "reservation_events_reservation_sequence_uq" UNIQUE ("reservation_id", "sequence")
);

-- foreign keys (ALTER で後付け: 循環参照に対応)
DO $$ BEGIN
  ALTER TABLE "book_events" ADD CONSTRAINT "book_events_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books" ("book_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loan_events" ADD CONSTRAINT "loan_events_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loans" ("loan_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_patron_number_fkey" FOREIGN KEY ("patron_number") REFERENCES "patrons" ("patron_number") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books" ("book_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notification_attempts" ADD CONSTRAINT "notification_attempts_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "notifications" ("notification_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notifications" ADD CONSTRAINT "notifications_patron_number_fkey" FOREIGN KEY ("patron_number") REFERENCES "patrons" ("patron_number") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notifications" ADD CONSTRAINT "notifications_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loans" ("loan_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notifications" ADD CONSTRAINT "notifications_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservation_events" ADD CONSTRAINT "reservation_events_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservations" ADD CONSTRAINT "reservations_patron_number_fkey" FOREIGN KEY ("patron_number") REFERENCES "patrons" ("patron_number") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservations" ADD CONSTRAINT "reservations_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books" ("book_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
