-- generated by distillery2 — do not edit

DO $$ BEGIN
  CREATE TYPE "books_genre" AS ENUM ('literature', 'history', 'natural_science', 'social_science', 'art', 'engineering', 'children', 'reference');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "books_media_type" AS ENUM ('paper', 'electronic');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "books_status" AS ENUM ('available', 'on_loan', 'on_hold', 'deleted');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "job_runs_status" AS ENUM ('running', 'succeeded', 'failed');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "loans_status" AS ENUM ('on_loan', 'overdue', 'returned');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notifications_type" AS ENUM ('hold_ready', 'reminder', 'overdue_notice');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notifications_reminder_timing" AS ENUM ('three_days_before', 'one_day_before');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notifications_status" AS ENUM ('pending', 'sent', 'failed');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "patrons_category" AS ENUM ('general', 'child', 'student');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "patrons_status" AS ENUM ('active', 'deleted');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "reservations_status" AS ENUM ('waiting', 'on_hold', 'picked_up', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "books" (
  "book_id" uuid NOT NULL,
  "isbn" text,
  "title" text NOT NULL,
  "author" text NOT NULL,
  "publisher" text,
  "genre" "books_genre" NOT NULL,
  "media_type" "books_media_type" NOT NULL,
  "status" "books_status" NOT NULL,
  "version" integer NOT NULL,
  "registered_on" date NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("book_id")
);
CREATE INDEX IF NOT EXISTS "books_isbn_idx" ON "books" ("isbn");
CREATE INDEX IF NOT EXISTS "books_title_idx" ON "books" ("title");
CREATE INDEX IF NOT EXISTS "books_author_idx" ON "books" ("author");
CREATE INDEX IF NOT EXISTS "books_status_idx" ON "books" ("status");

CREATE TABLE IF NOT EXISTS "book_events" (
  "event_id" uuid NOT NULL,
  "book_id" uuid NOT NULL,
  "book_version" integer NOT NULL,
  "event_type" text NOT NULL,
  "payload" text NOT NULL,
  "actor_id" text NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "book_events_book_version_uq" UNIQUE ("book_id", "book_version")
);

CREATE TABLE IF NOT EXISTS "idempotency_keys" (
  "actor_id" text NOT NULL,
  "idempotency_key" text NOT NULL,
  "request_hash" text NOT NULL,
  "response_status" integer NOT NULL,
  "response_body" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("actor_id", "idempotency_key")
);
CREATE INDEX IF NOT EXISTS "idempotency_keys_expires_at_idx" ON "idempotency_keys" ("expires_at");

CREATE TABLE IF NOT EXISTS "job_runs" (
  "job_type" text NOT NULL,
  "target_date" date NOT NULL,
  "status" "job_runs_status" NOT NULL,
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz,
  "last_error" text,
  PRIMARY KEY ("job_type", "target_date")
);

CREATE TABLE IF NOT EXISTS "patrons" (
  "patron_number" text NOT NULL,
  "idp_subject" text,
  "full_name_encrypted" text NOT NULL,
  "email_encrypted" text NOT NULL,
  "phone_encrypted" text,
  "address_encrypted" text,
  "category" "patrons_category" NOT NULL,
  "status" "patrons_status" NOT NULL,
  "version" integer NOT NULL,
  "registered_on" date NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("patron_number"),
  CONSTRAINT "patrons_idp_subject_uq" UNIQUE ("idp_subject")
);
CREATE INDEX IF NOT EXISTS "patrons_status_idx" ON "patrons" ("status");

CREATE TABLE IF NOT EXISTS "loans" (
  "loan_id" uuid NOT NULL,
  "book_id" uuid NOT NULL,
  "patron_number" text NOT NULL,
  "loaned_on" date NOT NULL,
  "loan_period_days" integer NOT NULL,
  "due_on" date NOT NULL,
  "returned_on" date,
  "status" "loans_status" NOT NULL,
  "version" integer NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("loan_id")
);
CREATE INDEX IF NOT EXISTS "loans_status_due_on_idx" ON "loans" ("status", "due_on");
CREATE INDEX IF NOT EXISTS "loans_patron_number_idx" ON "loans" ("patron_number");
CREATE INDEX IF NOT EXISTS "loans_book_id_idx" ON "loans" ("book_id");
CREATE INDEX IF NOT EXISTS "loans_loaned_on_idx" ON "loans" ("loaned_on");

CREATE TABLE IF NOT EXISTS "loan_events" (
  "event_id" uuid NOT NULL,
  "loan_id" uuid NOT NULL,
  "loan_version" integer NOT NULL,
  "event_type" text NOT NULL,
  "payload" text NOT NULL,
  "actor_id" text NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "loan_events_loan_version_uq" UNIQUE ("loan_id", "loan_version")
);

CREATE TABLE IF NOT EXISTS "reservations" (
  "reservation_id" uuid NOT NULL,
  "book_id" uuid NOT NULL,
  "patron_number" text NOT NULL,
  "reserved_at" timestamptz NOT NULL,
  "queue_position" integer,
  "status" "reservations_status" NOT NULL,
  "hold_started_on" date,
  "hold_expires_on" date,
  "version" integer NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("reservation_id"),
  CONSTRAINT "reservations_book_queue_uq" UNIQUE ("book_id", "queue_position")
);
CREATE INDEX IF NOT EXISTS "reservations_patron_number_idx" ON "reservations" ("patron_number");
CREATE INDEX IF NOT EXISTS "reservations_status_hold_expires_idx" ON "reservations" ("status", "hold_expires_on");

CREATE TABLE IF NOT EXISTS "notifications" (
  "notification_id" uuid NOT NULL,
  "patron_number" text NOT NULL,
  "type" "notifications_type" NOT NULL,
  "loan_id" uuid,
  "reservation_id" uuid,
  "reminder_timing" "notifications_reminder_timing",
  "dedupe_key" text NOT NULL,
  "recipient_email_encrypted" text NOT NULL,
  "subject" text NOT NULL,
  "body" text NOT NULL,
  "status" "notifications_status" NOT NULL,
  "attempt_count" integer NOT NULL,
  "last_error" text,
  "version" integer NOT NULL,
  "created_at" timestamptz NOT NULL,
  "sent_at" timestamptz,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("notification_id"),
  CONSTRAINT "notifications_dedupe_key_uq" UNIQUE ("dedupe_key")
);
CREATE INDEX IF NOT EXISTS "notifications_status_created_idx" ON "notifications" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "notifications_patron_number_idx" ON "notifications" ("patron_number");

CREATE TABLE IF NOT EXISTS "notification_events" (
  "event_id" uuid NOT NULL,
  "notification_id" uuid NOT NULL,
  "notification_version" integer NOT NULL,
  "event_type" text NOT NULL,
  "payload" text NOT NULL,
  "actor_id" text NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "notification_events_notification_version_uq" UNIQUE ("notification_id", "notification_version")
);

CREATE TABLE IF NOT EXISTS "patron_events" (
  "event_id" uuid NOT NULL,
  "patron_number" text NOT NULL,
  "patron_version" integer NOT NULL,
  "event_type" text NOT NULL,
  "payload" text NOT NULL,
  "actor_id" text NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "patron_events_patron_version_uq" UNIQUE ("patron_number", "patron_version")
);

CREATE TABLE IF NOT EXISTS "reservation_events" (
  "event_id" uuid NOT NULL,
  "reservation_id" uuid NOT NULL,
  "reservation_version" integer NOT NULL,
  "event_type" text NOT NULL,
  "payload" text NOT NULL,
  "actor_id" text NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "reservation_events_reservation_version_uq" UNIQUE ("reservation_id", "reservation_version")
);

-- foreign keys (ALTER で後付け: 循環参照に対応)
DO $$ BEGIN
  ALTER TABLE "book_events" ADD CONSTRAINT "book_events_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books" ("book_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loan_events" ADD CONSTRAINT "loan_events_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loans" ("loan_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books" ("book_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_patron_number_fkey" FOREIGN KEY ("patron_number") REFERENCES "patrons" ("patron_number") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notification_events" ADD CONSTRAINT "notification_events_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "notifications" ("notification_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notifications" ADD CONSTRAINT "notifications_patron_number_fkey" FOREIGN KEY ("patron_number") REFERENCES "patrons" ("patron_number") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notifications" ADD CONSTRAINT "notifications_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loans" ("loan_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notifications" ADD CONSTRAINT "notifications_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "patron_events" ADD CONSTRAINT "patron_events_patron_number_fkey" FOREIGN KEY ("patron_number") REFERENCES "patrons" ("patron_number") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservation_events" ADD CONSTRAINT "reservation_events_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservations" ADD CONSTRAINT "reservations_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books" ("book_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservations" ADD CONSTRAINT "reservations_patron_number_fkey" FOREIGN KEY ("patron_number") REFERENCES "patrons" ("patron_number") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
