-- generated by distillery2 — do not edit

DO $$ BEGIN
  CREATE TYPE "books_genre" AS ENUM ('literature', 'history', 'social_science', 'natural_science', 'technology', 'arts', 'children', 'other');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "books_media_type" AS ENUM ('paper', 'electronic');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "copies_status" AS ENUM ('available', 'on_loan', 'on_hold', 'withdrawn');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "copy_events_event_type" AS ENUM ('registered', 'loaned', 'returned_to_shelf', 'held', 'withdrawn');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "copy_events_from_status" AS ENUM ('available', 'on_loan', 'on_hold', 'withdrawn');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "copy_events_to_status" AS ENUM ('available', 'on_loan', 'on_hold', 'withdrawn');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "loan_events_event_type" AS ENUM ('loaned', 'marked_overdue', 'returned');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "loan_events_from_status" AS ENUM ('on_loan', 'overdue', 'returned');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "loan_events_to_status" AS ENUM ('on_loan', 'overdue', 'returned');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "loans_status" AS ENUM ('on_loan', 'overdue', 'returned');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notification_events_event_type" AS ENUM ('queued', 'sent', 'send_failed');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notification_events_from_status" AS ENUM ('pending', 'sent');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notification_events_to_status" AS ENUM ('pending', 'sent');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notifications_notification_type" AS ENUM ('reservation_ready', 'due_reminder', 'overdue_notice');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "notifications_status" AS ENUM ('pending', 'sent');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "reservation_events_event_type" AS ENUM ('reserved', 'position_advanced', 'held', 'fulfilled', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "reservation_events_from_status" AS ENUM ('waiting', 'on_hold', 'fulfilled', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "reservation_events_to_status" AS ENUM ('waiting', 'on_hold', 'fulfilled', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
DO $$ BEGIN
  CREATE TYPE "reservations_status" AS ENUM ('waiting', 'on_hold', 'fulfilled', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "books" (
  "book_id" uuid NOT NULL,
  "isbn" text,
  "title" text NOT NULL,
  "author" text,
  "publisher" text,
  "genre" "books_genre",
  "media_type" "books_media_type" NOT NULL,
  "registered_on" date NOT NULL,
  "deleted_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("book_id"),
  CONSTRAINT "books_isbn_key" UNIQUE ("isbn")
);
CREATE INDEX IF NOT EXISTS "books_title_idx" ON "books" ("title");
CREATE INDEX IF NOT EXISTS "books_author_idx" ON "books" ("author");
CREATE INDEX IF NOT EXISTS "books_genre_idx" ON "books" ("genre");

CREATE TABLE IF NOT EXISTS "copies" (
  "copy_id" uuid NOT NULL,
  "book_id" uuid NOT NULL,
  "status" "copies_status" NOT NULL,
  "acquired_on" date NOT NULL,
  "version" integer NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("copy_id")
);
CREATE INDEX IF NOT EXISTS "copies_book_id_idx" ON "copies" ("book_id");
CREATE INDEX IF NOT EXISTS "copies_status_idx" ON "copies" ("status");

CREATE TABLE IF NOT EXISTS "librarians" (
  "librarian_id" uuid NOT NULL,
  "staff_id" text NOT NULL,
  "name" text NOT NULL,
  "login_id" text NOT NULL,
  "idp_subject" text,
  "deleted_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("librarian_id"),
  CONSTRAINT "librarians_staff_id_key" UNIQUE ("staff_id"),
  CONSTRAINT "librarians_login_id_key" UNIQUE ("login_id"),
  CONSTRAINT "librarians_idp_subject_key" UNIQUE ("idp_subject")
);

CREATE TABLE IF NOT EXISTS "copy_events" (
  "event_id" uuid NOT NULL,
  "copy_id" uuid NOT NULL,
  "sequence" integer NOT NULL,
  "event_type" "copy_events_event_type" NOT NULL,
  "from_status" "copy_events_from_status",
  "to_status" "copy_events_to_status" NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  "actor_librarian_id" uuid,
  "payload" text,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "copy_events_copy_sequence_key" UNIQUE ("copy_id", "sequence")
);

CREATE TABLE IF NOT EXISTS "patrons" (
  "patron_id" uuid NOT NULL,
  "patron_number" text NOT NULL,
  "name_encrypted" text NOT NULL,
  "email_encrypted" text NOT NULL,
  "login_id" text NOT NULL,
  "idp_subject" text,
  "registered_on" date NOT NULL,
  "deleted_at" timestamptz,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("patron_id"),
  CONSTRAINT "patrons_patron_number_key" UNIQUE ("patron_number"),
  CONSTRAINT "patrons_login_id_key" UNIQUE ("login_id"),
  CONSTRAINT "patrons_idp_subject_key" UNIQUE ("idp_subject")
);

CREATE TABLE IF NOT EXISTS "loan_rules" (
  "loan_rule_id" uuid NOT NULL,
  "loan_period_days" integer NOT NULL,
  "reminder_days_before" integer NOT NULL,
  "effective_from" date NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("loan_rule_id"),
  CONSTRAINT "loan_rules_effective_from_key" UNIQUE ("effective_from")
);

CREATE TABLE IF NOT EXISTS "loans" (
  "loan_id" uuid NOT NULL,
  "patron_id" uuid NOT NULL,
  "copy_id" uuid NOT NULL,
  "loan_rule_id" uuid NOT NULL,
  "loaned_on" date NOT NULL,
  "due_on" date NOT NULL,
  "returned_on" date,
  "status" "loans_status" NOT NULL,
  "loaned_by_librarian_id" uuid NOT NULL,
  "returned_by_librarian_id" uuid,
  "version" integer NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("loan_id")
);
CREATE INDEX IF NOT EXISTS "loans_patron_id_idx" ON "loans" ("patron_id");
CREATE INDEX IF NOT EXISTS "loans_copy_id_idx" ON "loans" ("copy_id");
CREATE INDEX IF NOT EXISTS "loans_status_due_on_idx" ON "loans" ("status", "due_on");

CREATE TABLE IF NOT EXISTS "loan_events" (
  "event_id" uuid NOT NULL,
  "loan_id" uuid NOT NULL,
  "sequence" integer NOT NULL,
  "event_type" "loan_events_event_type" NOT NULL,
  "from_status" "loan_events_from_status",
  "to_status" "loan_events_to_status" NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  "actor_librarian_id" uuid,
  "payload" text,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "loan_events_loan_sequence_key" UNIQUE ("loan_id", "sequence")
);

CREATE TABLE IF NOT EXISTS "reservations" (
  "reservation_id" uuid NOT NULL,
  "patron_id" uuid NOT NULL,
  "book_id" uuid NOT NULL,
  "held_copy_id" uuid,
  "reserved_at" timestamptz NOT NULL,
  "queue_position" integer,
  "status" "reservations_status" NOT NULL,
  "hold_started_on" date,
  "active_key" text,
  "version" integer NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("reservation_id"),
  CONSTRAINT "reservations_active_key_key" UNIQUE ("active_key")
);
CREATE INDEX IF NOT EXISTS "reservations_book_status_position_idx" ON "reservations" ("book_id", "status", "queue_position");
CREATE INDEX IF NOT EXISTS "reservations_patron_id_idx" ON "reservations" ("patron_id");

CREATE TABLE IF NOT EXISTS "notifications" (
  "notification_id" uuid NOT NULL,
  "notification_type" "notifications_notification_type" NOT NULL,
  "target_id" uuid NOT NULL,
  "loan_id" uuid,
  "reservation_id" uuid,
  "patron_id" uuid NOT NULL,
  "recipient_email_encrypted" text NOT NULL,
  "scheduled_on" date NOT NULL,
  "status" "notifications_status" NOT NULL,
  "sent_at" timestamptz,
  "attempt_count" integer NOT NULL,
  "last_error" text,
  "version" integer NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("notification_id"),
  CONSTRAINT "notifications_dedup_key" UNIQUE ("notification_type", "target_id", "scheduled_on")
);
CREATE INDEX IF NOT EXISTS "notifications_status_idx" ON "notifications" ("status");

CREATE TABLE IF NOT EXISTS "notification_events" (
  "event_id" uuid NOT NULL,
  "notification_id" uuid NOT NULL,
  "sequence" integer NOT NULL,
  "event_type" "notification_events_event_type" NOT NULL,
  "from_status" "notification_events_from_status",
  "to_status" "notification_events_to_status" NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  "payload" text,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "notification_events_notification_sequence_key" UNIQUE ("notification_id", "sequence")
);

CREATE TABLE IF NOT EXISTS "reservation_events" (
  "event_id" uuid NOT NULL,
  "reservation_id" uuid NOT NULL,
  "sequence" integer NOT NULL,
  "event_type" "reservation_events_event_type" NOT NULL,
  "from_status" "reservation_events_from_status",
  "to_status" "reservation_events_to_status" NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  "actor_librarian_id" uuid,
  "payload" text,
  PRIMARY KEY ("event_id"),
  CONSTRAINT "reservation_events_reservation_sequence_key" UNIQUE ("reservation_id", "sequence")
);

-- foreign keys (ALTER で後付け: 循環参照に対応)
DO $$ BEGIN
  ALTER TABLE "copies" ADD CONSTRAINT "copies_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books" ("book_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "copy_events" ADD CONSTRAINT "copy_events_copy_id_fkey" FOREIGN KEY ("copy_id") REFERENCES "copies" ("copy_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "copy_events" ADD CONSTRAINT "copy_events_actor_librarian_id_fkey" FOREIGN KEY ("actor_librarian_id") REFERENCES "librarians" ("librarian_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loan_events" ADD CONSTRAINT "loan_events_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loans" ("loan_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loan_events" ADD CONSTRAINT "loan_events_actor_librarian_id_fkey" FOREIGN KEY ("actor_librarian_id") REFERENCES "librarians" ("librarian_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_patron_id_fkey" FOREIGN KEY ("patron_id") REFERENCES "patrons" ("patron_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_copy_id_fkey" FOREIGN KEY ("copy_id") REFERENCES "copies" ("copy_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_loan_rule_id_fkey" FOREIGN KEY ("loan_rule_id") REFERENCES "loan_rules" ("loan_rule_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_loaned_by_librarian_id_fkey" FOREIGN KEY ("loaned_by_librarian_id") REFERENCES "librarians" ("librarian_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "loans" ADD CONSTRAINT "loans_returned_by_librarian_id_fkey" FOREIGN KEY ("returned_by_librarian_id") REFERENCES "librarians" ("librarian_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notification_events" ADD CONSTRAINT "notification_events_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "notifications" ("notification_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notifications" ADD CONSTRAINT "notifications_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loans" ("loan_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notifications" ADD CONSTRAINT "notifications_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "notifications" ADD CONSTRAINT "notifications_patron_id_fkey" FOREIGN KEY ("patron_id") REFERENCES "patrons" ("patron_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservation_events" ADD CONSTRAINT "reservation_events_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("reservation_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservation_events" ADD CONSTRAINT "reservation_events_actor_librarian_id_fkey" FOREIGN KEY ("actor_librarian_id") REFERENCES "librarians" ("librarian_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservations" ADD CONSTRAINT "reservations_patron_id_fkey" FOREIGN KEY ("patron_id") REFERENCES "patrons" ("patron_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservations" ADD CONSTRAINT "reservations_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "books" ("book_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "reservations" ADD CONSTRAINT "reservations_held_copy_id_fkey" FOREIGN KEY ("held_copy_id") REFERENCES "copies" ("copy_id") ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
