#!/usr/bin/env node
'use strict';
/**
 * genArchTests.js (F2) — ADR の arch_test から .dependency-cruiser.cjs を生成する
 *
 *   node genArchTests.js --adr docs/adr --out .dependency-cruiser.cjs [--cwd <repo>]
 *
 * - 採用済み ADR の rules[].arch_test を forbidden ルールにする。名前は adr-<id>-<n>。
 *   effect: forbid → forbidden、effect: allow → allowed[] (許可リスト)。
 * - 既定ルール: no-circular (error)、no-orphans (warn)。
 * - 出力は決定論。生成ファイルは有効な JS (node -e "require(...)" が通る)。
 * - パスは dependency-cruiser の正規表現。glob (`**`, `*`) を正規表現へ変換する。
 *
 * 参照 (Context7 /sverweij/dependency-cruiser v18.4.0): module.exports = {forbidden, options}、
 * forbidden[].{name, severity, from:{path}, to:{path|circular|orphan}}。
 */
const fs = require('node:fs');
const path = require('node:path');
const { loadAdrs, isAccepted } = require('./adr');
const { stamp, headerLine } = require('../../../scripts/lib/basis');

function parseArgs(argv) {
  const o = { adr: 'docs/adr', out: '.dependency-cruiser.cjs', cwd: process.cwd() };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i], next = () => argv[++i];
    if (a === '--adr') o.adr = next();
    else if (a === '--out') o.out = next();
    else if (a === '--cwd') o.cwd = path.resolve(next());
    else throw new Error(`Unknown arg: ${a}`);
  }
  return o;
}

/** glob を dependency-cruiser 用の正規表現文字列へ変換する。 */
function globToRe(glob) {
  let re = '^';
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i];
    if (c === '*') {
      if (glob[i + 1] === '*') { re += '.*'; i++; if (glob[i + 1] === '/') i++; }
      else re += '[^/]*';
    } else if ('.+?^${}()|[]\\'.includes(c)) re += '\\' + c;
    else re += c;
  }
  return re;
}

/** 採用済み ADR から arch_test を集める。ADR 内での連番で名前を付ける。 */
function collectArchTests(adrs) {
  const forbidden = [], allowed = [];
  for (const adr of adrs) {
    if (!isAccepted(adr) || !Array.isArray(adr.rules)) continue;
    let n = 0;
    for (const r of adr.rules) {
      if (!r || !r.arch_test) continue;
      n++;
      const at = r.arch_test;
      const entry = { name: `adr-${adr.id}-${n}`, from: globToRe(at.from), to: globToRe(at.to), text: r.text || '', effect: at.effect || 'forbid' };
      (entry.effect === 'allow' ? allowed : forbidden).push(entry);
    }
  }
  const byName = (a, b) => a.name.localeCompare(b.name, 'en', { numeric: true });
  return { forbidden: forbidden.sort(byName), allowed: allowed.sort(byName) };
}

function render({ forbidden, allowed }, basisLine) {
  const forbiddenSrc = forbidden.map(r =>
    `    {\n      name: ${JSON.stringify(r.name)},\n      comment: ${JSON.stringify(r.text)},\n      severity: 'error',\n      from: { path: ${JSON.stringify(r.from)} },\n      to: { path: ${JSON.stringify(r.to)} },\n    },`).join('\n');
  const allowedSrc = allowed.map(r =>
    `    { from: { path: ${JSON.stringify(r.from)} }, to: { path: ${JSON.stringify(r.to)} } }, // ${r.name}`).join('\n');
  const allowedBlock = allowed.length
    ? `\n  allowed: [\n${allowedSrc}\n  ],\n  allowedSeverity: 'warn',`
    : '';
  return `// ${basisLine}
// generated by d2-foundation genArchTests.js — 手で直さず ADR の arch_test を変える
/** @type {import('dependency-cruiser').IConfiguration} */
module.exports = {
  forbidden: [
    {
      name: 'no-circular',
      comment: '循環依存を禁止する',
      severity: 'error',
      from: {},
      to: { circular: true },
    },
    {
      name: 'no-orphans',
      comment: 'どこからも参照されないモジュールを警告する',
      severity: 'warn',
      from: { orphan: true, pathNot: ['\\\\.(test|spec)\\\\.[jt]sx?$', '\\\\.d\\\\.ts$'] },
      to: {},
    },
${forbiddenSrc}
  ],${allowedBlock}
  options: {
    doNotFollow: { path: 'node_modules' },
    tsConfig: { fileName: './tsconfig.base.json' },
    tsPreCompilationDeps: true,
  },
};
`;
}

function run(o) {
  const adrs = loadAdrs(path.resolve(o.cwd, o.adr));
  const rules = collectArchTests(adrs);
  const basisLine = headerLine(stamp({ adr: o.adr }, o.cwd));
  const outPath = path.resolve(o.cwd, o.out);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, render(rules, basisLine));
  return { code: 0, forbidden: rules.forbidden.length, allowed: rules.allowed.length, out: outPath };
}

function main(argv) {
  let o; try { o = parseArgs(argv); } catch (e) { console.error(e.message); return 2; }
  const r = run(o);
  console.log(`genArchTests: ${r.forbidden} forbidden + ${r.allowed} allowed → ${o.out}`);
  return r.code;
}

if (require.main === module) process.exit(main(process.argv.slice(2)));
module.exports = { parseArgs, globToRe, collectArchTests, render, run };
