#!/usr/bin/env node
'use strict';
/**
 * genRules.js (F1) — ADR の rules[] とテンプレートから docs/rules/*.md を生成する
 *
 *   node genRules.js --adr docs/adr --out docs/rules [--templates <dir>] [--cwd <repo>]
 *
 * - テンプレート (references/rule-templates/) を土台に、採用済み ADR の rules[] を
 *   scope ごとに `## プロジェクトの決定から` 節へ ADR id 昇順で差し込む。
 * - scope: common → common.md / tier:<kind> → tier-<kind>.md / testing → testing.md
 * - tier ファイルは ADR tiers[] に現れた kind だけ生成する (宣言が無ければ全 kind)。
 * - 出力は決定論 (2 回実行して同一)。先頭に basis ヘッダを付ける。
 * - 未知の scope は exit 1 で停止する (推測で振り分けない)。
 */
const fs = require('node:fs');
const path = require('node:path');
const { loadAdrs, isAccepted, TIER_KINDS } = require('./adr');
const { stamp, headerLine } = require('../../../scripts/lib/basis');

const DEFAULT_TEMPLATES = path.join(__dirname, '..', 'references', 'rule-templates');

function parseArgs(argv) {
  const o = { adr: 'docs/adr', out: 'docs/rules', templates: DEFAULT_TEMPLATES, cwd: process.cwd() };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i], next = () => argv[++i];
    if (a === '--adr') o.adr = next();
    else if (a === '--out') o.out = next();
    else if (a === '--templates') o.templates = next();
    else if (a === '--cwd') o.cwd = path.resolve(next());
    else throw new Error(`Unknown arg: ${a}`);
  }
  return o;
}

/** rule の scope を出力ファイル名に対応づける。未知なら null。 */
function scopeToFile(scope) {
  if (scope === 'common') return 'common.md';
  if (scope === 'testing') return 'testing.md';
  const m = /^tier:(.+)$/.exec(scope);
  if (m && TIER_KINDS.includes(m[1])) return `tier-${m[1]}.md`;
  return null;
}

/** 採用済み ADR から scope → [{id, text}] を集める。未知 scope はエラー配列に載せる。 */
function collectRules(adrs) {
  const byScope = {};
  const errors = [];
  for (const adr of adrs) {
    if (!isAccepted(adr) || !Array.isArray(adr.rules)) continue;
    for (const r of adr.rules) {
      if (!r || !r.scope) continue;
      const file = scopeToFile(r.scope);
      if (!file) { errors.push({ id: adr.id, scope: r.scope, file: adr.file }); continue; }
      (byScope[file] ||= []).push({ id: adr.id, text: r.text });
    }
  }
  for (const list of Object.values(byScope)) list.sort((a, b) => String(a.id).localeCompare(String(b.id), 'en', { numeric: true }));
  return { byScope, errors };
}

/** ADR tiers[] に現れた kind の集合。宣言が無ければ全 kind。 */
function presentKinds(adrs) {
  const kinds = new Set();
  for (const adr of adrs) {
    if (isAccepted(adr) && Array.isArray(adr.tiers)) for (const t of adr.tiers) if (t.kind) kinds.add(t.kind);
  }
  return kinds.size ? [...kinds].filter(k => TIER_KINDS.includes(k)) : [...TIER_KINDS];
}

function renderFile(templateBody, rules, basisLine) {
  let body = templateBody.replace(/\s+$/, '');
  if (rules && rules.length) {
    body += '\n\n## プロジェクトの決定から\n\n';
    body += rules.map(r => `- (ADR ${r.id}) ${r.text}`).join('\n');
  }
  return `<!-- ${basisLine} -->\n<!-- generated by d2-foundation genRules.js — 手で直さず ADR を変える -->\n\n${body}\n`;
}

function run(o) {
  const adrDir = path.resolve(o.cwd, o.adr);
  const outDir = path.resolve(o.cwd, o.out);
  const adrs = loadAdrs(adrDir);
  const { byScope, errors } = collectRules(adrs);
  if (errors.length) {
    for (const e of errors) console.error(`ERROR unknown rule scope "${e.scope}" in ${e.file} (ADR ${e.id})`);
    return { code: 1, written: [] };
  }
  const basisLine = headerLine(stamp({ adr: o.adr }, o.cwd));
  const kinds = presentKinds(adrs);
  const targets = ['index.md', 'common.md', 'testing.md', ...kinds.map(k => `tier-${k}.md`)];
  fs.mkdirSync(outDir, { recursive: true });
  const written = [];
  for (const name of targets) {
    const tplPath = path.join(o.templates, name);
    if (!fs.existsSync(tplPath)) { console.error(`ERROR template not found: ${tplPath}`); return { code: 1, written }; }
    const tpl = fs.readFileSync(tplPath, 'utf8');
    const content = renderFile(tpl, byScope[name], basisLine);
    fs.writeFileSync(path.join(outDir, name), content);
    written.push(name);
  }
  return { code: 0, written, adrs: adrs.length, kinds };
}

function main(argv) {
  let o; try { o = parseArgs(argv); } catch (e) { console.error(e.message); return 2; }
  const r = run(o);
  if (r.code === 0) console.log(`genRules: ${r.written.length} files (kinds: ${r.kinds.join(', ')}) from ${r.adrs} ADRs`);
  return r.code;
}

if (require.main === module) process.exit(main(process.argv.slice(2)));
module.exports = { parseArgs, scopeToFile, collectRules, presentKinds, renderFile, run };
