#!/usr/bin/env node
'use strict';

/**
 * genApiClient.js <contracts-dir> --config <config.yaml> --out-root <dir> [--check]
 *
 * OpenAPI bundle から、消費側 (frontend) が使う型付き API クライアントを生成する。
 * v1 の openapi-generator (typescript-fetch) codegen の置き換え。外部依存を使わず、
 * プラグイン内の小さな JSON-Schema → TypeScript 変換で決定論的に生成する。
 *
 * 生成物 (openapi 契約 <id> ごと):
 *  - packages/contracts/<id>/types.ts   components.schemas を TypeScript 型に変換
 *  - packages/contracts/<id>/client.ts  operationId ごとの型付き fetch 関数 (path/query/body/response by status)
 *  - packages/contracts/<id>/server.ts  operationId ↔ method/path 表 (provider が経路を突き合わせるため)
 *
 * すべて `// generated by distillery2 — do not edit` + `// basis:` ヘッダ付き・決定論的。
 * 同一入力なら同一出力。読み手 (frontend は client.ts、backend は types.ts/server.ts) は tier-impl.md を参照。
 */

const fs = require('node:fs');
const path = require('node:path');
const C = require('./lib/contractsDir');
const G = require('./lib/contractGraph');
const U = require('./lib/genUtil');
const compileContracts = require('./compileContracts');

// ---- JSON Schema → TypeScript 型式 ----------------------------------------

const refName = (ref) => String(ref).split('/').pop();
const isObj = (x) => x !== null && typeof x === 'object' && !Array.isArray(x);
const tsIdent = (name) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name));
const litOf = (v) => (typeof v === 'string' ? JSON.stringify(v) : v === null ? 'null' : String(v));

/** JSON Schema (2020-12 の部分集合) を TypeScript 型式 (文字列) に変換する。$ref は型名へ。 */
function schemaToTs(schema) {
  if (!isObj(schema)) return 'unknown';
  if (schema.$ref) return refName(schema.$ref);

  // 型の null 許容 (type: ['string','null']) を分離する
  let types = schema.type;
  let nullable = false;
  if (Array.isArray(types)) {
    nullable = types.includes('null');
    types = types.filter((t) => t !== 'null');
    if (types.length === 1) types = types[0];
  }

  const parts = [];
  if (Array.isArray(schema.enum) && schema.enum.length) {
    parts.push(schema.enum.map(litOf).join(' | '));
  } else if (Array.isArray(schema.oneOf) || Array.isArray(schema.anyOf)) {
    const alts = (schema.oneOf || schema.anyOf).map((s) => wrapUnion(schemaToTs(s)));
    parts.push(alts.join(' | '));
  } else if (Array.isArray(schema.allOf) || types === 'object' || isObj(schema.properties) || schema.additionalProperties != null) {
    // allOf は交差型として保持し、object の既知プロパティ・additionalProperties と合成する
    parts.push(objectTs(schema));
  } else if (Array.isArray(types)) {
    parts.push(types.map((t) => scalarTs(t, schema)).map(wrapUnion).join(' | '));
  } else if (types === 'array' || schema.items) {
    parts.push(`${wrapUnion(schemaToTs(schema.items || {}))}[]`);
  } else if (typeof types === 'string') {
    parts.push(scalarTs(types, schema));
  } else {
    parts.push('unknown');
  }

  let out = parts.join(' | ');
  if (nullable) out = `${wrapUnion(out)} | null`;
  return out;
}

function scalarTs(type, schema) {
  switch (type) {
    case 'string': return 'string';
    case 'integer':
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'array': return `${wrapUnion(schemaToTs(schema.items || {}))}[]`;
    case 'object': return objectTs(schema);
    default: return 'unknown';
  }
}

function wrapUnion(expr) {
  return /[|&]/.test(expr) && !/^\(.*\)$/.test(expr) ? `(${expr})` : expr;
}

/**
 * object スキーマを型式へ。allOf は交差型 (A & B) として保持し、既知プロパティの `{ ... }` と
 * additionalProperties の `Record<string, T>` を交差で合成する。
 * additionalProperties を index signature ではなく Record 交差にすることで、既知プロパティの型と
 * index 型が衝突しても TS2411 にならず必ずコンパイルできる (指摘 3)。
 */
function objectTs(schema) {
  const parts = [];
  if (Array.isArray(schema.allOf)) {
    for (const sub of schema.allOf) parts.push(wrapUnion(schemaToTs(sub)));
  }
  const props = isObj(schema.properties) ? schema.properties : {};
  const required = new Set(Array.isArray(schema.required) ? schema.required : []);
  const fields = [];
  for (const [key, sub] of Object.entries(props)) {
    const opt = required.has(key) ? '' : '?';
    fields.push(`${tsIdent(key)}${opt}: ${schemaToTs(sub)}`);
  }
  if (fields.length) parts.push(`{ ${fields.join('; ')} }`);
  const ap = schema.additionalProperties;
  let apType = null;
  if (ap === true) apType = 'unknown';
  else if (isObj(ap)) apType = schemaToTs(ap);
  if (apType !== null) parts.push(`Record<string, ${apType}>`);
  if (!parts.length) return 'Record<string, never>';
  return parts.join(' & ');
}

/** 交差や Record を含まない単一の `{ ... }` リテラルか判定する (interface に展開できるか)。 */
function isSingleObjectLiteral(expr) {
  const s = expr.trim();
  if (s[0] !== '{') return false;
  let depth = 0;
  for (let i = 0; i < s.length; i++) {
    const ch = s[i];
    if (ch === '{' || ch === '(' || ch === '[') depth++;
    else if (ch === '}' || ch === ')' || ch === ']') { depth--; if (depth === 0) return i === s.length - 1; }
  }
  return false;
}

/** 名前付き component スキーマを export 宣言に。単一 object リテラルは interface、交差型・その他は type alias。 */
function renderNamedSchema(name, schema) {
  const objectLike = isObj(schema) && !schema.$ref && !schema.enum
    && !Array.isArray(schema.oneOf) && !Array.isArray(schema.anyOf) && !Array.isArray(schema.type)
    && (schema.type === 'object' || isObj(schema.properties) || Array.isArray(schema.allOf) || schema.additionalProperties != null);
  if (objectLike) {
    const body = objectTs(schema);
    if (isSingleObjectLiteral(body)) {
      // `{ a: b; c: d }` を複数行 interface に展開する
      const inner = body.replace(/^\{ /, '').replace(/ \}$/, '');
      const lines = splitFields(inner);
      return `export interface ${name} {\n${lines.map((l) => `  ${l};`).join('\n')}${lines.length ? '\n' : ''}}`;
    }
    return `export type ${name} = ${body};`;
  }
  return `export type ${name} = ${schemaToTs(schema)};`;
}

/** `{ }` 内の `; ` 区切りをネスト対応で分割する。 */
function splitFields(inner) {
  const out = [];
  let depth = 0, buf = '';
  for (let i = 0; i < inner.length; i++) {
    const ch = inner[i];
    if (ch === '{' || ch === '(' || ch === '[') depth++;
    else if (ch === '}' || ch === ')' || ch === ']') depth--;
    if (ch === ';' && depth === 0) { out.push(buf.trim()); buf = ''; continue; }
    buf += ch;
  }
  if (buf.trim()) out.push(buf.trim());
  return out;
}

// ---- operation のパラメータ抽出 -------------------------------------------

const derefMaybe = (doc, node) => (isObj(node) && node.$ref ? G.resolve(doc, node.$ref) : node);

/** path item + operation の parameters を {name, in, required, schema} に平坦化 (name+in で重複排除)。 */
function collectParameters(bundle, entry) {
  const pathItem = bundle.paths[entry.path] || {};
  const raw = [...(pathItem.parameters || []), ...(entry.operation.parameters || [])];
  const map = new Map();
  for (const pRaw of raw) {
    const p = derefMaybe(bundle, pRaw);
    if (!isObj(p) || !p.name || !p.in) continue;
    map.set(`${p.in}:${p.name}`, { name: p.name, in: p.in, required: Boolean(p.required), schema: p.schema || {} });
  }
  return [...map.values()];
}

/** requestBody の application/json スキーマと required を返す。無ければ null。 */
function requestBodyInfo(bundle, entry) {
  const rb = derefMaybe(bundle, entry.operation.requestBody);
  if (!isObj(rb) || !isObj(rb.content)) return null;
  const media = rb.content['application/json'] || Object.values(rb.content)[0];
  if (!isObj(media) || !media.schema) return null;
  return { schema: media.schema, required: Boolean(rb.required) };
}

/** responses を [{status, schema|null}] に (2xx/4xx など documented status を昇順)。 */
function responseInfos(bundle, entry) {
  const out = [];
  for (const [status, respRaw] of Object.entries(entry.operation.responses || {})) {
    const resp = derefMaybe(bundle, respRaw);
    let schema = null;
    if (isObj(resp) && isObj(resp.content)) {
      const media = resp.content['application/json'] || resp.content['application/problem+json'] || Object.values(resp.content)[0];
      if (isObj(media) && media.schema) schema = media.schema;
    }
    out.push({ status, schema });
  }
  out.sort((a, b) => String(a.status).localeCompare(String(b.status)));
  return out;
}

// ---- 生成 ------------------------------------------------------------------

/** types.ts 本文 (ヘッダ抜き)。components.schemas を名前昇順で宣言する。 */
function buildTypes(bundle) {
  const schemas = (bundle.components && bundle.components.schemas) || {};
  const names = Object.keys(schemas).sort();
  if (!names.length) return 'export {};\n';
  return names.map((n) => renderNamedSchema(n, schemas[n])).join('\n\n') + '\n';
}

/** server.ts 本文: operationId ↔ method/path の const 表。 */
function buildServer(index) {
  const ops = [...index.keys()].sort();
  const rows = ops.map((op) => {
    const e = index.get(op);
    return `  ${tsIdent(op)}: { method: ${JSON.stringify(e.method)}, path: ${JSON.stringify(e.path)} },`;
  });
  return `export interface OperationRoute {
  method: string;
  path: string;
}

export const operations = {
${rows.join('\n')}
} as const satisfies Record<string, OperationRoute>;

export type OperationId = keyof typeof operations;
`;
}

/** client.ts 本文: operationId ごとの型付き fetch 関数。types.ts から型を import する。 */
function buildClient(bundle, index) {
  const schemas = (bundle.components && bundle.components.schemas) || {};
  const typeNames = Object.keys(schemas).sort();
  const ops = [...index.keys()].sort();

  const usedTypes = new Set();
  const noteType = (expr) => { for (const n of typeNames) if (new RegExp(`\\b${n}\\b`).test(expr)) usedTypes.add(n); };

  const fnBlocks = [];
  for (const op of ops) {
    const entry = index.get(op);
    const params = collectParameters(bundle, entry);
    const pathParams = params.filter((p) => p.in === 'path');
    const queryParams = params.filter((p) => p.in === 'query');
    const body = requestBodyInfo(bundle, entry);
    const responses = responseInfos(bundle, entry);
    const Cap = op.charAt(0).toUpperCase() + op.slice(1);

    // Args 型
    const argFields = [];
    for (const p of pathParams) { const t = schemaToTs(p.schema); noteType(t); argFields.push(`${tsIdent(p.name)}: ${t}`); }
    if (queryParams.length) {
      const qf = queryParams.map((p) => { const t = schemaToTs(p.schema); noteType(t); return `${tsIdent(p.name)}${p.required ? '' : '?'}: ${t}`; });
      argFields.push(`query${queryParams.every((p) => !p.required) ? '?' : ''}: { ${qf.join('; ')} }`);
    }
    if (body) { const t = schemaToTs(body.schema); noteType(t); argFields.push(`body${body.required ? '' : '?'}: ${t}`); }
    const hasArgs = argFields.length > 0;
    const argsType = `${Cap}Args`;
    const argsDecl = hasArgs ? `export interface ${argsType} {\n${argFields.map((f) => `  ${f};`).join('\n')}\n}\n\n` : '';

    // Response 型 (status で判別する union)
    const resultType = `${Cap}Result`;
    const resultAlts = responses.map(({ status, schema }) => {
      const data = schema ? schemaToTs(schema) : 'undefined';
      if (schema) noteType(data);
      const st = /^\d+$/.test(status) ? status : 'number';
      return `{ status: ${st}; data: ${data} }`;
    });
    const resultDecl = `export type ${resultType} =\n${resultAlts.map((a) => `  | ${a}`).join('\n')};\n\n`;

    // パス構築
    const pathExpr = '`${options.baseUrl ?? \'\'}' + entry.path.replace(/\{([^}]+)\}/g, (_, n) => '${encodeURIComponent(String(' + argAccess(n) + '))}') + '`';
    const argParam = hasArgs ? `args: ${argsType}, ` : '';
    const queryLine = queryParams.length
      ? `  const url = withQuery(${pathExpr}, args.query as Record<string, unknown> | undefined);\n`
      : `  const url = ${pathExpr};\n`;
    const bodyInit = body ? "\n    body: JSON.stringify(args.body)," : '';
    const contentType = body ? "\n      'content-type': 'application/json'," : '';

    fnBlocks.push(`${argsDecl}${resultDecl}export async function ${op}(${argParam}options: ClientOptions = {}): Promise<${resultType}> {
${queryLine}  const res = await (options.fetch ?? fetch)(url, {
    method: ${JSON.stringify(entry.method)},${bodyInit}
    headers: {${contentType}
      ...(options.headers ?? {}),
    },
  });
  const data = await parseBody(res);
  return { status: res.status, data } as ${resultType};
}`);
  }

  const importLine = usedTypes.size ? `import type { ${[...usedTypes].sort().join(', ')} } from './types';\n\n` : '';
  const preamble = `${importLine}export interface ClientOptions {
  /** ベース URL (末尾スラッシュ無し)。既定は同一オリジン。 */
  baseUrl?: string;
  /** 差し替え可能な fetch。テストで注入する。既定はグローバル fetch。 */
  fetch?: typeof fetch;
  /** 追加ヘッダ (認可トークン等)。 */
  headers?: Record<string, string>;
}

function withQuery(url: string, query?: Record<string, unknown>): string {
  if (!query) return url;
  const usp = new URLSearchParams();
  for (const [k, v] of Object.entries(query)) {
    if (v === undefined || v === null) continue;
    usp.append(k, String(v));
  }
  const qs = usp.toString();
  return qs ? \`\${url}?\${qs}\` : url;
}

async function parseBody(res: Response): Promise<unknown> {
  const text = await res.text();
  if (!text) return undefined;
  try { return JSON.parse(text); } catch { return text; }
}
`;
  return `${preamble}\n${fnBlocks.join('\n\n')}\n`;
}

// 識別子として使える名前は `args.name`、そうでなければ `args["name"]` を組み立てる (指摘 4)。
const argAccess = (name) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? `args.${name}` : `args[${JSON.stringify(name)}]`);

/**
 * openapi 契約 1 件から生成ファイル Map (rel → ヘッダ付き本文) を作る純関数。
 * genContractTests から呼ばれ、契約テストと同じ write/check/stale フローに乗る。
 */
function buildFiles({ bundle, contract, head }) {
  const index = G.operations(bundle, 'openapi');
  const base = path.posix.join('packages', 'contracts', contract.id);
  const files = new Map();
  files.set(path.posix.join(base, 'types.ts'), `${head}\n${buildTypes(bundle)}`);
  files.set(path.posix.join(base, 'server.ts'), `${head}\n${buildServer(index)}`);
  files.set(path.posix.join(base, 'client.ts'), `${head}\n${buildClient(bundle, index)}`);
  return files;
}

function run(contractsDir, { configPath, outRoot, check = false }) {
  const dir = fs.realpathSync(contractsDir);
  const catalog = C.readCatalog(dir);
  const config = U.readConfig(configPath);
  // genContractTests が付けるのと同じヘッダ (所有タグ込み)。違うと単体の --check が stale と誤判定する (0.1.13 実走 ④-4)
  const head = `${U.header(dir, config.docs_root || 'docs')}\n${U.OWNER_TAG}`;
  // bundle の鮮度を確かめる
  compileContracts.run(dir, true);
  const openapiContract = C.contractsOfType(catalog, 'openapi')[0];
  if (!openapiContract) return { status: check ? 'current' : 'generated', written: [], files: [] };
  const bundle = C.readBundle(dir, 'openapi.bundle.yaml');
  if (!bundle) throw new Error('openapi.bundle.yaml が無い。compileContracts を先に実行');
  const files = buildFiles({ bundle, contract: openapiContract, config, head });
  const stale = [], written = [];
  for (const [rel, text] of files) U.writeFileDet(path.join(outRoot, rel), text, check, stale, written, rel);
  if (check && stale.length) throw new Error(`Stale API client: ${stale.join(', ')}`);
  return { status: check ? 'current' : 'generated', written, files: [...files.keys()] };
}

module.exports = { run, buildFiles, buildTypes, buildClient, buildServer, schemaToTs, renderNamedSchema };

if (require.main === module) {
  try {
    const args = process.argv.slice(2);
    const valueFlags = new Set(['--config', '--out-root']);
    const positionals = args.filter((a, i) => !a.startsWith('--') && !valueFlags.has(args[i - 1]));
    const contractsDir = positionals[0];
    const configPath = argVal(args, '--config');
    const outRoot = argVal(args, '--out-root') || '.';
    if (!contractsDir || !configPath) { console.error('Usage: genApiClient.js <contracts-dir> --config <config.yaml> --out-root <dir> [--check]'); process.exit(2); }
    console.log(JSON.stringify(run(contractsDir, { configPath, outRoot, check: args.includes('--check') })));
  } catch (e) { console.error(e.message); process.exit(e.exitCode || 1); }
}
function argVal(args, flag) { const i = args.indexOf(flag); return i >= 0 ? args[i + 1] : null; }
