#!/usr/bin/env node
'use strict';

/**
 * genContractTests.js <contracts-dir> --config <config.yaml> [--uc <slug>] --out-root <dir> [--check]
 *
 * bundle と (任意で UC slice) から provider 契約テストと consumer stub を生成する:
 *  - openapi: apps/<provider>/test/contract/<operationId>.test.ts (vitest + supertest + ajv)。
 *    各 example で request を組み、status を検証し、response body を JSON Schema (2020-12) で検証する。
 *    example が無い operation/status は it.todo。
 *  - openapi consumer stub: packages/contracts/<id>/stubs/<operationId>.<status>.json (response example から)。
 *  - asyncapi: apps/<provider>/test/contract/messages.test.ts と
 *    packages/contracts/<id>/validators.ts (validateMessage(name, payload))。
 * 生成物は `// generated by distillery2 — do not edit`・`// basis:`・OWNER_TAG を持ち決定論的。
 *
 * 全生成 (--uc なし) では、所有する旧生成物 (OWNER_TAG 付き .ts と stubs/ 配下) のうち
 * 今回作らないものを stale として掃除する: 生成時は削除、--check 時は報告して exit 1。
 * --uc 指定時は subset しか作らないため掃除せず、代わりに slice の実在と bundle の鮮度を検証する
 * (slice 無し=exit 2 / 古い=exit 1)。
 */

const fs = require('node:fs');
const path = require('node:path');
const C = require('./lib/contractsDir');
const G = require('./lib/contractGraph');
const U = require('./lib/genUtil');
const compileContracts = require('./compileContracts');

const posixRel = (fromDir, to) => path.posix.relative(fromDir, to);
const json = v => JSON.stringify(v);

// genContractTests が所有する .ts (契約テスト・validators) の目印。
// stale 掃除で他の生成物 (genRdbDdl の db-schema.test.ts / tables.ts) を巻き込まないため、
// 共通の「generated by distillery2」より狭い、このツール固有のタグで所有を判定する。
const OWNER_TAG = '// distillery2-owner: d2-contract/genContractTests';
const ownsText = text => text.includes(OWNER_TAG);

/** response の status に対応する JSON Schema (content から) を取り出す。無ければ null。 */
function responseSchema(doc, resp) {
  const r = G.object(resp) && resp.$ref ? G.resolve(doc, resp.$ref) : resp;
  if (!G.object(r) || !G.object(r.content)) return null;
  const media = r.content['application/json'] || r.content['application/problem+json'] || Object.values(r.content)[0];
  return G.object(media) && media.schema ? media.schema : null;
}

/** ajv に渡す検証スキーマ。$ref 解決のため components を同梱する。 */
function ajvSchema(schema, componentsRef) {
  return Object.assign({}, schema, { components: { __ref: componentsRef } });
}

/**
 * status に対応する request example を名前で引く。
 *  - 同名の request example があればそれ (409 の response example `conflict` ↔ request example `conflict`)。
 *  - request が単数形 `example` のみのときは 2xx にだけ対応づける。
 *  - どちらも無ければ null (呼び出し側で it.todo にする)。
 */
function requestExampleFor(reqExamples, responseName, status) {
  const named = reqExamples.find(r => r.name === responseName);
  if (named) return named;
  const singular = reqExamples.find(r => r.name === 'example');
  if (singular && G.is2xx(status)) return singular;
  return null;
}

function sendClause(reqExample) { return reqExample ? `\n      .send(${json(reqExample.value)})` : ''; }

function openapiTest(op, entry, doc, testRel, componentsVar) {
  const method = entry.method.toLowerCase();
  const url = entry.path.replace(/\{([^}]+)\}/g, (_, p) => `test-${p}`);
  const ex = G.operationExamples(entry);
  const title = `${op} (${entry.method} ${entry.path})`;
  const blocks = [];

  if (ex.hasRequestBody && ex.requestExamples.length === 0) {
    blocks.push(`  it.todo('${op} — requestBody に example を追加する');`);
  } else {
    for (const [status, r] of Object.entries(ex.responses)) {
      if (!(G.is2xx(status) || G.is4xx(status))) continue;
      const schema = responseSchema(doc, entry.operation.responses[status]);
      if (r.hasContent && r.examples.length === 0) {
        blocks.push(`  it.todo('responds ${status} — response example を追加する');`);
        continue;
      }
      if (!r.hasContent) {
        // ボディ無しの応答。requestBody があるなら status に対応づく request を送る (無ければ todo)。
        const reqExample = ex.hasRequestBody ? requestExampleFor(ex.requestExamples, null, status) : null;
        if (ex.hasRequestBody && !reqExample) {
          blocks.push(`  it.todo('${status}: request example missing — 同名の request example を追加する');`);
          continue;
        }
        blocks.push(`  it('responds ${status} (no body)', async () => {
    const app = await createTestApp();
    const res = await request(app).${method}(\`${url}\`)${sendClause(reqExample)};
    expect(res.status).toBe(${Number(status)});
  });`);
        continue;
      }
      for (const example of r.examples) {
        const reqExample = ex.hasRequestBody ? requestExampleFor(ex.requestExamples, example.name, status) : null;
        if (ex.hasRequestBody && !reqExample) {
          // この status を起こす入力が契約に無い。同じ request を使い回すと必ず落ちるので todo にする。
          blocks.push(`  it.todo('${status}: request example "${example.name}" missing — 同名の request example を追加する');`);
          continue;
        }
        const validateExpr = schema
          ? `\n    const validate = ajv.compile(${json(ajvSchema(schema, componentsVar))});\n    expect(validate(res.body) || ajv.errorsText(validate.errors)).toBe(true);`
          : '';
        blocks.push(`  it('responds ${status} (example: ${example.name})', async () => {
    const app = await createTestApp();
    const res = await request(app).${method}(\`${url}\`)${sendClause(reqExample)};
    expect(res.status).toBe(${Number(status)});${validateExpr}
  });`);
      }
    }
  }
  return `describe('${title}', () => {\n${blocks.join('\n')}\n});`;
}

function run(contractsDir, { configPath, outRoot, uc = null, check = false }) {
  const dir = fs.realpathSync(contractsDir);
  const catalog = C.readCatalog(dir);
  const ucIndex = C.readUcIndex(dir);
  const config = U.readConfig(configPath);
  const head = `${U.header(dir, config.docs_root || 'docs')}\n${OWNER_TAG}`;
  const files = new Map();

  let ucRow = null;
  if (uc) {
    ucRow = ucIndex.ucs.find(u => u.slug === uc);
    if (!ucRow) throw new Error(`unknown uc: ${uc}`);
    // UC 指定時は slice の実在と bundle の鮮度を先に確かめる (古い契約からテストを作らない)。
    const slicePath = path.join(C.generatedDir(dir), 'slices', uc, 'contract-slice.json');
    if (!fs.existsSync(slicePath)) {
      const e = new Error(`contract slice not found for uc "${uc}": generated/slices/${uc}/contract-slice.json が無い。compileContracts を先に実行`);
      e.exitCode = 2;
      throw e;
    }
    try {
      compileContracts.run(dir, true); // --check 相当: source から再 bundle して generated と突合
    } catch (e) {
      throw new Error(`contracts are stale for uc "${uc}": ${e.message}. compileContracts を先に実行してから再生成する`);
    }
  }

  const openapiContract = C.contractsOfType(catalog, 'openapi')[0];
  const asyncapiContract = C.contractsOfType(catalog, 'asyncapi')[0];

  // --- OpenAPI provider tests + consumer stubs ---
  if (openapiContract) {
    const bundle = C.readBundle(dir, 'openapi.bundle.yaml');
    if (!bundle) throw new Error('openapi.bundle.yaml が無い。compileContracts を先に実行');
    const index = G.operations(bundle, 'openapi');
    const providerDir = U.tierDir(config, openapiContract.provider);
    const componentsJson = json({ schemas: bundle.components?.schemas || {} });
    let ops = [...index.keys()];
    if (ucRow) ops = ops.filter(o => ucRow.operations.includes(o));
    ops.sort();
    for (const op of ops) {
      const entry = index.get(op);
      const testRel = path.posix.join(providerDir, 'test', 'contract', `${op}.test.ts`);
      const appImport = posixRel(path.posix.dirname(testRel), path.posix.join(providerDir, 'src', 'test-app'));
      const body = openapiTest(op, entry, bundle, testRel, 'components');
      const text = `${head}
import { describe, it, expect } from 'vitest';
import request from 'supertest';
import Ajv2020 from 'ajv/dist/2020';
import addFormats from 'ajv-formats';
import { createTestApp } from '${appImport}';

const components = ${componentsJson};
const ajv = new Ajv2020({ strict: false, allErrors: true });
addFormats(ajv);

${body}
`.replace(/\{"__ref":"components"\}/g, 'components');
      files.set(testRel, text);
      // consumer stubs: status ごとに最初の response example
      const ex = G.operationExamples(entry);
      for (const [status, r] of Object.entries(ex.responses)) {
        if (!r.examples.length) continue;
        const stubRel = path.posix.join('packages', 'contracts', openapiContract.id, 'stubs', `${op}.${status}.json`);
        files.set(stubRel, U.jsonDet(r.examples[0].value));
      }
    }
  }

  // --- AsyncAPI message tests + validators ---
  if (asyncapiContract) {
    const bundle = C.readBundle(dir, 'asyncapi.bundle.yaml');
    if (!bundle) throw new Error('asyncapi.bundle.yaml が無い。compileContracts を先に実行');
    const providerDir = U.tierDir(config, asyncapiContract.provider);
    const messages = bundle.components?.messages || {};
    const componentsJson = json({ schemas: bundle.components?.schemas || {} });
    let names = Object.keys(messages);
    if (ucRow) names = names.filter(n => ucRow.messages.includes(n));
    names.sort();

    const payloadSchemas = {};
    const testBlocks = [];
    for (const name of names) {
      const msg = messages[name];
      const payload = msg.payload || {};
      payloadSchemas[name] = { schema: Object.assign({}, payload, { components: '__COMPONENTS__' }) };
      const examples = G.messageExamples(msg);
      if (!examples.length) { testBlocks.push(`  it.todo('${name} — message example を追加する');`); continue; }
      for (const example of examples) {
        testBlocks.push(`  it('${name} example (${example.name}) matches payload schema', () => {
    const r = validateMessage('${name}', ${json(example.payload)});
    expect(r.valid || JSON.stringify(r.errors)).toBe(true);
  });`);
      }
    }

    const validatorsRel = path.posix.join('packages', 'contracts', asyncapiContract.id, 'validators.ts');
    const schemasLiteral = Object.entries(payloadSchemas)
      .map(([n, v]) => `  ${json(n)}: ${json(v.schema).replace('"__COMPONENTS__"', 'components')}`).join(',\n');
    files.set(validatorsRel, `${head}
import Ajv2020 from 'ajv/dist/2020';
import addFormats from 'ajv-formats';

const components = ${componentsJson};
const payloadSchemas: Record<string, object> = {
${schemasLiteral}
};
const ajv = new Ajv2020({ strict: false, allErrors: true });
addFormats(ajv);

export function validateMessage(name: string, payload: unknown): { valid: boolean; errors: unknown } {
  const schema = payloadSchemas[name];
  if (!schema) throw new Error(\`unknown message: \${name}\`);
  const validate = ajv.compile(schema);
  const valid = validate(payload) as boolean;
  return { valid, errors: validate.errors };
}
`);

    const testRel = path.posix.join(providerDir, 'test', 'contract', 'messages.test.ts');
    const validatorsImport = posixRel(path.posix.dirname(testRel), path.posix.join('packages', 'contracts', asyncapiContract.id, 'validators'));
    files.set(testRel, `${head}
import { describe, it, expect } from 'vitest';
import { validateMessage } from '${validatorsImport}';

describe('message contract examples', () => {
${testBlocks.join('\n')}
});
`);
  }

  const stale = [], written = [];
  for (const [rel, text] of files) U.writeFileDet(path.join(outRoot, rel), text, check, stale, written, rel);

  // 不要になった旧生成物の掃除。UC 指定時は subset しか作らないので掃除しない (他 UC の生成物を消さない)。
  const removed = [], orphaned = [];
  if (!ucRow) {
    const current = new Set([...files.keys()]);
    for (const rel of listGeneratedArtifacts(outRoot, catalog, config)) {
      if (current.has(rel)) continue;
      if (check) { orphaned.push(rel); continue; }
      fs.rmSync(path.join(outRoot, rel), { force: true });
      removed.push(rel);
    }
  }

  if (check && (stale.length || orphaned.length)) {
    throw new Error(`Stale generated tests: ${[...stale, ...orphaned.map(r => `${r} (obsolete)`)].join(', ')}`);
  }
  return { status: check ? 'current' : 'generated', written, removed, files: [...files.keys()] };
}

/**
 * genContractTests が所有しうる既存ファイルを列挙する (outRoot 相対 posix)。
 *  - apps/<provider>/test/contract/*.ts のうち OWNER_TAG を持つもの (db-schema.test.ts 等は対象外)。
 *  - packages/contracts/<id>/stubs/* (このツール専用ディレクトリなので全件)。
 *  - packages/contracts/<id>/validators.ts のうち OWNER_TAG を持つもの (tables.ts は対象外)。
 */
function listGeneratedArtifacts(outRoot, catalog, config) {
  const out = [];
  const providers = new Set();
  for (const c of catalog.contracts) if (c.type === 'openapi' || c.type === 'asyncapi') {
    try { providers.add(U.tierDir(config, c.provider)); } catch { /* provider が config に無い場合は無視 */ }
  }
  for (const providerDir of providers) {
    const dirAbs = path.join(outRoot, providerDir, 'test', 'contract');
    if (!fs.existsSync(dirAbs)) continue;
    for (const name of fs.readdirSync(dirAbs)) {
      if (!name.endsWith('.ts')) continue;
      const rel = path.posix.join(providerDir, 'test', 'contract', name);
      if (ownsText(readSafe(path.join(outRoot, rel)))) out.push(rel);
    }
  }
  const pkgRoot = path.join(outRoot, 'packages', 'contracts');
  if (fs.existsSync(pkgRoot)) for (const id of fs.readdirSync(pkgRoot)) {
    const stubsAbs = path.join(pkgRoot, id, 'stubs');
    if (fs.existsSync(stubsAbs)) for (const name of fs.readdirSync(stubsAbs)) {
      out.push(path.posix.join('packages', 'contracts', id, 'stubs', name));
    }
    const validatorsRel = path.posix.join('packages', 'contracts', id, 'validators.ts');
    if (fs.existsSync(path.join(outRoot, validatorsRel)) && ownsText(readSafe(path.join(outRoot, validatorsRel)))) out.push(validatorsRel);
  }
  return out;
}

function readSafe(p) { try { return fs.readFileSync(p, 'utf8'); } catch { return ''; } }

module.exports = { run, openapiTest };

if (require.main === module) {
  try {
    const args = process.argv.slice(2);
    const valueFlags = new Set(['--config', '--uc', '--out-root']);
    const positionals = args.filter((a, i) => !a.startsWith('--') && !valueFlags.has(args[i - 1]));
    const contractsDir = positionals[0];
    const configPath = argVal(args, '--config');
    const outRoot = argVal(args, '--out-root') || '.';
    const uc = argVal(args, '--uc');
    if (!contractsDir || !configPath) { console.error('Usage: genContractTests.js <contracts-dir> --config <config.yaml> [--uc <slug>] --out-root <dir> [--check]'); process.exit(2); }
    console.log(JSON.stringify(run(contractsDir, { configPath, outRoot, uc, check: args.includes('--check') })));
  } catch (e) { console.error(e.message); process.exit(e.exitCode || 1); }
}
function argVal(args, flag) { const i = args.indexOf(flag); return i >= 0 ? args[i + 1] : null; }
