#!/usr/bin/env node
'use strict';

/**
 * genContractTests.js <contracts-dir> --config <config.yaml> [--uc <slug>] --out-root <dir> [--check]
 *
 * bundle と (任意で UC slice) から provider 契約テストと consumer stub を生成する:
 *  - openapi: apps/<provider>/test/contract/<operationId>.test.ts (vitest + supertest + ajv)。
 *    各 example で request を組み、status を検証し、response body を JSON Schema (2020-12) で検証する。
 *    example が無い operation/status は it.todo。
 *  - openapi consumer stub: packages/contracts/<id>/stubs/<operationId>.<status>.json (response example から)。
 *  - asyncapi: apps/<provider>/test/contract/messages.test.ts と
 *    packages/contracts/<id>/validators.ts (validateMessage(name, payload))。
 * 生成物は `// generated by distillery2 — do not edit` と `// basis:` を持ち決定論的。
 */

const fs = require('node:fs');
const path = require('node:path');
const C = require('./lib/contractsDir');
const G = require('./lib/contractGraph');
const U = require('./lib/genUtil');

const posixRel = (fromDir, to) => path.posix.relative(fromDir, to);
const json = v => JSON.stringify(v);

/** response の status に対応する JSON Schema (content から) を取り出す。無ければ null。 */
function responseSchema(doc, resp) {
  const r = G.object(resp) && resp.$ref ? G.resolve(doc, resp.$ref) : resp;
  if (!G.object(r) || !G.object(r.content)) return null;
  const media = r.content['application/json'] || r.content['application/problem+json'] || Object.values(r.content)[0];
  return G.object(media) && media.schema ? media.schema : null;
}

/** ajv に渡す検証スキーマ。$ref 解決のため components を同梱する。 */
function ajvSchema(schema, componentsRef) {
  return Object.assign({}, schema, { components: { __ref: componentsRef } });
}

function openapiTest(op, entry, doc, testRel, componentsVar) {
  const method = entry.method.toLowerCase();
  const url = entry.path.replace(/\{([^}]+)\}/g, (_, p) => `test-${p}`);
  const ex = G.operationExamples(entry);
  const title = `${op} (${entry.method} ${entry.path})`;
  const blocks = [];

  const reqExample = ex.requestExamples[0];
  const buildReq = reqExample ? `\n      .send(${json(reqExample.value)})` : '';

  if (ex.hasRequestBody && !reqExample) {
    blocks.push(`  it.todo('${op} — requestBody に example を追加する');`);
  } else {
    for (const [status, r] of Object.entries(ex.responses)) {
      if (!(G.is2xx(status) || G.is4xx(status))) continue;
      const schema = responseSchema(doc, op && entry.operation.responses[status]);
      if (r.hasContent && r.examples.length === 0) {
        blocks.push(`  it.todo('responds ${status} — response example を追加する');`);
        continue;
      }
      if (!r.hasContent) {
        blocks.push(`  it('responds ${status} (no body)', async () => {
    const app = await createTestApp();
    const res = await request(app).${method}(\`${url}\`)${buildReq};
    expect(res.status).toBe(${Number(status)});
  });`);
        continue;
      }
      for (const example of r.examples) {
        const validateExpr = schema
          ? `\n    const validate = ajv.compile(${json(ajvSchema(schema, componentsVar))});\n    expect(validate(res.body) || ajv.errorsText(validate.errors)).toBe(true);`
          : '';
        blocks.push(`  it('responds ${status} (example: ${example.name})', async () => {
    const app = await createTestApp();
    const res = await request(app).${method}(\`${url}\`)${buildReq};
    expect(res.status).toBe(${Number(status)});${validateExpr}
  });`);
      }
    }
  }
  return `describe('${title}', () => {\n${blocks.join('\n')}\n});`;
}

function run(contractsDir, { configPath, outRoot, uc = null, check = false }) {
  const dir = fs.realpathSync(contractsDir);
  const catalog = C.readCatalog(dir);
  const ucIndex = C.readUcIndex(dir);
  const config = U.readConfig(configPath);
  const head = U.header(dir, config.docs_root || 'docs');
  const files = new Map();

  let ucRow = null;
  if (uc) { ucRow = ucIndex.ucs.find(u => u.slug === uc); if (!ucRow) throw new Error(`unknown uc: ${uc}`); }

  const openapiContract = C.contractsOfType(catalog, 'openapi')[0];
  const asyncapiContract = C.contractsOfType(catalog, 'asyncapi')[0];

  // --- OpenAPI provider tests + consumer stubs ---
  if (openapiContract) {
    const bundle = C.readBundle(dir, 'openapi.bundle.yaml');
    if (!bundle) throw new Error('openapi.bundle.yaml が無い。compileContracts を先に実行');
    const index = G.operations(bundle, 'openapi');
    const providerDir = U.tierDir(config, openapiContract.provider);
    const componentsJson = json({ schemas: bundle.components?.schemas || {} });
    let ops = [...index.keys()];
    if (ucRow) ops = ops.filter(o => ucRow.operations.includes(o));
    ops.sort();
    for (const op of ops) {
      const entry = index.get(op);
      const testRel = path.posix.join(providerDir, 'test', 'contract', `${op}.test.ts`);
      const appImport = posixRel(path.posix.dirname(testRel), path.posix.join(providerDir, 'src', 'test-app'));
      const body = openapiTest(op, entry, bundle, testRel, 'components');
      const text = `${head}
import { describe, it, expect } from 'vitest';
import request from 'supertest';
import Ajv2020 from 'ajv/dist/2020';
import addFormats from 'ajv-formats';
import { createTestApp } from '${appImport}';

const components = ${componentsJson};
const ajv = new Ajv2020({ strict: false, allErrors: true });
addFormats(ajv);

${body}
`.replace(/\{"__ref":"components"\}/g, 'components');
      files.set(testRel, text);
      // consumer stubs: status ごとに最初の response example
      const ex = G.operationExamples(entry);
      for (const [status, r] of Object.entries(ex.responses)) {
        if (!r.examples.length) continue;
        const stubRel = path.posix.join('packages', 'contracts', openapiContract.id, 'stubs', `${op}.${status}.json`);
        files.set(stubRel, U.jsonDet(r.examples[0].value));
      }
    }
  }

  // --- AsyncAPI message tests + validators ---
  if (asyncapiContract) {
    const bundle = C.readBundle(dir, 'asyncapi.bundle.yaml');
    if (!bundle) throw new Error('asyncapi.bundle.yaml が無い。compileContracts を先に実行');
    const providerDir = U.tierDir(config, asyncapiContract.provider);
    const messages = bundle.components?.messages || {};
    const componentsJson = json({ schemas: bundle.components?.schemas || {} });
    let names = Object.keys(messages);
    if (ucRow) names = names.filter(n => ucRow.messages.includes(n));
    names.sort();

    const payloadSchemas = {};
    const testBlocks = [];
    for (const name of names) {
      const msg = messages[name];
      const payload = msg.payload || {};
      payloadSchemas[name] = { schema: Object.assign({}, payload, { components: '__COMPONENTS__' }) };
      const examples = G.messageExamples(msg);
      if (!examples.length) { testBlocks.push(`  it.todo('${name} — message example を追加する');`); continue; }
      for (const example of examples) {
        testBlocks.push(`  it('${name} example (${example.name}) matches payload schema', () => {
    const r = validateMessage('${name}', ${json(example.payload)});
    expect(r.valid || JSON.stringify(r.errors)).toBe(true);
  });`);
      }
    }

    const validatorsRel = path.posix.join('packages', 'contracts', asyncapiContract.id, 'validators.ts');
    const schemasLiteral = Object.entries(payloadSchemas)
      .map(([n, v]) => `  ${json(n)}: ${json(v.schema).replace('"__COMPONENTS__"', 'components')}`).join(',\n');
    files.set(validatorsRel, `${head}
import Ajv2020 from 'ajv/dist/2020';
import addFormats from 'ajv-formats';

const components = ${componentsJson};
const payloadSchemas: Record<string, object> = {
${schemasLiteral}
};
const ajv = new Ajv2020({ strict: false, allErrors: true });
addFormats(ajv);

export function validateMessage(name: string, payload: unknown): { valid: boolean; errors: unknown } {
  const schema = payloadSchemas[name];
  if (!schema) throw new Error(\`unknown message: \${name}\`);
  const validate = ajv.compile(schema);
  const valid = validate(payload) as boolean;
  return { valid, errors: validate.errors };
}
`);

    const testRel = path.posix.join(providerDir, 'test', 'contract', 'messages.test.ts');
    const validatorsImport = posixRel(path.posix.dirname(testRel), path.posix.join('packages', 'contracts', asyncapiContract.id, 'validators'));
    files.set(testRel, `${head}
import { describe, it, expect } from 'vitest';
import { validateMessage } from '${validatorsImport}';

describe('message contract examples', () => {
${testBlocks.join('\n')}
});
`);
  }

  const stale = [], written = [];
  for (const [rel, text] of files) U.writeFileDet(path.join(outRoot, rel), text, check, stale, written, rel);
  if (check && stale.length) throw new Error(`Stale generated tests: ${stale.join(', ')}`);
  return { status: check ? 'current' : 'generated', written, files: [...files.keys()] };
}

module.exports = { run, openapiTest };

if (require.main === module) {
  try {
    const args = process.argv.slice(2);
    const valueFlags = new Set(['--config', '--uc', '--out-root']);
    const positionals = args.filter((a, i) => !a.startsWith('--') && !valueFlags.has(args[i - 1]));
    const contractsDir = positionals[0];
    const configPath = argVal(args, '--config');
    const outRoot = argVal(args, '--out-root') || '.';
    const uc = argVal(args, '--uc');
    if (!contractsDir || !configPath) { console.error('Usage: genContractTests.js <contracts-dir> --config <config.yaml> [--uc <slug>] --out-root <dir> [--check]'); process.exit(2); }
    console.log(JSON.stringify(run(contractsDir, { configPath, outRoot, uc, check: args.includes('--check') })));
  } catch (e) { console.error(e.message); process.exit(1); }
}
function argVal(args, flag) { const i = args.indexOf(flag); return i >= 0 ? args[i + 1] : null; }
