#!/usr/bin/env node
'use strict';

/**
 * genRdbDdl.js <contracts-dir> --config <config.yaml> --out-root <dir> [--check]
 *
 * generated/rdb-schema.bundle.yaml から、datastore_owner ティアの Postgres migration・
 * pglite による DB 契約テスト・packages/contracts/<id>/tables.ts (row 型 + 名前定数) を生成する。
 * v1 の RDB codegen 案 (row 型 + テーブル/列名定数) を踏襲。生成物は決定論的。
 */

const fs = require('node:fs');
const path = require('node:path');
const C = require('./lib/contractsDir');
const U = require('./lib/genUtil');
const { parseYaml } = require('../../../scripts/lib/yaml');

const PG_TYPE = { string: 'text', text: 'text', integer: 'integer', bigint: 'bigint', decimal: 'numeric', boolean: 'boolean', date: 'date', datetime: 'timestamptz', uuid: 'uuid' };
const TS_TYPE = { string: 'string', text: 'string', uuid: 'string', integer: 'number', bigint: 'number', decimal: 'number', boolean: 'boolean', date: 'string', datetime: 'string' };
const enumTypeName = (table, col) => `${table}_${col}`;

/** FK 依存順 (参照先が先) にテーブルを並べる。循環時はアルファベット順にフォールバック。 */
function topoSort(tables) {
  const byName = new Map(tables.map(t => [t.name, t]));
  const out = [], visiting = new Set(), done = new Set();
  let cyclic = false;
  const visit = t => {
    if (done.has(t.name)) return;
    if (visiting.has(t.name)) { cyclic = true; return; }
    visiting.add(t.name);
    for (const fk of t.foreign_keys || []) { const dep = byName.get(fk.references.table); if (dep && dep !== t) visit(dep); }
    visiting.delete(t.name); done.add(t.name); out.push(t);
  };
  for (const t of [...tables].sort((a, b) => a.name.localeCompare(b.name, 'en'))) visit(t);
  return cyclic ? [...tables].sort((a, b) => a.name.localeCompare(b.name, 'en')) : out;
}

function columnDef(table, col) {
  const type = col.enum ? enumTypeName(table.name, col.name) : (PG_TYPE[col.type] || 'text');
  return `  ${col.name} ${type}${col.nullable ? '' : ' NOT NULL'}`;
}

/** FK 制約名。テーブル名 + FK 列で決定論的に組む (循環時も安定)。 */
function fkConstraintName(table, fk) { return `${table.name}_${fk.columns.join('_')}_fkey`; }

function tableSql(table) {
  const lines = [];
  const cols = table.columns.map(c => columnDef(table, c));
  cols.push(`  PRIMARY KEY (${table.primary_key.join(', ')})`);
  // FK は CREATE TABLE に埋めず、全テーブル作成後に ALTER TABLE で足す (循環 FK でも参照先が必ず存在する)。
  for (const idx of table.indexes || []) if (idx.unique) cols.push(`  CONSTRAINT ${idx.name} UNIQUE (${idx.columns.join(', ')})`);
  lines.push(`CREATE TABLE IF NOT EXISTS ${table.name} (`);
  lines.push(cols.join(',\n'));
  lines.push(`);`);
  for (const idx of table.indexes || []) if (!idx.unique) lines.push(`CREATE INDEX IF NOT EXISTS ${idx.name} ON ${table.name} (${idx.columns.join(', ')});`);
  return lines.join('\n');
}

/** 1 本の FK を冪等な ALTER TABLE ADD CONSTRAINT にする。ADD CONSTRAINT には IF NOT EXISTS が無いため DO ブロックで冪等化。 */
function foreignKeySql(table, fk) {
  const onDelete = fk.on_delete ? ` ON DELETE ${fk.on_delete}` : '';
  const name = fkConstraintName(table, fk);
  const clause = `ALTER TABLE ${table.name} ADD CONSTRAINT ${name} FOREIGN KEY (${fk.columns.join(', ')}) REFERENCES ${fk.references.table} (${fk.references.columns.join(', ')})${onDelete}`;
  return `DO $$ BEGIN\n  ${clause};\nEXCEPTION WHEN duplicate_object THEN null;\nEND $$;`;
}

function enumTypeSql(table, col) {
  const values = col.enum.map(v => `'${String(v).replace(/'/g, "''")}'`).join(', ');
  // CREATE TYPE には IF NOT EXISTS が無いため DO ブロックで冪等化する
  return `DO $$ BEGIN\n  CREATE TYPE ${enumTypeName(table.name, col.name)} AS ENUM (${values});\nEXCEPTION WHEN duplicate_object THEN null;\nEND $$;`;
}

function buildSql(tables) {
  const ordered = topoSort(tables);
  const blocks = ['-- generated by distillery2 — do not edit', ''];
  const enumCols = [];
  for (const t of [...tables].sort((a, b) => a.name.localeCompare(b.name, 'en'))) for (const c of t.columns) if (c.enum) enumCols.push([t, c]);
  for (const [t, c] of enumCols) blocks.push(enumTypeSql(t, c));
  if (enumCols.length) blocks.push('');
  for (const t of ordered) { blocks.push(tableSql(t)); blocks.push(''); }
  // 全テーブル作成後に FK を足す。テーブル名昇順で決定論的に (循環 FK でも順序に依存しない)。
  const fkBlocks = [];
  for (const t of [...tables].sort((a, b) => a.name.localeCompare(b.name, 'en'))) {
    for (const fk of t.foreign_keys || []) fkBlocks.push(foreignKeySql(t, fk));
  }
  if (fkBlocks.length) { blocks.push('-- foreign keys (ALTER で後付け: 循環参照に対応)'); for (const b of fkBlocks) { blocks.push(b); blocks.push(''); } }
  return blocks.join('\n').replace(/\n+$/, '\n');
}

function rowTypes(tables, header) {
  const lines = [header, ''];
  for (const t of [...tables].sort((a, b) => a.name.localeCompare(b.name, 'en'))) {
    const typeName = pascal(t.name) + 'Row';
    lines.push(`export type ${typeName} = {`);
    for (const c of t.columns) {
      const base = c.enum ? c.enum.map(v => `'${v}'`).join(' | ') : (TS_TYPE[c.type] || 'string');
      lines.push(`  ${c.name}: ${base}${c.nullable ? ' | null' : ''};`);
    }
    lines.push('};');
    lines.push(`export const ${constName(t.name)}_TABLE = '${t.name}' as const;`);
    const cols = t.columns.map(c => `${c.name}: '${c.name}'`).join(', ');
    lines.push(`export const ${constName(t.name)}_COLUMNS = { ${cols} } as const;`);
    lines.push('');
  }
  return lines.join('\n').replace(/\n+$/, '\n');
}

function dbSchemaTest(tables, ownerDir, header) {
  const embedded = U.jsonDet(tables.map(t => ({
    name: t.name,
    columns: t.columns.map(c => ({ name: c.name, type: c.enum ? enumTypeName(t.name, c.name) : (PG_TYPE[c.type] || 'text'), nullable: c.nullable })),
    primary_key: t.primary_key,
  }))).trimEnd();
  return `${header}
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PGlite } from '@electric-sql/pglite';

const here = dirname(fileURLToPath(import.meta.url));
const migration = readFileSync(join(here, '..', '..', 'migrations', '0001_schema.sql'), 'utf8');
const expected = ${embedded};

let db: PGlite;
beforeAll(async () => { db = new PGlite(); await db.exec(migration); });
afterAll(async () => { await db.close(); });

describe('db schema contract', () => {
  for (const table of expected) {
    it(\`\${table.name} matches the contract bundle\`, async () => {
      const cols = await db.query<{ column_name: string; data_type: string; udt_name: string; is_nullable: string }>(
        \`SELECT column_name, data_type, udt_name, is_nullable FROM information_schema.columns WHERE table_name = $1\`, [table.name]);
      const actual = new Map(cols.rows.map(r => [r.column_name, r]));
      expect(new Set(actual.keys())).toEqual(new Set(table.columns.map(c => c.name)));
      for (const col of table.columns) {
        const got = actual.get(col.name)!;
        const gotType = got.data_type === 'USER-DEFINED' ? got.udt_name : got.data_type;
        expect(normalize(gotType)).toBe(normalize(col.type));
        expect(got.is_nullable === 'YES').toBe(col.nullable);
      }
      const pk = await db.query<{ column_name: string }>(
        \`SELECT kcu.column_name FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu ON kcu.constraint_name = tc.constraint_name
         WHERE tc.table_name = $1 AND tc.constraint_type = 'PRIMARY KEY'\`, [table.name]);
      expect(new Set(pk.rows.map(r => r.column_name))).toEqual(new Set(table.primary_key));
    });
  }
});

function normalize(t: string): string {
  const map: Record<string, string> = { 'character varying': 'text', 'timestamp with time zone': 'timestamptz', 'timestamp without time zone': 'timestamp' };
  return map[t] ?? t;
}
`;
}

function pascal(s) { return s.split(/[_-]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(''); }
function constName(s) { return s.replace(/-/g, '_').toUpperCase(); }

function run(contractsDir, { configPath, outRoot, check = false }) {
  const dir = fs.realpathSync(contractsDir);
  const bundlePath = path.join(C.generatedDir(dir), 'rdb-schema.bundle.yaml');
  if (!fs.existsSync(bundlePath)) throw new Error('rdb-schema.bundle.yaml が無い。compileRdbSchema を先に実行');
  const bundle = parseYaml(fs.readFileSync(bundlePath, 'utf8'));
  const tables = bundle.tables || [];
  const config = U.readConfig(configPath);
  const rdbContract = (config.contracts || []).find(c => c.type === 'rdb-schema');
  if (!rdbContract) throw new Error('config.yaml: rdb-schema 契約が無い');
  const owner = config.datastore_owner;
  if (!owner) throw new Error('config.yaml: datastore_owner が無い');
  const ownerDir = U.tierDir(config, owner);
  const head = U.header(dir, config.docs_root || 'docs');

  const files = new Map();
  files.set(path.join(ownerDir, 'migrations', '0001_schema.sql'), buildSql(tables));
  files.set(path.join(ownerDir, 'test', 'contract', 'db-schema.test.ts'), dbSchemaTest(tables, ownerDir, head));
  files.set(path.join('packages', 'contracts', rdbContract.id, 'tables.ts'), rowTypes(tables, head));

  const stale = [], written = [];
  for (const [rel, text] of files) U.writeFileDet(path.join(outRoot, rel), text, check, stale, written, rel);
  if (check && stale.length) throw new Error(`Stale generated files: ${stale.join(', ')}`);
  return { status: check ? 'current' : 'generated', written, files: [...files.keys()] };
}

module.exports = { run, buildSql, rowTypes, dbSchemaTest, foreignKeySql, fkConstraintName };

if (require.main === module) {
  try {
    const args = process.argv.slice(2);
    const contractsDir = args.find(a => !a.startsWith('--'));
    const configPath = argVal(args, '--config');
    const outRoot = argVal(args, '--out-root') || '.';
    if (!contractsDir || !configPath) { console.error('Usage: genRdbDdl.js <contracts-dir> --config <config.yaml> --out-root <dir> [--check]'); process.exit(2); }
    console.log(JSON.stringify(run(contractsDir, { configPath, outRoot, check: args.includes('--check') })));
  } catch (e) { console.error(e.message); process.exit(1); }
}
function argVal(args, flag) { const i = args.indexOf(flag); return i >= 0 ? args[i + 1] : null; }
