// generated by distillery2 — do not edit
// biome-ignore-all format: generated (do not edit)
// biome-ignore-all lint: generated (do not edit)
// basis: contracts@78204463d891ad94ca15a2cc757ae230a2289d94

export type AuditLogsRow = {
  audit_id: string;
  actor_subject: string;
  actor_role: 'librarian' | 'patron';
  action: string;
  target_type: string;
  target_id: string;
  occurred_at: string;
};
export const AUDIT_LOGS_TABLE = 'audit_logs' as const;
export const AUDIT_LOGS_COLUMNS = { audit_id: 'audit_id', actor_subject: 'actor_subject', actor_role: 'actor_role', action: 'action', target_type: 'target_type', target_id: 'target_id', occurred_at: 'occurred_at' } as const;

export type BookEventsRow = {
  event_id: string;
  book_id: string;
  sequence: number;
  event_type: string;
  payload: string;
  actor_subject: string | null;
  occurred_at: string;
};
export const BOOK_EVENTS_TABLE = 'book_events' as const;
export const BOOK_EVENTS_COLUMNS = { event_id: 'event_id', book_id: 'book_id', sequence: 'sequence', event_type: 'event_type', payload: 'payload', actor_subject: 'actor_subject', occurred_at: 'occurred_at' } as const;

export type BooksRow = {
  book_id: string;
  title: string;
  author: string;
  isbn: string | null;
  publisher: string | null;
  genre: string | null;
  media_type: 'paper' | 'ebook';
  status: 'available' | 'on_loan' | 'awaiting_pickup';
  registered_on: string;
  deleted_on: string | null;
  version: number;
  updated_at: string;
};
export const BOOKS_TABLE = 'books' as const;
export const BOOKS_COLUMNS = { book_id: 'book_id', title: 'title', author: 'author', isbn: 'isbn', publisher: 'publisher', genre: 'genre', media_type: 'media_type', status: 'status', registered_on: 'registered_on', deleted_on: 'deleted_on', version: 'version', updated_at: 'updated_at' } as const;

export type IdempotencyKeysRow = {
  idempotency_key: string;
  principal_subject: string;
  operation_id: string;
  request_hash: string;
  response_status: number;
  response_body: string | null;
  created_at: string;
};
export const IDEMPOTENCY_KEYS_TABLE = 'idempotency_keys' as const;
export const IDEMPOTENCY_KEYS_COLUMNS = { idempotency_key: 'idempotency_key', principal_subject: 'principal_subject', operation_id: 'operation_id', request_hash: 'request_hash', response_status: 'response_status', response_body: 'response_body', created_at: 'created_at' } as const;

export type LoanEventsRow = {
  event_id: string;
  loan_id: string;
  sequence: number;
  event_type: string;
  payload: string;
  actor_subject: string | null;
  occurred_at: string;
};
export const LOAN_EVENTS_TABLE = 'loan_events' as const;
export const LOAN_EVENTS_COLUMNS = { event_id: 'event_id', loan_id: 'loan_id', sequence: 'sequence', event_type: 'event_type', payload: 'payload', actor_subject: 'actor_subject', occurred_at: 'occurred_at' } as const;

export type LoansRow = {
  loan_id: string;
  patron_number: string;
  book_id: string;
  reservation_id: string | null;
  loaned_on: string;
  due_date: string;
  returned_on: string | null;
  status: 'on_loan' | 'returned' | 'overdue';
  version: number;
  updated_at: string;
};
export const LOANS_TABLE = 'loans' as const;
export const LOANS_COLUMNS = { loan_id: 'loan_id', patron_number: 'patron_number', book_id: 'book_id', reservation_id: 'reservation_id', loaned_on: 'loaned_on', due_date: 'due_date', returned_on: 'returned_on', status: 'status', version: 'version', updated_at: 'updated_at' } as const;

export type NotificationAttemptsRow = {
  notification_id: string;
  attempt_no: number;
  result: 'sent' | 'failed';
  error_message: string | null;
  attempted_at: string;
};
export const NOTIFICATION_ATTEMPTS_TABLE = 'notification_attempts' as const;
export const NOTIFICATION_ATTEMPTS_COLUMNS = { notification_id: 'notification_id', attempt_no: 'attempt_no', result: 'result', error_message: 'error_message', attempted_at: 'attempted_at' } as const;

export type NotificationsRow = {
  notification_id: string;
  patron_number: string;
  email_encrypted: string;
  loan_id: string | null;
  reservation_id: string | null;
  notification_type: 'return_notice' | 'reminder' | 'overdue_notice';
  requested_at: string;
};
export const NOTIFICATIONS_TABLE = 'notifications' as const;
export const NOTIFICATIONS_COLUMNS = { notification_id: 'notification_id', patron_number: 'patron_number', email_encrypted: 'email_encrypted', loan_id: 'loan_id', reservation_id: 'reservation_id', notification_type: 'notification_type', requested_at: 'requested_at' } as const;

export type PatronsRow = {
  patron_number: string;
  idp_subject: string | null;
  name: string;
  email_encrypted: string;
  registered_on: string;
  deleted_on: string | null;
  updated_at: string;
};
export const PATRONS_TABLE = 'patrons' as const;
export const PATRONS_COLUMNS = { patron_number: 'patron_number', idp_subject: 'idp_subject', name: 'name', email_encrypted: 'email_encrypted', registered_on: 'registered_on', deleted_on: 'deleted_on', updated_at: 'updated_at' } as const;

export type ReservationEventsRow = {
  event_id: string;
  reservation_id: string;
  sequence: number;
  event_type: string;
  payload: string;
  actor_subject: string | null;
  occurred_at: string;
};
export const RESERVATION_EVENTS_TABLE = 'reservation_events' as const;
export const RESERVATION_EVENTS_COLUMNS = { event_id: 'event_id', reservation_id: 'reservation_id', sequence: 'sequence', event_type: 'event_type', payload: 'payload', actor_subject: 'actor_subject', occurred_at: 'occurred_at' } as const;

export type ReservationsRow = {
  reservation_id: string;
  patron_number: string;
  book_id: string;
  received_at: string;
  queue_position: number | null;
  status: 'waiting' | 'notified' | 'completed' | 'cancelled';
  notified_at: string | null;
  completed_at: string | null;
  cancelled_at: string | null;
  version: number;
  updated_at: string;
};
export const RESERVATIONS_TABLE = 'reservations' as const;
export const RESERVATIONS_COLUMNS = { reservation_id: 'reservation_id', patron_number: 'patron_number', book_id: 'book_id', received_at: 'received_at', queue_position: 'queue_position', status: 'status', notified_at: 'notified_at', completed_at: 'completed_at', cancelled_at: 'cancelled_at', version: 'version', updated_at: 'updated_at' } as const;
