/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 貸出リクエスト
 * @export
 * @interface CreateLoanRequest
 */
export interface CreateLoanRequest {
    /**
     * 貸出対象の書籍ID
     * @type {string}
     * @memberof CreateLoanRequest
     */
    bookId: string;
}

/**
 * Check if a given object implements the CreateLoanRequest interface.
 */
export function instanceOfCreateLoanRequest(value: object): value is CreateLoanRequest {
    if ((!('bookId' in (value as Record<string, any>)) && !('book_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['bookId'] === undefined && (value as Record<string, any>)['book_id'] === undefined)) return false;
    return true;
}

export function CreateLoanRequestFromJSON(json: any): CreateLoanRequest {
    return CreateLoanRequestFromJSONTyped(json, false);
}

export function CreateLoanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLoanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookId': json['book_id'],
    };
}

export function CreateLoanRequestToJSON(json: any): CreateLoanRequest {
    return CreateLoanRequestToJSONTyped(json, false);
}

export function CreateLoanRequestToJSONTyped(value?: CreateLoanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'book_id': value['bookId'],
    };
}

