/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetectOverdue200Response
 */
export interface DetectOverdue200Response {
    /**
     * 新規延滞検出件数
     * @type {number}
     * @memberof DetectOverdue200Response
     */
    detectedCount: number;
}

/**
 * Check if a given object implements the DetectOverdue200Response interface.
 */
export function instanceOfDetectOverdue200Response(value: object): value is DetectOverdue200Response {
    if ((!('detectedCount' in (value as Record<string, any>)) && !('detected_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['detectedCount'] === undefined && (value as Record<string, any>)['detected_count'] === undefined)) return false;
    return true;
}

export function DetectOverdue200ResponseFromJSON(json: any): DetectOverdue200Response {
    return DetectOverdue200ResponseFromJSONTyped(json, false);
}

export function DetectOverdue200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectOverdue200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'detectedCount': json['detected_count'],
    };
}

export function DetectOverdue200ResponseToJSON(json: any): DetectOverdue200Response {
    return DetectOverdue200ResponseToJSONTyped(json, false);
}

export function DetectOverdue200ResponseToJSONTyped(value?: DetectOverdue200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detected_count': value['detectedCount'],
    };
}

