/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InventoryResponseByGenreInner } from './InventoryResponseByGenreInner';
import {
    InventoryResponseByGenreInnerFromJSON,
    InventoryResponseByGenreInnerFromJSONTyped,
    InventoryResponseByGenreInnerToJSON,
    InventoryResponseByGenreInnerToJSONTyped,
} from './InventoryResponseByGenreInner';

/**
 * 在庫状況レスポンス
 * @export
 * @interface InventoryResponse
 */
export interface InventoryResponse {
    /**
     * 総蔵書数
     * @type {number}
     * @memberof InventoryResponse
     */
    totalBooks: number;
    /**
     * 在庫あり数
     * @type {number}
     * @memberof InventoryResponse
     */
    availableCount: number;
    /**
     * 貸出中数
     * @type {number}
     * @memberof InventoryResponse
     */
    onLoanCount: number;
    /**
     * 延滞中数
     * @type {number}
     * @memberof InventoryResponse
     */
    overdueCount: number;
    /**
     * ジャンル別蔵書数
     * @type {Array<InventoryResponseByGenreInner>}
     * @memberof InventoryResponse
     */
    byGenre: Array<InventoryResponseByGenreInner>;
}

/**
 * Check if a given object implements the InventoryResponse interface.
 */
export function instanceOfInventoryResponse(value: object): value is InventoryResponse {
    if ((!('totalBooks' in (value as Record<string, any>)) && !('total_books' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalBooks'] === undefined && (value as Record<string, any>)['total_books'] === undefined)) return false;
    if ((!('availableCount' in (value as Record<string, any>)) && !('available_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['availableCount'] === undefined && (value as Record<string, any>)['available_count'] === undefined)) return false;
    if ((!('onLoanCount' in (value as Record<string, any>)) && !('on_loan_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['onLoanCount'] === undefined && (value as Record<string, any>)['on_loan_count'] === undefined)) return false;
    if ((!('overdueCount' in (value as Record<string, any>)) && !('overdue_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['overdueCount'] === undefined && (value as Record<string, any>)['overdue_count'] === undefined)) return false;
    if ((!('byGenre' in (value as Record<string, any>)) && !('by_genre' in (value as Record<string, any>))) || ((value as Record<string, any>)['byGenre'] === undefined && (value as Record<string, any>)['by_genre'] === undefined)) return false;
    return true;
}

export function InventoryResponseFromJSON(json: any): InventoryResponse {
    return InventoryResponseFromJSONTyped(json, false);
}

export function InventoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalBooks': json['total_books'],
        'availableCount': json['available_count'],
        'onLoanCount': json['on_loan_count'],
        'overdueCount': json['overdue_count'],
        'byGenre': ((json['by_genre'] as Array<any>).map(InventoryResponseByGenreInnerFromJSON)),
    };
}

export function InventoryResponseToJSON(json: any): InventoryResponse {
    return InventoryResponseToJSONTyped(json, false);
}

export function InventoryResponseToJSONTyped(value?: InventoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_books': value['totalBooks'],
        'available_count': value['availableCount'],
        'on_loan_count': value['onLoanCount'],
        'overdue_count': value['overdueCount'],
        'by_genre': ((value['byGenre'] as Array<any>).map(InventoryResponseByGenreInnerToJSON)),
    };
}

