/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryResponseByGenreInner
 */
export interface InventoryResponseByGenreInner {
    /**
     * ジャンル名
     * @type {string}
     * @memberof InventoryResponseByGenreInner
     */
    genre: string;
    /**
     * 蔵書数
     * @type {number}
     * @memberof InventoryResponseByGenreInner
     */
    count: number;
}

/**
 * Check if a given object implements the InventoryResponseByGenreInner interface.
 */
export function instanceOfInventoryResponseByGenreInner(value: object): value is InventoryResponseByGenreInner {
    if (!('genre' in value) || value['genre'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function InventoryResponseByGenreInnerFromJSON(json: any): InventoryResponseByGenreInner {
    return InventoryResponseByGenreInnerFromJSONTyped(json, false);
}

export function InventoryResponseByGenreInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryResponseByGenreInner {
    if (json == null) {
        return json;
    }
    return {
        
        'genre': json['genre'],
        'count': json['count'],
    };
}

export function InventoryResponseByGenreInnerToJSON(json: any): InventoryResponseByGenreInner {
    return InventoryResponseByGenreInnerToJSONTyped(json, false);
}

export function InventoryResponseByGenreInnerToJSONTyped(value?: InventoryResponseByGenreInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'genre': value['genre'],
        'count': value['count'],
    };
}

