/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 貸出レスポンス
 * @export
 * @interface LoanResponse
 */
export interface LoanResponse {
    /**
     * 貸出ID
     * @type {string}
     * @memberof LoanResponse
     */
    id: string;
    /**
     * 書籍ID
     * @type {string}
     * @memberof LoanResponse
     */
    bookId: string;
    /**
     * 書籍タイトル
     * @type {string}
     * @memberof LoanResponse
     */
    bookTitle: string;
    /**
     * 利用者ID
     * @type {string}
     * @memberof LoanResponse
     */
    userId: string;
    /**
     * 貸出日
     * @type {Date}
     * @memberof LoanResponse
     */
    loanDate: Date;
    /**
     * 返却期限
     * @type {Date}
     * @memberof LoanResponse
     */
    dueDate: Date;
    /**
     * 返却日
     * @type {Date}
     * @memberof LoanResponse
     */
    returnDate?: Date;
    /**
     * 延滞フラグ
     * @type {boolean}
     * @memberof LoanResponse
     */
    isOverdue: boolean;
}

/**
 * Check if a given object implements the LoanResponse interface.
 */
export function instanceOfLoanResponse(value: object): value is LoanResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('bookId' in (value as Record<string, any>)) && !('book_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['bookId'] === undefined && (value as Record<string, any>)['book_id'] === undefined)) return false;
    if ((!('bookTitle' in (value as Record<string, any>)) && !('book_title' in (value as Record<string, any>))) || ((value as Record<string, any>)['bookTitle'] === undefined && (value as Record<string, any>)['book_title'] === undefined)) return false;
    if ((!('userId' in (value as Record<string, any>)) && !('user_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['userId'] === undefined && (value as Record<string, any>)['user_id'] === undefined)) return false;
    if ((!('loanDate' in (value as Record<string, any>)) && !('loan_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['loanDate'] === undefined && (value as Record<string, any>)['loan_date'] === undefined)) return false;
    if ((!('dueDate' in (value as Record<string, any>)) && !('due_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['dueDate'] === undefined && (value as Record<string, any>)['due_date'] === undefined)) return false;
    if ((!('isOverdue' in (value as Record<string, any>)) && !('is_overdue' in (value as Record<string, any>))) || ((value as Record<string, any>)['isOverdue'] === undefined && (value as Record<string, any>)['is_overdue'] === undefined)) return false;
    return true;
}

export function LoanResponseFromJSON(json: any): LoanResponse {
    return LoanResponseFromJSONTyped(json, false);
}

export function LoanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bookId': json['book_id'],
        'bookTitle': json['book_title'],
        'userId': json['user_id'],
        'loanDate': (new Date(json['loan_date'])),
        'dueDate': (new Date(json['due_date'])),
        'returnDate': json['return_date'] == null ? undefined : (new Date(json['return_date'])),
        'isOverdue': json['is_overdue'],
    };
}

export function LoanResponseToJSON(json: any): LoanResponse {
    return LoanResponseToJSONTyped(json, false);
}

export function LoanResponseToJSONTyped(value?: LoanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'book_id': value['bookId'],
        'book_title': value['bookTitle'],
        'user_id': value['userId'],
        'loan_date': value['loanDate'].toISOString().substring(0,10),
        'due_date': value['dueDate'].toISOString().substring(0,10),
        'return_date': value['returnDate'] == null ? value['returnDate'] : value['returnDate'].toISOString().substring(0,10),
        'is_overdue': value['isOverdue'],
    };
}

