/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookResponse } from './BookResponse';
import {
    BookResponseFromJSON,
    BookResponseFromJSONTyped,
    BookResponseToJSON,
    BookResponseToJSONTyped,
} from './BookResponse';

/**
 * ページネーション付き書籍一覧
 * @export
 * @interface PaginatedBookListResponse
 */
export interface PaginatedBookListResponse {
    /**
     * 
     * @type {Array<BookResponse>}
     * @memberof PaginatedBookListResponse
     */
    items: Array<BookResponse>;
    /**
     * 全件数
     * @type {number}
     * @memberof PaginatedBookListResponse
     */
    total: number;
    /**
     * 現在ページ
     * @type {number}
     * @memberof PaginatedBookListResponse
     */
    page: number;
    /**
     * 1ページあたり件数
     * @type {number}
     * @memberof PaginatedBookListResponse
     */
    perPage: number;
}

/**
 * Check if a given object implements the PaginatedBookListResponse interface.
 */
export function instanceOfPaginatedBookListResponse(value: object): value is PaginatedBookListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if ((!('perPage' in (value as Record<string, any>)) && !('per_page' in (value as Record<string, any>))) || ((value as Record<string, any>)['perPage'] === undefined && (value as Record<string, any>)['per_page'] === undefined)) return false;
    return true;
}

export function PaginatedBookListResponseFromJSON(json: any): PaginatedBookListResponse {
    return PaginatedBookListResponseFromJSONTyped(json, false);
}

export function PaginatedBookListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBookListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(BookResponseFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'perPage': json['per_page'],
    };
}

export function PaginatedBookListResponseToJSON(json: any): PaginatedBookListResponse {
    return PaginatedBookListResponseToJSONTyped(json, false);
}

export function PaginatedBookListResponseToJSONTyped(value?: PaginatedBookListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(BookResponseToJSON)),
        'total': value['total'],
        'page': value['page'],
        'per_page': value['perPage'],
    };
}

