/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 予約レスポンス
 * @export
 * @interface ReservationResponse
 */
export interface ReservationResponse {
    /**
     * 予約ID
     * @type {string}
     * @memberof ReservationResponse
     */
    id: string;
    /**
     * 書籍ID
     * @type {string}
     * @memberof ReservationResponse
     */
    bookId: string;
    /**
     * 書籍タイトル
     * @type {string}
     * @memberof ReservationResponse
     */
    bookTitle: string;
    /**
     * 利用者ID
     * @type {string}
     * @memberof ReservationResponse
     */
    userId: string;
    /**
     * 予約日時
     * @type {Date}
     * @memberof ReservationResponse
     */
    reservedAt: Date;
    /**
     * 予約順位
     * @type {number}
     * @memberof ReservationResponse
     */
    queuePosition: number;
    /**
     * 予約状態
     * @type {ReservationResponseStatusEnum}
     * @memberof ReservationResponse
     */
    status: ReservationResponseStatusEnum;
}


/**
 * @export
 */
export const ReservationResponseStatusEnum = {
    Pending: 'pending',
    Reserved: 'reserved',
    Cancelled: 'cancelled'
} as const;
export type ReservationResponseStatusEnum = typeof ReservationResponseStatusEnum[keyof typeof ReservationResponseStatusEnum];


/**
 * Check if a given object implements the ReservationResponse interface.
 */
export function instanceOfReservationResponse(value: object): value is ReservationResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('bookId' in (value as Record<string, any>)) && !('book_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['bookId'] === undefined && (value as Record<string, any>)['book_id'] === undefined)) return false;
    if ((!('bookTitle' in (value as Record<string, any>)) && !('book_title' in (value as Record<string, any>))) || ((value as Record<string, any>)['bookTitle'] === undefined && (value as Record<string, any>)['book_title'] === undefined)) return false;
    if ((!('userId' in (value as Record<string, any>)) && !('user_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['userId'] === undefined && (value as Record<string, any>)['user_id'] === undefined)) return false;
    if ((!('reservedAt' in (value as Record<string, any>)) && !('reserved_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['reservedAt'] === undefined && (value as Record<string, any>)['reserved_at'] === undefined)) return false;
    if ((!('queuePosition' in (value as Record<string, any>)) && !('queue_position' in (value as Record<string, any>))) || ((value as Record<string, any>)['queuePosition'] === undefined && (value as Record<string, any>)['queue_position'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ReservationResponseFromJSON(json: any): ReservationResponse {
    return ReservationResponseFromJSONTyped(json, false);
}

export function ReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bookId': json['book_id'],
        'bookTitle': json['book_title'],
        'userId': json['user_id'],
        'reservedAt': (new Date(json['reserved_at'])),
        'queuePosition': json['queue_position'],
        'status': json['status'],
    };
}

export function ReservationResponseToJSON(json: any): ReservationResponse {
    return ReservationResponseToJSONTyped(json, false);
}

export function ReservationResponseToJSONTyped(value?: ReservationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'book_id': value['bookId'],
        'book_title': value['bookTitle'],
        'user_id': value['userId'],
        'reserved_at': value['reservedAt'].toISOString(),
        'queue_position': value['queuePosition'],
        'status': value['status'],
    };
}

