/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 返却レスポンス
 * @export
 * @interface ReturnLoanResponse
 */
export interface ReturnLoanResponse {
    /**
     * 貸出ID
     * @type {string}
     * @memberof ReturnLoanResponse
     */
    id: string;
    /**
     * 書籍タイトル
     * @type {string}
     * @memberof ReturnLoanResponse
     */
    bookTitle: string;
    /**
     * 返却日
     * @type {Date}
     * @memberof ReturnLoanResponse
     */
    returnDate: Date;
}

/**
 * Check if a given object implements the ReturnLoanResponse interface.
 */
export function instanceOfReturnLoanResponse(value: object): value is ReturnLoanResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('bookTitle' in (value as Record<string, any>)) && !('book_title' in (value as Record<string, any>))) || ((value as Record<string, any>)['bookTitle'] === undefined && (value as Record<string, any>)['book_title'] === undefined)) return false;
    if ((!('returnDate' in (value as Record<string, any>)) && !('return_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['returnDate'] === undefined && (value as Record<string, any>)['return_date'] === undefined)) return false;
    return true;
}

export function ReturnLoanResponseFromJSON(json: any): ReturnLoanResponse {
    return ReturnLoanResponseFromJSONTyped(json, false);
}

export function ReturnLoanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnLoanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bookTitle': json['book_title'],
        'returnDate': (new Date(json['return_date'])),
    };
}

export function ReturnLoanResponseToJSON(json: any): ReturnLoanResponse {
    return ReturnLoanResponseToJSONTyped(json, false);
}

export function ReturnLoanResponseToJSONTyped(value?: ReturnLoanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'book_title': value['bookTitle'],
        'return_date': value['returnDate'].toISOString().substring(0,10),
    };
}

