/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendOverdueNotificationRequest
 */
export interface SendOverdueNotificationRequest {
    /**
     * 督促対象の貸出ID一覧
     * @type {Array<string>}
     * @memberof SendOverdueNotificationRequest
     */
    loanIds: Array<string>;
}

/**
 * Check if a given object implements the SendOverdueNotificationRequest interface.
 */
export function instanceOfSendOverdueNotificationRequest(value: object): value is SendOverdueNotificationRequest {
    if ((!('loanIds' in (value as Record<string, any>)) && !('loan_ids' in (value as Record<string, any>))) || ((value as Record<string, any>)['loanIds'] === undefined && (value as Record<string, any>)['loan_ids'] === undefined)) return false;
    return true;
}

export function SendOverdueNotificationRequestFromJSON(json: any): SendOverdueNotificationRequest {
    return SendOverdueNotificationRequestFromJSONTyped(json, false);
}

export function SendOverdueNotificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendOverdueNotificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'loanIds': json['loan_ids'],
    };
}

export function SendOverdueNotificationRequestToJSON(json: any): SendOverdueNotificationRequest {
    return SendOverdueNotificationRequestToJSONTyped(json, false);
}

export function SendOverdueNotificationRequestToJSONTyped(value?: SendOverdueNotificationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'loan_ids': value['loanIds'],
    };
}

