/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatsResponseMonthlyTrendInner
 */
export interface StatsResponseMonthlyTrendInner {
    /**
     * 年月（YYYY-MM）
     * @type {string}
     * @memberof StatsResponseMonthlyTrendInner
     */
    month: string;
    /**
     * 貸出件数
     * @type {number}
     * @memberof StatsResponseMonthlyTrendInner
     */
    count: number;
}

/**
 * Check if a given object implements the StatsResponseMonthlyTrendInner interface.
 */
export function instanceOfStatsResponseMonthlyTrendInner(value: object): value is StatsResponseMonthlyTrendInner {
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function StatsResponseMonthlyTrendInnerFromJSON(json: any): StatsResponseMonthlyTrendInner {
    return StatsResponseMonthlyTrendInnerFromJSONTyped(json, false);
}

export function StatsResponseMonthlyTrendInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsResponseMonthlyTrendInner {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'],
        'count': json['count'],
    };
}

export function StatsResponseMonthlyTrendInnerToJSON(json: any): StatsResponseMonthlyTrendInner {
    return StatsResponseMonthlyTrendInnerToJSONTyped(json, false);
}

export function StatsResponseMonthlyTrendInnerToJSONTyped(value?: StatsResponseMonthlyTrendInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'month': value['month'],
        'count': value['count'],
    };
}

