/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 利用者レスポンス
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 利用者ID
     * @type {string}
     * @memberof UserResponse
     */
    id: string;
    /**
     * 利用者番号
     * @type {string}
     * @memberof UserResponse
     */
    userNumber: string;
    /**
     * 氏名
     * @type {string}
     * @memberof UserResponse
     */
    name: string;
    /**
     * 連絡先
     * @type {string}
     * @memberof UserResponse
     */
    contact?: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof UserResponse
     */
    email: string;
    /**
     * 利用者種別
     * @type {string}
     * @memberof UserResponse
     */
    userType: string;
    /**
     * 登録日
     * @type {Date}
     * @memberof UserResponse
     */
    registeredAt: Date;
}

/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): value is UserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('userNumber' in (value as Record<string, any>)) && !('user_number' in (value as Record<string, any>))) || ((value as Record<string, any>)['userNumber'] === undefined && (value as Record<string, any>)['user_number'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if ((!('userType' in (value as Record<string, any>)) && !('user_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['userType'] === undefined && (value as Record<string, any>)['user_type'] === undefined)) return false;
    if ((!('registeredAt' in (value as Record<string, any>)) && !('registered_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['registeredAt'] === undefined && (value as Record<string, any>)['registered_at'] === undefined)) return false;
    return true;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userNumber': json['user_number'],
        'name': json['name'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'email': json['email'],
        'userType': json['user_type'],
        'registeredAt': (new Date(json['registered_at'])),
    };
}

export function UserResponseToJSON(json: any): UserResponse {
    return UserResponseToJSONTyped(json, false);
}

export function UserResponseToJSONTyped(value?: UserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_number': value['userNumber'],
        'name': value['name'],
        'contact': value['contact'],
        'email': value['email'],
        'user_type': value['userType'],
        'registered_at': value['registeredAt'].toISOString().substring(0,10),
    };
}

