"""mid-harness scripts の共通処理 (manifest 読込、パス解決、版取得、検証)."""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = SKILL_DIR / "templates"
MANIFEST_REL = Path(".agents/harness.yaml")
GENERATED_MARKER = ".mid-harness-generated"
GENERATED_LINE = "generated by mid-harness"  # 生成した agent 定義に埋める所有マーカー (行頭固定で判定する)
OWNER_TAG = "# mid-harness"                  # hook handler の所有 ID (command の末尾に完全一致)


def owned_agent_file(text: str, fmt: str) -> bool:
    """所有マーカーが「その形式の所定位置の完全な行」にあるときだけ True。
    fmt="md"   (Claude): 先頭の front matter (--- ... ---) の直後の行が `<!-- generated by mid-harness from ...; do not edit -->`
    fmt="toml" (Codex):  先頭行が `# generated by mid-harness from ...; do not edit`
    形式が違うマーカーは所有と見なさない (front matter 無しの md の先頭が `# generated …` でも手書き扱い)."""
    lines = text.splitlines()
    if not lines:
        return False
    if fmt == "toml":
        return lines[0].startswith(f"# {GENERATED_LINE} from ") and lines[0].endswith("; do not edit")
    if fmt == "md":
        if lines[0].strip() != "---":
            return False
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                nxt = lines[i + 1] if i + 1 < len(lines) else ""
                return nxt.startswith(f"<!-- {GENERATED_LINE} from ") and nxt.endswith("; do not edit -->")
        return False
    raise ValueError(f"unknown fmt: {fmt}")


def owned_hook_command(cmd) -> bool:
    return isinstance(cmd, str) and cmd.rstrip().endswith("  " + OWNER_TAG)


def manifest_lists(m: dict) -> tuple[list, list]:
    hooks = m.get("hooks", [])
    agents = m.get("agents", [])
    return (hooks if isinstance(hooks, list) else []), (agents if isinstance(agents, list) else [])
HOOK_SCRIPT_DIR = "scripts/agent-hooks"
SUPPORTED_TARGETS = ("claude-code", "codex")
LOGICAL_EVENTS = ("pre-tool", "post-tool", "session-start", "stop")
CAPABILITIES = ("read", "edit", "shell", "delegate", "network")
NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$")


def die(msg: str, code: int = 1):
    print(f"mid-harness: {msg}", file=sys.stderr)
    sys.exit(code)


def load_yaml_module():
    try:
        import yaml  # type: ignore
    except ImportError:
        die("PyYAML が必要です: pip install pyyaml", 1)
    return yaml


def skill_version() -> str:
    """plugin.json (正本) から版を読む。無ければ 'dev'."""
    for parent in SKILL_DIR.parents:
        pj = parent / ".claude-plugin" / "plugin.json"
        if pj.exists():
            try:
                return str(json.loads(pj.read_text()).get("version", "dev"))
            except Exception:
                return "dev"
    return "dev"


def resolve_repo(arg: str | None) -> Path:
    start = Path(arg).resolve() if arg else Path.cwd()
    try:
        out = subprocess.run(
            ["git", "-C", str(start), "rev-parse", "--show-toplevel"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
    except subprocess.CalledProcessError:
        die(f"{start} は git リポジトリではありません", 1)
    return Path(out)


def safe_rel_path(repo: Path, rel: str, allowed_root: str) -> Path | None:
    """rel が repo/allowed_root 配下の通常ファイル (symlink でない) を指すなら Path、そうでなければ None."""
    if not isinstance(rel, str) or not rel or rel.startswith(("/", "~")) or "\\" in rel:
        return None
    p = repo / rel
    try:
        p.resolve().relative_to((repo / allowed_root).resolve())
    except ValueError:
        return None
    if ".." in Path(rel).parts:
        return None
    return p


def load_manifest(repo: Path) -> dict:
    yaml = load_yaml_module()
    path = repo / MANIFEST_REL
    if not path.exists():
        die(f"manifest がありません: {path} (init を先に実行)", 1)
    data = yaml.safe_load(path.read_text())
    errors = validate_manifest(data, repo)
    if errors:
        die("manifest が不正です:\n  - " + "\n  - ".join(errors), 1)
    return data


def validate_manifest(m, repo: Path | None = None) -> list[str]:
    errs: list[str] = []
    if not isinstance(m, dict):
        return ["manifest の top-level は map"]
    targets = m.get("targets")
    if not isinstance(targets, list) or not targets or not all(isinstance(t, str) for t in targets):
        errs.append("targets は 1 つ以上の文字列リスト")
    else:
        for t in targets:
            if t not in SUPPORTED_TARGETS:
                errs.append(f"unsupported target: {t} (対応: {', '.join(SUPPORTED_TARGETS)})")
    if m.get("skills_mode", "generate") not in ("generate", "symlink", "manual"):
        errs.append("skills_mode は generate | symlink | manual")
    hooks = m.get("hooks", [])
    if hooks is None:
        hooks = []
    if not isinstance(hooks, list):
        errs.append(f"hooks はリスト (got {type(hooks).__name__})")
        hooks = []
    for i, h in enumerate(hooks):
        if not isinstance(h, dict):
            errs.append(f"hooks[{i}] は map")
            continue
        if h.get("event") not in LOGICAL_EVENTS:
            errs.append(f"hooks[{i}].event は {LOGICAL_EVENTS} のいずれか")
        script = h.get("script")
        if not isinstance(script, str) or not script.startswith(HOOK_SCRIPT_DIR + "/") \
                or (repo is not None and safe_rel_path(repo, script, HOOK_SCRIPT_DIR) is None):
            errs.append(f"hooks[{i}].script は {HOOK_SCRIPT_DIR}/ 配下の相対パス ('..' や symlink 越え不可): {script!r}")
        if "matcher" in h and h["matcher"] is not None and not isinstance(h["matcher"], str):
            errs.append(f"hooks[{i}].matcher は文字列")
        if h.get("on_unmappable", "fail") not in ("fail", "skip"):
            errs.append(f"hooks[{i}].on_unmappable は fail | skip")
    agents = m.get("agents", [])
    if agents is None:
        agents = []
    if not isinstance(agents, list):
        errs.append(f"agents はリスト (got {type(agents).__name__})")
        agents = []
    for a in agents:
        if not isinstance(a, str) or not NAME_RE.match(a):
            errs.append(f"agents の要素は名前のみ ([A-Za-z0-9][A-Za-z0-9_-]*): {a!r}")
    return errs


def load_policy(repo: Path, agent: str) -> tuple[str, dict]:
    yaml = load_yaml_module()
    if not NAME_RE.match(agent):
        die(f"agent 名が不正です: {agent!r}", 1)
    spec_dir = repo / ".agents" / "agent-specs" / agent
    prompt = spec_dir / "prompt.md"
    policy = spec_dir / "policy.yaml"
    if not prompt.is_file() or not policy.is_file():
        die(f"agent-spec が不完全です: {spec_dir} (prompt.md と policy.yaml が必要)", 1)
    p = yaml.safe_load(policy.read_text())
    if not isinstance(p, dict):
        die(f"{policy}: top-level は map", 1)
    if not isinstance(p.get("description"), str) or not p["description"].strip():
        die(f"{policy}: description (文字列) は必須", 1)
    if any(ch in p["description"] for ch in "\r\n"):
        die(f"{policy}: description に改行は使えません", 1)
    caps = p.get("capabilities")
    if caps is None:
        caps = {}
    if not isinstance(caps, dict):
        die(f"{policy}: capabilities は map", 1)
    for k in CAPABILITIES:
        v = caps.get(k, False)
        if not isinstance(v, bool):
            die(f"{policy}: capabilities.{k} は true | false", 1)
        caps[k] = v
    unknown = set(caps) - set(CAPABILITIES)
    if unknown:
        die(f"{policy}: 未知の capability: {sorted(unknown)}", 1)
    p["capabilities"] = caps
    if p.get("on_unmappable", "fail") not in ("fail", "skip"):
        die(f"{policy}: on_unmappable は fail | skip", 1)
    p.setdefault("on_unmappable", "fail")
    docs = p.get("docs") or []
    if not isinstance(docs, list) or not all(isinstance(d, str) and d and not d.startswith(("/", "~")) and ".." not in Path(d).parts for d in docs):
        die(f"{policy}: docs は repo root 基準の相対パスのリスト", 1)
    p["docs"] = docs
    model = p.get("model")
    if model is not None and (not isinstance(model, str) or not re.match(r"^[A-Za-z0-9._:-]+$", model)):
        die(f"{policy}: model は null か英数字の識別子", 1)
    return prompt.read_text(), p
