#!/usr/bin/env bash
# test_scripts.sh — scripts の回帰テスト (LLM 不要、一時 git リポで scaffold → gen → drift → verify skip を通す)。usage: test_scripts.sh
set -u
S="$(cd "$(dirname "$0")" && pwd)"
T="$(mktemp -d "${TMPDIR:-/tmp}/mid-harness-selftest.XXXXXX")"; trap 'rm -rf "$T"' EXIT
fail=0
ok() { echo "pass  $1"; }
ng() { echo "FAIL  $1"; fail=1; }

git -C "$T" init -q; git -C "$T" config user.email t@t; git -C "$T" config user.name t
python3 $S/scaffold.py "$T" >/dev/null && ok "scaffold" || ng "scaffold"
python3 $S/scaffold.py "$T" | grep -q "created (0)" && ok "scaffold idempotent" || ng "scaffold idempotent"

# 既存 hooks.json に他人の handler を同居させておく
mkdir -p "$T/.codex"
printf '{"hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"echo audit"}]}]},"other":1}\n' > "$T/.codex/hooks.json"
mkdir -p "$T/.claude"; printf '{"permissions":{"allow":["Bash(ls:*)"]}}\n' > "$T/.claude/settings.json"

python3 $S/gen_adapters.py "$T" --quiet && ok "gen" || ng "gen"
grep -q '"echo audit"' "$T/.codex/hooks.json" && ok "foreign handler kept" || ng "foreign handler kept"
grep -q '"other": 1' "$T/.codex/hooks.json" && ok "foreign key kept" || ng "foreign key kept"
grep -q 'Bash(ls' "$T/.claude/settings.json" && ok "permissions kept" || ng "permissions kept"
grep -q 'git rev-parse --show-toplevel' "$T/.codex/hooks.json" && ok "codex cmd resolves root" || ng "codex cmd resolves root"
grep -q 'generated by mid-harness' "$T/.claude/agents/reviewer.md" && ok "agent marker" || ng "agent marker"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen idempotent" || ng "gen idempotent"
grep -c '"echo audit"' "$T/.codex/hooks.json" | grep -q '^1$' && ok "no duplicate on regen" || ng "no duplicate on regen"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after gen" || ng "no drift after gen"

# 手書き agent 定義の保護
printf -- '---\nname: hand\ndescription: x\n---\nhand written\n' > "$T/.claude/agents/hand.md"
cp -R "$T/.agents/agent-specs/reviewer" "$T/.agents/agent-specs/hand"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\nagents: [reviewer, hand]\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>/dev/null; then ng "handwritten agent protected"; else ok "handwritten agent protected"; fi
grep -q 'hand written' "$T/.claude/agents/hand.md" && ok "handwritten untouched (atomic)" || ng "handwritten untouched (atomic)"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "adopt" || ng "adopt"

# TOML: backslash と """ を含む prompt
printf 'skill_version: "t"\ntargets: [codex]\nskills_mode: manual\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
printf 'Use C:\\new\\queue and literal """ here.\nline2 ends with quote "\n' > "$T/.agents/agent-specs/reviewer/prompt.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "gen with backslash prompt" || ng "gen with backslash prompt"
python3 -c "import importlib,importlib.util;tomllib=importlib.import_module('tomllib') if importlib.util.find_spec('tomllib') else importlib.import_module('tomli');d=tomllib.load(open('$T/.codex/agents/reviewer.toml','rb'));assert 'C:\\\\new\\\\queue' in d['developer_instructions'] and '\"\"\"' in d['developer_instructions']" && ok "toml roundtrip" || ng "toml roundtrip"

# drift: generated skill dir に余剰ファイル
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: generate\nagents: []\n' > "$T/.agents/harness.yaml"
mkdir -p "$T/.agents/skills/demo"; printf -- '---\nname: demo\ndescription: d\n---\nx\n' > "$T/.agents/skills/demo/SKILL.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "gen skills" || ng "gen skills"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift (skills)" || ng "no drift (skills)"
touch "$T/.claude/skills/demo/stale.txt"
if python3 $S/check_drift.py "$T" | grep -q "extra file"; then ok "drift detects extra file"; else ng "drift detects extra file"; fi
rm "$T/.claude/skills/demo/stale.txt"; rm "$T/.claude/skills/demo/.mid-harness-generated"
if python3 $S/check_drift.py "$T" >/dev/null 2>&1; then ng "drift detects marker loss"; else ok "drift detects marker loss (gen refuses unmarked dir)"; fi
rm -rf "$T/.claude/skills/demo"   # マーカーを消した生成物を片付けて以降のテストに影響させない

# manifest validation
printf 'targets: [claude-code]\nhooks:\n  - event: pre-tool\n    script: scripts/agent-hooks/../../x.sh\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "symlink 越え不可"; then ok "reject path escape"; else ng "reject path escape"; fi
printf 'targets: [claude-code]\nagents: ["../x"]\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "名前のみ"; then ok "reject bad agent name"; else ng "reject bad agent name"; fi

# round2: orphan agent removal + empty codex block
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
printf 'Review carefully.\n' > "$T/.agents/agent-specs/reviewer/prompt.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt || ng "gen reviewer"
printf -- '---\nname: keepme\ndescription: x\n---\nhand written keepme\n' > "$T/.claude/agents/keepme.md"
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\nagents: []\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen with agents removed" || ng "gen with agents removed"
[ ! -e "$T/.claude/agents/reviewer.md" ] && [ ! -e "$T/.codex/agents/reviewer.toml" ] && ok "orphan agents removed" || ng "orphan agents removed"
grep -q "mid-harness:begin" "$T/.codex/config.toml" && ng "empty codex block removed" || ok "empty codex block removed"
grep -q 'hand written keepme' "$T/.claude/agents/keepme.md" 2>/dev/null && ok "handwritten agent not removed" || ng "handwritten agent not removed"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after orphan removal" || ng "no drift after orphan removal"
# round2: exact owner tag (foreign handler that merely mentions the tag must survive)
printf 'skill_version: "t"\ntargets: [codex]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    matcher: Bash\n    script: scripts/agent-hooks/pre-tool-policy.sh\n' > "$T/.agents/harness.yaml"
printf '{"hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"printf %%s # mid-harness release note"},{"type":"command","command":"bash scripts/agent-hooks/team-owned.sh"}]}]}}\n' > "$T/.codex/hooks.json"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen exact tag" || ng "gen exact tag"
grep -q "release note" "$T/.codex/hooks.json" && grep -q "team-owned.sh" "$T/.codex/hooks.json" && ok "foreign handlers with lookalike text kept" || ng "foreign handlers with lookalike text kept"
# round2: agent marker must be at fixed position
printf -- '---\nname: hand2\ndescription: x\n---\nNotes about text generated by mid-harness from somewhere; do not edit\n' > "$T/.claude/agents/hand2.md"
cp -R "$T/.agents/agent-specs/reviewer" "$T/.agents/agent-specs/hand2"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\nagents: [hand2]\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>/dev/null; then ng "lookalike marker not treated as owned"; else ok "lookalike marker not treated as owned"; fi
# round2: control chars in prompt
printf 'skill_version: "t"\ntargets: [codex]\nskills_mode: manual\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
printf 'has NUL \000 and CR \r here\n' > "$T/.agents/agent-specs/reviewer/prompt.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "gen with control chars" || ng "gen with control chars"
# CR は Python の text mode (universal newlines) で LF に正規化される。NUL が round-trip すれば十分
python3 -c "import importlib,importlib.util;tomllib=importlib.import_module('tomllib') if importlib.util.find_spec('tomllib') else importlib.import_module('tomli');d=tomllib.load(open('$T/.codex/agents/reviewer.toml','rb'));assert '\x00' in d['developer_instructions'], d" && ok "control chars roundtrip" || ng "control chars roundtrip"
# round2: falsy manifest values rejected
printf 'targets: [codex]\nhooks: false\nagents: 0\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "はリスト"; then ok "falsy hooks/agents rejected"; else ng "falsy hooks/agents rejected"; fi
# round2: symlink inside core skill rejected
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: generate\n' > "$T/.agents/harness.yaml"
ln -s /etc/hosts "$T/.agents/skills/demo/outside.txt"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "symlink"; then ok "symlink in skill rejected"; else ng "symlink in skill rejected"; fi
rm "$T/.agents/skills/demo/outside.txt"
# round2: exec bit drift
mkdir -p "$T/.agents/skills/demo/scripts"; printf '#!/bin/sh\necho hi\n' > "$T/.agents/skills/demo/scripts/run.sh"; chmod 755 "$T/.agents/skills/demo/scripts/run.sh"
python3 $S/gen_adapters.py "$T" --quiet && python3 $S/check_drift.py "$T" >/dev/null && ok "no drift with exec script" || ng "no drift with exec script"
chmod 644 "$T/.claude/skills/demo/scripts/run.sh"
if python3 $S/check_drift.py "$T" | grep -q "exec bit differs"; then ok "drift detects exec bit"; else ng "drift detects exec bit"; fi
chmod 755 "$T/.claude/skills/demo/scripts/run.sh"
# round2: verify leaves no empty parent dir
rm -rf "$T/.claude/skills"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\n' > "$T/.agents/harness.yaml"
mkdir -p "$T/fakebin"; printf '#!/bin/sh\necho MID_HARNESS_PROBE_OK\n' > "$T/fakebin/claude"; chmod +x "$T/fakebin/claude"
[ ! -e "$T/.claude/skills" ] && ok "precondition: no .claude/skills" || ng "precondition"
PATH="$T/fakebin:$PATH" MID_HARNESS_VERIFY_TIMEOUT=20 bash $S/verify.sh "$T" >/dev/null 2>&1   # fake CLI: hook テストは fail するが cleanup を見る
[ ! -e "$T/.claude/skills" ] && ok "no empty parent left after probe cleanup" || ng "no empty parent left after probe cleanup"
ls "$T/.agents/skills" | grep -q probe && ng "probe cleaned (fake cli)" || ok "probe cleaned (fake cli)"

# round3: front matter 無しの md の先頭 "# generated by mid-harness from" は手書き扱い (削除しない)
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\nagents: []\n' > "$T/.agents/harness.yaml"
printf '# generated by mid-harness from a design note; this is handwritten prose\nbody\n' > "$T/.claude/agents/prose.md"
printf -- '---\nname: x\n---\ntext\n---\n<!-- generated by mid-harness from x; do not edit -->\n' > "$T/.claude/agents/lateMarker.md"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen (frontmatterless case)" || ng "gen (frontmatterless case)"
[ -e "$T/.claude/agents/prose.md" ] && ok "frontmatterless md not treated as owned" || ng "frontmatterless md not treated as owned"
[ -e "$T/.claude/agents/lateMarker.md" ] && ok "marker after second --- not treated as owned" || ng "marker after second --- not treated as owned"
# round3: 生成先が symlink なら失敗し、外部ファイルを書き換えない
OUTSIDE="$(mktemp)"; printf '{"sentinel":"outside"}\n' > "$OUTSIDE"
mv "$T/.claude/settings.json" "$T/.claude/settings.json.bak"; ln -s "$OUTSIDE" "$T/.claude/settings.json"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "symlink"; then ok "symlink target rejected"; else ng "symlink target rejected"; fi
grep -q '"sentinel":"outside"' "$OUTSIDE" && ok "outside file untouched" || ng "outside file untouched"
rm "$T/.claude/settings.json"; mv "$T/.claude/settings.json.bak" "$T/.claude/settings.json"; rm -f "$OUTSIDE"
# round3: codex を targets から外すと agent toml と管理ブロックが消え、hooks.json の所有 handler は残る
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    matcher: Bash\n    script: scripts/agent-hooks/pre-tool-policy.sh\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
printf 'Review.\n' > "$T/.agents/agent-specs/reviewer/prompt.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt || ng "gen both targets"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    matcher: Bash\n    script: scripts/agent-hooks/pre-tool-policy.sh\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen after dropping codex" || ng "gen after dropping codex"
[ ! -e "$T/.codex/agents/reviewer.toml" ] && ok "codex agent removed on target drop" || ng "codex agent removed on target drop"
grep -q "mid-harness:begin" "$T/.codex/config.toml" && ng "codex block removed on target drop" || ok "codex block removed on target drop"
grep -q "# mid-harness" "$T/.codex/hooks.json" && ok "codex hook handler kept on target drop (documented asymmetry)" || ng "codex hook handler kept on target drop"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after target drop" || ng "no drift after target drop"
# round3: core から skill を消すと生成 skill ディレクトリも消える
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: generate\nagents: []\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet || ng "gen skills 2"
[ -d "$T/.claude/skills/demo" ] && ok "generated skill present" || ng "generated skill present"
rm -rf "$T/.agents/skills/demo"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen after core skill removal" || ng "gen after core skill removal"
[ ! -e "$T/.claude/skills/demo" ] && ok "orphan generated skill removed" || ng "orphan generated skill removed"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after skill removal" || ng "no drift after skill removal"

# 6 製品: 全 targets で生成 → drift ゼロ → 製品を外すと所有生成物だけ消える
printf 'skill_version: "t"\ntargets: [claude-code, codex, cursor, grok, copilot, antigravity]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    matcher: Bash\n    script: scripts/agent-hooks/pre-tool-policy.sh\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
printf 'Review.\n' > "$T/.agents/agent-specs/reviewer/prompt.md"
printf '{"other-hook":{"Stop":[{"hooks":[{"type":"command","command":"echo bye"}]}]}}\n' > "$T/.agents/hooks.json"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "gen 6 targets" || ng "gen 6 targets"
for f in .cursor/hooks.json .cursor/agents/reviewer.md .grok/hooks/mid-harness.json .grok/agents/reviewer.md .github/hooks/mid-harness.json .github/agents/reviewer.md .agents/hooks.json .agents/agents/reviewer/agent.md; do
  [ -f "$T/$f" ] && ok "generated $f" || ng "generated $f"
done
grep -q '"other-hook"' "$T/.agents/hooks.json" && grep -q '"mid-harness"' "$T/.agents/hooks.json" && ok "antigravity: foreign named hook kept" || ng "antigravity: foreign named hook kept"
grep -q 'beforeShellExecution' "$T/.cursor/hooks.json" && grep -q '"failClosed": true' "$T/.cursor/hooks.json" && ok "cursor: event + failClosed" || ng "cursor: event + failClosed"
grep -q 'readonly: true' "$T/.cursor/agents/reviewer.md" && ok "cursor: readonly agent" || ng "cursor: readonly agent"
grep -q 'permissionMode: plan' "$T/.grok/agents/reviewer.md" && ok "grok: permissionMode plan" || ng "grok: permissionMode plan"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift (6 targets)" || ng "no drift (6 targets)"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    matcher: Bash\n    script: scripts/agent-hooks/pre-tool-policy.sh\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen after dropping 5 targets" || ng "gen after dropping 5 targets"
for f in .cursor/agents/reviewer.md .grok/hooks/mid-harness.json .grok/agents/reviewer.md .github/hooks/mid-harness.json .github/agents/reviewer.md .agents/agents/reviewer/agent.md; do
  [ ! -e "$T/$f" ] && ok "removed $f" || ng "removed $f"
done
grep -q 'other-hook' "$T/.agents/hooks.json" && ok "antigravity: foreign hook kept after drop" || ng "antigravity: foreign hook kept after drop"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after dropping 5 targets" || ng "no drift after dropping 5 targets"
# copilot: tools alias と matcher
printf 'skill_version: "t"\ntargets: [copilot]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    matcher: Bash\n    script: scripts/agent-hooks/pre-tool-policy.sh\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "gen copilot" || ng "gen copilot"
grep -q 'tools: \[read, search\]' "$T/.github/agents/reviewer.md" && ok "copilot: tools alias from policy" || ng "copilot: tools alias from policy"
grep -q '"matcher": "bash|powershell"' "$T/.github/hooks/mid-harness.json" && ok "copilot: matcher Bash -> bash|powershell" || ng "copilot: matcher"
# copilot / grok: 全 true → tools 省略、全 false → tools: []、model 指定
mkdir -p "$T/.agents/agent-specs/allt" "$T/.agents/agent-specs/nonet" "$T/.agents/agent-specs/modl"
printf 'p\n' | tee "$T/.agents/agent-specs/allt/prompt.md" "$T/.agents/agent-specs/nonet/prompt.md" "$T/.agents/agent-specs/modl/prompt.md" >/dev/null
printf 'description: d\ncapabilities: {read: true, edit: true, shell: true, delegate: true, network: true}\n' > "$T/.agents/agent-specs/allt/policy.yaml"
printf 'description: d\ncapabilities: {read: false, edit: false, shell: false, delegate: false, network: false}\non_unmappable: skip\n' > "$T/.agents/agent-specs/nonet/policy.yaml"
printf 'description: d\nmodel: gpt-5.6\ncapabilities: {read: true, edit: true, shell: true, delegate: true, network: true}\n' > "$T/.agents/agent-specs/modl/policy.yaml"
printf 'skill_version: "t"\ntargets: [copilot, grok]\nskills_mode: manual\nagents: [allt, nonet, modl]\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "gen tools edge cases" || ng "gen tools edge cases"
grep -q '^tools:' "$T/.github/agents/allt.md" && ng "copilot: all true omits tools" || ok "copilot: all true omits tools"
grep -q '^tools: \[\]$' "$T/.github/agents/nonet.md" && ok "copilot: all false -> tools: []" || ng "copilot: all false -> tools: []"
grep -q '^model: gpt-5.6$' "$T/.github/agents/modl.md" && ok "copilot: model emitted" || ng "copilot: model emitted"
grep -q '^tools:' "$T/.grok/agents/allt.md" && ng "grok: all true omits tools" || ok "grok: all true omits tools"
grep -q '^tools: \[\]$' "$T/.grok/agents/nonet.md" && ok "grok: all false -> tools: []" || ng "grok: all false -> tools: []"
python3 -c "import yaml,sys;t=open('$T/.grok/agents/nonet.md').read().split('---')[1];assert yaml.safe_load(t)['tools']==[]" && ok "grok: tools: [] parses as empty list" || ng "grok: tools: [] parses as empty list"
# targets から外したのに所有 hook ファイル / キーが残っていたら drift として検出
printf 'skill_version: "t"\ntargets: [copilot, grok, antigravity]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    script: scripts/agent-hooks/pre-tool-policy.sh\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet --adopt || ng "gen 3 targets for drift test"
printf 'skill_version: "t"\ntargets: [cursor]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    script: scripts/agent-hooks/pre-tool-policy.sh\n' > "$T/.agents/harness.yaml"
out="$(python3 $S/check_drift.py "$T" 2>&1)"
printf '%s' "$out" | grep -q "orphan generated hook file: .grok" && printf '%s' "$out" | grep -q "orphan generated hook file: .github" && printf '%s' "$out" | grep -q "orphan generated hook key" && ok "drift detects leftover owned hook files/keys after target drop" || ng "drift detects leftover owned hook files/keys after target drop"
python3 $S/gen_adapters.py "$T" --quiet && python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after regenerating with dropped targets" || ng "no drift after regenerating with dropped targets"
# antigravity が targets 外で、手書きの同名キー 'mid-harness' があっても drift の孤児扱いにしない
printf 'skill_version: "t"\ntargets: [cursor]\nskills_mode: manual\n' > "$T/.agents/harness.yaml"
printf '{"mid-harness":{"Stop":[{"hooks":[{"command":"echo handwritten"}]}]}}\n' > "$T/.agents/hooks.json"
python3 $S/gen_adapters.py "$T" --quiet && grep -q 'echo handwritten' "$T/.agents/hooks.json" && ok "antigravity: handwritten key kept when not a target" || ng "antigravity: handwritten key kept when not a target"
python3 $S/check_drift.py "$T" >/dev/null && ok "drift: handwritten mid-harness key is not an orphan" || ng "drift: handwritten mid-harness key is not an orphan"
rm -f "$T/.agents/hooks.json"
# agy_project_id: folderUri 一致 / 複数 / 無し / 壊れたエントリ (HOME を差し替えてテスト)
FH="$(mktemp -d "${TMPDIR:-/tmp}/mh-fakehome.XXXXXX")"; mkdir -p "$FH/.gemini/config/projects"
printf '{"id":"p1","name":"x","projectResources":{"resources":[{"folderUri":"file:///repo/a"}]}}\n' > "$FH/.gemini/config/projects/1.json"
printf '{"id":"p2","name":"x","projectResources":{"resources":[{"folderUri":"file:///repo/a/"}]}}\n' > "$FH/.gemini/config/projects/2.json"
printf '{"id":"p3","name":"y","projectResources":{"resources":[{"folderUri":"file:///repo/b"}]}}\n' > "$FH/.gemini/config/projects/3.json"
[ "$(HOME=$FH python3 $S/agy_project_id.py /repo/b)" = "p3" ] && ok "agy_project_id: exact match" || ng "agy_project_id: exact match"
r="$(HOME=$FH python3 $S/agy_project_id.py /repo/a 2>"$FH/err")"; [ "$r" = "p1" ] && grep -q "複数" "$FH/err" && ok "agy_project_id: multiple -> first + warning" || ng "agy_project_id: multiple -> first + warning"
[ -z "$(HOME=$FH python3 $S/agy_project_id.py /repo/none)" ] && ok "agy_project_id: none -> empty" || ng "agy_project_id: none -> empty"
printf '{"id":{"unexpected":true},"projectResources":{"resources":[{"folderUri":"file:///repo/c"}]}}\n' > "$FH/.gemini/config/projects/4.json"
printf '{"id":"p5","projectResources":{"resources":[{"folderUri":["file:///repo/c"]}]}}\n' > "$FH/.gemini/config/projects/5.json"
printf 'not json\n' > "$FH/.gemini/config/projects/6.json"
printf '{"id":"p7","projectResources":{"resources":[{"folderUri":"file:///repo/c"}]}}\n' > "$FH/.gemini/config/projects/7.json"
[ "$(HOME=$FH python3 $S/agy_project_id.py /repo/c 2>/dev/null)" = "p7" ] && ok "agy_project_id: broken entries skipped, valid one found" || ng "agy_project_id: broken entries skipped, valid one found"
rm -rf "$FH"
# trust_status: HOME を差し替えて missing / ok / hooks 無し を検査
FH="$(mktemp -d "${TMPDIR:-/tmp}/mh-fakehome.XXXXXX")"
printf 'skill_version: "t"\ntargets: [claude-code, codex, grok, copilot, antigravity, cursor]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    script: scripts/agent-hooks/pre-tool-policy.sh\n' > "$T/.agents/harness.yaml"
HOME=$FH python3 $S/trust_status.py "$T" > "$FH/out" 2>&1; rc=$?
[ $rc -eq 3 ] && grep -q "^codex *missing" "$FH/out" && grep -q "^copilot *missing" "$FH/out" && grep -q "^claude-code *-" "$FH/out" && ok "trust_status: reports missing (exit 3)" || ng "trust_status: reports missing (exit 3) rc=$rc"
grep -q "trustedFolders" "$FH/out" && grep -q "trusted_folders.toml" "$FH/out" && grep -q -- "--new-project" "$FH/out" && ok "trust_status: how-to per product" || ng "trust_status: how-to per product"
TC="$(cd "$T" && git rev-parse --show-toplevel)"   # trust は canonical パスで照合される
mkdir -p "$FH/.codex" "$FH/.grok" "$FH/.gemini/antigravity-cli" "$FH/.gemini/config/projects" "$FH/.copilot"
printf '[projects."%s"]\ntrust_level = "trusted"\n' "$TC" > "$FH/.codex/config.toml"
printf '[folders."%s"]\ntrusted = true\ndecided_at = 1\n' "$TC" > "$FH/.grok/trusted_folders.toml"
printf '{"trustedWorkspaces":["%s"]}\n' "$TC" > "$FH/.gemini/antigravity-cli/settings.json"
printf '{"id":"pX","projectResources":{"resources":[{"folderUri":"file://%s"}]}}\n' "$TC" > "$FH/.gemini/config/projects/x.json"
printf '{"trustedFolders":["%s"]}\n' "$TC" > "$FH/.copilot/settings.json"
HOME=$FH python3 $S/trust_status.py "$T" > "$FH/out2" 2>&1 && grep -q "揃っています" "$FH/out2" && ok "trust_status: all ok (exit 0)" || ng "trust_status: all ok (exit 0)"
printf 'skill_version: "t"\ntargets: [codex]\nskills_mode: manual\nhooks: []\n' > "$T/.agents/harness.yaml"
HOME=$FH python3 $S/trust_status.py "$T" | grep -q "trust は不要" && ok "trust_status: no hooks -> not needed" || ng "trust_status: no hooks -> not needed"
rm -rf "$FH"
# hooks: [] でも他人の hook ファイルは消さない (grok / copilot)、所有ファイルは消す
printf 'skill_version: "t"\ntargets: [grok, copilot]\nskills_mode: manual\nhooks: []\nagents: []\n' > "$T/.agents/harness.yaml"
mkdir -p "$T/.grok/hooks" "$T/.github/hooks"
printf '{"hooks":{"Stop":[]}}\n' > "$T/.grok/hooks/mid-harness.json"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen hooks: [] (grok/copilot)" || ng "gen hooks: [] (grok/copilot)"
[ -f "$T/.grok/hooks/mid-harness.json" ] && ok "grok: foreign hook file kept on hooks: []" || ng "grok: foreign hook file kept on hooks: []"
[ ! -e "$T/.github/hooks/mid-harness.json" ] && ok "copilot: owned hook file removed on hooks: []" || ng "copilot: owned hook file removed on hooks: []"
rm -f "$T/.grok/hooks/mid-harness.json"
# antigravity: 手書きの同名キー 'mid-harness' は --adopt 無しで上書きしない
printf 'skill_version: "t"\ntargets: [antigravity]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    script: scripts/agent-hooks/pre-tool-policy.sh\n' > "$T/.agents/harness.yaml"
printf '{"mid-harness":{"Stop":[{"hooks":[{"type":"command","command":"echo handwritten"}]}]}}\n' > "$T/.agents/hooks.json"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "所有 ID 無し"; then ok "antigravity: foreign 'mid-harness' key protected"; else ng "antigravity: foreign 'mid-harness' key protected"; fi
grep -q 'echo handwritten' "$T/.agents/hooks.json" && ok "antigravity: handwritten key untouched" || ng "antigravity: handwritten key untouched"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "antigravity: adopt" || ng "antigravity: adopt"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen drop antigravity" || ng "gen drop antigravity"
grep -q '"mid-harness"' "$T/.agents/hooks.json" && ng "antigravity: owned key removed on target drop" || ok "antigravity: owned key removed on target drop"
# grok の hook ファイルが他人のものなら上書きしない
printf 'skill_version: "t"\ntargets: [grok]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    script: scripts/agent-hooks/pre-tool-policy.sh\n' > "$T/.agents/harness.yaml"
mkdir -p "$T/.grok/hooks"; printf '{"hooks":{"Stop":[]}}\n' > "$T/.grok/hooks/mid-harness.json"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "所有マーカー無し"; then ok "grok: foreign hook file protected"; else ng "grok: foreign hook file protected"; fi
rm -f "$T/.grok/hooks/mid-harness.json"

# verify skip-llm with probe cleanup, and refuse to clobber existing probe-like dirs (名前が一意なので衝突しない)
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\n' > "$T/.agents/harness.yaml"
MID_HARNESS_VERIFY_SKIP_LLM=1 bash $S/verify.sh "$T" >/dev/null && ok "verify skip" || ng "verify skip"
ls "$T/.agents/skills" | grep -q probe && ng "probe cleaned" || ok "probe cleaned"

exit $fail
