#!/usr/bin/env bash
# test_scripts.sh — scripts の回帰テスト (LLM 不要、一時 git リポで scaffold → gen → drift → verify skip を通す)。usage: test_scripts.sh
set -u
S="$(cd "$(dirname "$0")" && pwd)"
T="$(mktemp -d "${TMPDIR:-/tmp}/mid-harness-selftest.XXXXXX")"; trap 'rm -rf "$T"' EXIT
fail=0
ok() { echo "pass  $1"; }
ng() { echo "FAIL  $1"; fail=1; }

git -C "$T" init -q; git -C "$T" config user.email t@t; git -C "$T" config user.name t
python3 $S/scaffold.py "$T" >/dev/null && ok "scaffold" || ng "scaffold"
python3 $S/scaffold.py "$T" | grep -q "created (0)" && ok "scaffold idempotent" || ng "scaffold idempotent"

# 既存 hooks.json に他人の handler を同居させておく
mkdir -p "$T/.codex"
printf '{"hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"echo audit"}]}]},"other":1}\n' > "$T/.codex/hooks.json"
mkdir -p "$T/.claude"; printf '{"permissions":{"allow":["Bash(ls:*)"]}}\n' > "$T/.claude/settings.json"

python3 $S/gen_adapters.py "$T" --quiet && ok "gen" || ng "gen"
grep -q '"echo audit"' "$T/.codex/hooks.json" && ok "foreign handler kept" || ng "foreign handler kept"
grep -q '"other": 1' "$T/.codex/hooks.json" && ok "foreign key kept" || ng "foreign key kept"
grep -q 'Bash(ls' "$T/.claude/settings.json" && ok "permissions kept" || ng "permissions kept"
grep -q 'git rev-parse --show-toplevel' "$T/.codex/hooks.json" && ok "codex cmd resolves root" || ng "codex cmd resolves root"
grep -q 'generated by mid-harness' "$T/.claude/agents/reviewer.md" && ok "agent marker" || ng "agent marker"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen idempotent" || ng "gen idempotent"
grep -c '"echo audit"' "$T/.codex/hooks.json" | grep -q '^1$' && ok "no duplicate on regen" || ng "no duplicate on regen"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after gen" || ng "no drift after gen"

# 手書き agent 定義の保護
printf -- '---\nname: hand\ndescription: x\n---\nhand written\n' > "$T/.claude/agents/hand.md"
cp -R "$T/.agents/agent-specs/reviewer" "$T/.agents/agent-specs/hand"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\nagents: [reviewer, hand]\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>/dev/null; then ng "handwritten agent protected"; else ok "handwritten agent protected"; fi
grep -q 'hand written' "$T/.claude/agents/hand.md" && ok "handwritten untouched (atomic)" || ng "handwritten untouched (atomic)"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "adopt" || ng "adopt"

# TOML: backslash と """ を含む prompt
printf 'skill_version: "t"\ntargets: [codex]\nskills_mode: manual\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
printf 'Use C:\\new\\queue and literal """ here.\nline2 ends with quote "\n' > "$T/.agents/agent-specs/reviewer/prompt.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "gen with backslash prompt" || ng "gen with backslash prompt"
python3 -c "import importlib,importlib.util;tomllib=importlib.import_module('tomllib') if importlib.util.find_spec('tomllib') else importlib.import_module('tomli');d=tomllib.load(open('$T/.codex/agents/reviewer.toml','rb'));assert 'C:\\\\new\\\\queue' in d['developer_instructions'] and '\"\"\"' in d['developer_instructions']" && ok "toml roundtrip" || ng "toml roundtrip"

# drift: generated skill dir に余剰ファイル
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: generate\nagents: []\n' > "$T/.agents/harness.yaml"
mkdir -p "$T/.agents/skills/demo"; printf -- '---\nname: demo\ndescription: d\n---\nx\n' > "$T/.agents/skills/demo/SKILL.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "gen skills" || ng "gen skills"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift (skills)" || ng "no drift (skills)"
touch "$T/.claude/skills/demo/stale.txt"
if python3 $S/check_drift.py "$T" | grep -q "extra file"; then ok "drift detects extra file"; else ng "drift detects extra file"; fi
rm "$T/.claude/skills/demo/stale.txt"; rm "$T/.claude/skills/demo/.mid-harness-generated"
if python3 $S/check_drift.py "$T" >/dev/null 2>&1; then ng "drift detects marker loss"; else ok "drift detects marker loss (gen refuses unmarked dir)"; fi
rm -rf "$T/.claude/skills/demo"   # マーカーを消した生成物を片付けて以降のテストに影響させない

# manifest validation
printf 'targets: [claude-code]\nhooks:\n  - event: pre-tool\n    script: scripts/agent-hooks/../../x.sh\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "symlink 越え不可"; then ok "reject path escape"; else ng "reject path escape"; fi
printf 'targets: [claude-code]\nagents: ["../x"]\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "名前のみ"; then ok "reject bad agent name"; else ng "reject bad agent name"; fi

# round2: orphan agent removal + empty codex block
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
printf 'Review carefully.\n' > "$T/.agents/agent-specs/reviewer/prompt.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt || ng "gen reviewer"
printf -- '---\nname: keepme\ndescription: x\n---\nhand written keepme\n' > "$T/.claude/agents/keepme.md"
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\nagents: []\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen with agents removed" || ng "gen with agents removed"
[ ! -e "$T/.claude/agents/reviewer.md" ] && [ ! -e "$T/.codex/agents/reviewer.toml" ] && ok "orphan agents removed" || ng "orphan agents removed"
grep -q "mid-harness:begin" "$T/.codex/config.toml" && ng "empty codex block removed" || ok "empty codex block removed"
grep -q 'hand written keepme' "$T/.claude/agents/keepme.md" 2>/dev/null && ok "handwritten agent not removed" || ng "handwritten agent not removed"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after orphan removal" || ng "no drift after orphan removal"
# round2: exact owner tag (foreign handler that merely mentions the tag must survive)
printf 'skill_version: "t"\ntargets: [codex]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    matcher: Bash\n    script: scripts/agent-hooks/pre-tool-policy.sh\n' > "$T/.agents/harness.yaml"
printf '{"hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"printf %%s # mid-harness release note"},{"type":"command","command":"bash scripts/agent-hooks/team-owned.sh"}]}]}}\n' > "$T/.codex/hooks.json"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen exact tag" || ng "gen exact tag"
grep -q "release note" "$T/.codex/hooks.json" && grep -q "team-owned.sh" "$T/.codex/hooks.json" && ok "foreign handlers with lookalike text kept" || ng "foreign handlers with lookalike text kept"
# round2: agent marker must be at fixed position
printf -- '---\nname: hand2\ndescription: x\n---\nNotes about text generated by mid-harness from somewhere; do not edit\n' > "$T/.claude/agents/hand2.md"
cp -R "$T/.agents/agent-specs/reviewer" "$T/.agents/agent-specs/hand2"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\nagents: [hand2]\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>/dev/null; then ng "lookalike marker not treated as owned"; else ok "lookalike marker not treated as owned"; fi
# round2: control chars in prompt
printf 'skill_version: "t"\ntargets: [codex]\nskills_mode: manual\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
printf 'has NUL \000 and CR \r here\n' > "$T/.agents/agent-specs/reviewer/prompt.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt && ok "gen with control chars" || ng "gen with control chars"
# CR は Python の text mode (universal newlines) で LF に正規化される。NUL が round-trip すれば十分
python3 -c "import importlib,importlib.util;tomllib=importlib.import_module('tomllib') if importlib.util.find_spec('tomllib') else importlib.import_module('tomli');d=tomllib.load(open('$T/.codex/agents/reviewer.toml','rb'));assert '\x00' in d['developer_instructions'], d" && ok "control chars roundtrip" || ng "control chars roundtrip"
# round2: falsy manifest values rejected
printf 'targets: [codex]\nhooks: false\nagents: 0\n' > "$T/.agents/harness.yaml"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "はリスト"; then ok "falsy hooks/agents rejected"; else ng "falsy hooks/agents rejected"; fi
# round2: symlink inside core skill rejected
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: generate\n' > "$T/.agents/harness.yaml"
ln -s /etc/hosts "$T/.agents/skills/demo/outside.txt"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "symlink"; then ok "symlink in skill rejected"; else ng "symlink in skill rejected"; fi
rm "$T/.agents/skills/demo/outside.txt"
# round2: exec bit drift
mkdir -p "$T/.agents/skills/demo/scripts"; printf '#!/bin/sh\necho hi\n' > "$T/.agents/skills/demo/scripts/run.sh"; chmod 755 "$T/.agents/skills/demo/scripts/run.sh"
python3 $S/gen_adapters.py "$T" --quiet && python3 $S/check_drift.py "$T" >/dev/null && ok "no drift with exec script" || ng "no drift with exec script"
chmod 644 "$T/.claude/skills/demo/scripts/run.sh"
if python3 $S/check_drift.py "$T" | grep -q "exec bit differs"; then ok "drift detects exec bit"; else ng "drift detects exec bit"; fi
chmod 755 "$T/.claude/skills/demo/scripts/run.sh"
# round2: verify leaves no empty parent dir
rm -rf "$T/.claude/skills"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\n' > "$T/.agents/harness.yaml"
mkdir -p "$T/fakebin"; printf '#!/bin/sh\necho MID_HARNESS_PROBE_OK\n' > "$T/fakebin/claude"; chmod +x "$T/fakebin/claude"
[ ! -e "$T/.claude/skills" ] && ok "precondition: no .claude/skills" || ng "precondition"
PATH="$T/fakebin:$PATH" MID_HARNESS_VERIFY_TIMEOUT=20 bash $S/verify.sh "$T" >/dev/null 2>&1   # fake CLI: hook テストは fail するが cleanup を見る
[ ! -e "$T/.claude/skills" ] && ok "no empty parent left after probe cleanup" || ng "no empty parent left after probe cleanup"
ls "$T/.agents/skills" | grep -q probe && ng "probe cleaned (fake cli)" || ok "probe cleaned (fake cli)"

# round3: front matter 無しの md の先頭 "# generated by mid-harness from" は手書き扱い (削除しない)
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\nagents: []\n' > "$T/.agents/harness.yaml"
printf '# generated by mid-harness from a design note; this is handwritten prose\nbody\n' > "$T/.claude/agents/prose.md"
printf -- '---\nname: x\n---\ntext\n---\n<!-- generated by mid-harness from x; do not edit -->\n' > "$T/.claude/agents/lateMarker.md"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen (frontmatterless case)" || ng "gen (frontmatterless case)"
[ -e "$T/.claude/agents/prose.md" ] && ok "frontmatterless md not treated as owned" || ng "frontmatterless md not treated as owned"
[ -e "$T/.claude/agents/lateMarker.md" ] && ok "marker after second --- not treated as owned" || ng "marker after second --- not treated as owned"
# round3: 生成先が symlink なら失敗し、外部ファイルを書き換えない
OUTSIDE="$(mktemp)"; printf '{"sentinel":"outside"}\n' > "$OUTSIDE"
mv "$T/.claude/settings.json" "$T/.claude/settings.json.bak"; ln -s "$OUTSIDE" "$T/.claude/settings.json"
if python3 $S/gen_adapters.py "$T" --quiet 2>&1 | grep -q "symlink"; then ok "symlink target rejected"; else ng "symlink target rejected"; fi
grep -q '"sentinel":"outside"' "$OUTSIDE" && ok "outside file untouched" || ng "outside file untouched"
rm "$T/.claude/settings.json"; mv "$T/.claude/settings.json.bak" "$T/.claude/settings.json"; rm -f "$OUTSIDE"
# round3: codex を targets から外すと agent toml と管理ブロックが消え、hooks.json の所有 handler は残る
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    matcher: Bash\n    script: scripts/agent-hooks/pre-tool-policy.sh\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
printf 'Review.\n' > "$T/.agents/agent-specs/reviewer/prompt.md"
python3 $S/gen_adapters.py "$T" --quiet --adopt || ng "gen both targets"
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: manual\nhooks:\n  - event: pre-tool\n    matcher: Bash\n    script: scripts/agent-hooks/pre-tool-policy.sh\nagents: [reviewer]\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen after dropping codex" || ng "gen after dropping codex"
[ ! -e "$T/.codex/agents/reviewer.toml" ] && ok "codex agent removed on target drop" || ng "codex agent removed on target drop"
grep -q "mid-harness:begin" "$T/.codex/config.toml" && ng "codex block removed on target drop" || ok "codex block removed on target drop"
grep -q "# mid-harness" "$T/.codex/hooks.json" && ok "codex hook handler kept on target drop (documented asymmetry)" || ng "codex hook handler kept on target drop"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after target drop" || ng "no drift after target drop"
# round3: core から skill を消すと生成 skill ディレクトリも消える
printf 'skill_version: "t"\ntargets: [claude-code]\nskills_mode: generate\nagents: []\n' > "$T/.agents/harness.yaml"
python3 $S/gen_adapters.py "$T" --quiet || ng "gen skills 2"
[ -d "$T/.claude/skills/demo" ] && ok "generated skill present" || ng "generated skill present"
rm -rf "$T/.agents/skills/demo"
python3 $S/gen_adapters.py "$T" --quiet && ok "gen after core skill removal" || ng "gen after core skill removal"
[ ! -e "$T/.claude/skills/demo" ] && ok "orphan generated skill removed" || ng "orphan generated skill removed"
python3 $S/check_drift.py "$T" >/dev/null && ok "no drift after skill removal" || ng "no drift after skill removal"

# verify skip-llm with probe cleanup, and refuse to clobber existing probe-like dirs (名前が一意なので衝突しない)
printf 'skill_version: "t"\ntargets: [claude-code, codex]\nskills_mode: manual\n' > "$T/.agents/harness.yaml"
MID_HARNESS_VERIFY_SKIP_LLM=1 bash $S/verify.sh "$T" >/dev/null && ok "verify skip" || ng "verify skip"
ls "$T/.agents/skills" | grep -q probe && ng "probe cleaned" || ok "probe cleaned"

exit $fail
