'use strict';

/**
 * genUtil.js — 生成コード (target repo 向け) 共通のヘルパ。
 * config.yaml の読み取り、生成ヘッダ (basis + do-not-edit)、決定論的 JSON 出力。
 */

const fs = require('node:fs');
const path = require('node:path');
const { parseYaml } = require('../../../../scripts/lib/yaml');
const { stamp, headerLine } = require('../../../../scripts/lib/basis');
const { sortKeys } = require('./contractsDir');

const DO_NOT_EDIT = '// generated by distillery2 — do not edit';

function readConfig(configPath) {
  const data = parseYaml(fs.readFileSync(configPath, 'utf8'));
  if (!Array.isArray(data.tiers)) throw new Error('config.yaml: tiers[] required');
  return data;
}

function tierDir(config, tierId) {
  const tier = config.tiers.find(t => t.id === tierId);
  if (!tier) throw new Error(`config.yaml: tier not found: ${tierId}`);
  return tier.dir || `apps/${tier.id}`;
}

/** `// basis: ...` の 1 行コメント。git が無ければ `// basis:` になる (決定論的)。 */
function basisComment(contractsDir, docsRoot = 'docs') {
  const root = gitCwd(contractsDir);
  const basis = stamp({
    requirements: path.join(docsRoot, 'requirements'),
    adr: path.join(docsRoot, 'adr'),
    contracts: path.relative(root, contractsDir) || '.',
  }, root);
  return `// ${headerLine(basis)}`;
}
function gitCwd(dir) { try { return fs.statSync(dir).isDirectory() ? dir : path.dirname(dir); } catch { return process.cwd(); } }

// 生成した .ts は biome の整形・lint を丸ごと抑止する (埋め込み JSON を biome が展開して format_check が落ちた。0.1.10 実走 ④-2)。
// biome 2 の biome-ignore-all はファイル先頭のコメントで有効 (実測 2.2.x)
const BIOME_IGNORE_ALL = '// biome-ignore-all format: generated (do not edit)\n// biome-ignore-all lint: generated (do not edit)';
function header(contractsDir, docsRoot) {
  return `${DO_NOT_EDIT}\n${BIOME_IGNORE_ALL}\n${basisComment(contractsDir, docsRoot)}`;
}

function writeFileDet(target, text, check, stale, written, rel) {
  if (fs.existsSync(target) && fs.readFileSync(target, 'utf8') === text) return;
  if (check) { stale.push(rel); return; }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, text);
  written.push(rel);
}

function jsonDet(value) { return JSON.stringify(sortKeys(value), null, 2) + '\n'; }

module.exports = { DO_NOT_EDIT, readConfig, tierDir, basisComment, header, writeFileDet, jsonDet };
