/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 書籍レスポンス
 * @export
 * @interface BookResponse
 */
export interface BookResponse {
    /**
     * 書籍ID
     * @type {string}
     * @memberof BookResponse
     */
    id: string;
    /**
     * タイトル
     * @type {string}
     * @memberof BookResponse
     */
    title: string;
    /**
     * 著者
     * @type {string}
     * @memberof BookResponse
     */
    author: string;
    /**
     * ISBN-13
     * @type {string}
     * @memberof BookResponse
     */
    isbn: string;
    /**
     * 出版社
     * @type {string}
     * @memberof BookResponse
     */
    publisher: string;
    /**
     * ジャンル
     * @type {string}
     * @memberof BookResponse
     */
    genre: string;
    /**
     * 資料種別
     * @type {string}
     * @memberof BookResponse
     */
    material_type: string;
    /**
     * 配架場所
     * @type {string}
     * @memberof BookResponse
     */
    location?: string;
    /**
     * 貸出状態
     * @type {BookResponseStatusEnum}
     * @memberof BookResponse
     */
    status: BookResponseStatusEnum;
    /**
     * 登録日時
     * @type {Date}
     * @memberof BookResponse
     */
    created_at: Date;
    /**
     * 更新日時
     * @type {Date}
     * @memberof BookResponse
     */
    updated_at?: Date;
}


/**
 * @export
 */
export const BookResponseStatusEnum = {
    Available: 'available',
    OnLoan: 'on_loan',
    Overdue: 'overdue'
} as const;
export type BookResponseStatusEnum = typeof BookResponseStatusEnum[keyof typeof BookResponseStatusEnum];


/**
 * Check if a given object implements the BookResponse interface.
 */
export function instanceOfBookResponse(value: object): value is BookResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('isbn' in value) || value['isbn'] === undefined) return false;
    if (!('publisher' in value) || value['publisher'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    if (!('material_type' in value) || value['material_type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function BookResponseFromJSON(json: any): BookResponse {
    return BookResponseFromJSONTyped(json, false);
}

export function BookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'author': json['author'],
        'isbn': json['isbn'],
        'publisher': json['publisher'],
        'genre': json['genre'],
        'material_type': json['material_type'],
        'location': json['location'] == null ? undefined : json['location'],
        'status': json['status'],
        'created_at': (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function BookResponseToJSON(json: any): BookResponse {
    return BookResponseToJSONTyped(json, false);
}

export function BookResponseToJSONTyped(value?: BookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'author': value['author'],
        'isbn': value['isbn'],
        'publisher': value['publisher'],
        'genre': value['genre'],
        'material_type': value['material_type'],
        'location': value['location'],
        'status': value['status'],
        'created_at': value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

