/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 書籍登録リクエスト
 * @export
 * @interface CreateBookRequest
 */
export interface CreateBookRequest {
    /**
     * 書籍タイトル
     * @type {string}
     * @memberof CreateBookRequest
     */
    title: string;
    /**
     * 著者名
     * @type {string}
     * @memberof CreateBookRequest
     */
    author: string;
    /**
     * ISBN-13形式
     * @type {string}
     * @memberof CreateBookRequest
     */
    isbn: string;
    /**
     * 出版社名
     * @type {string}
     * @memberof CreateBookRequest
     */
    publisher: string;
    /**
     * 書籍ジャンル
     * @type {CreateBookRequestGenreEnum}
     * @memberof CreateBookRequest
     */
    genre: CreateBookRequestGenreEnum;
    /**
     * 資料種別
     * @type {CreateBookRequestMaterialTypeEnum}
     * @memberof CreateBookRequest
     */
    material_type: CreateBookRequestMaterialTypeEnum;
    /**
     * 配架場所（紙書籍の場合必須）
     * @type {string}
     * @memberof CreateBookRequest
     */
    location?: string;
}


/**
 * @export
 */
export const CreateBookRequestGenreEnum = {
    : '文学',
    2: '理工',
    3: '児童書',
    4: '社会科学',
    5: '自然科学',
    6: '芸術',
    7: 'その他'
} as const;
export type CreateBookRequestGenreEnum = typeof CreateBookRequestGenreEnum[keyof typeof CreateBookRequestGenreEnum];

/**
 * @export
 */
export const CreateBookRequestMaterialTypeEnum = {
    : '紙書籍',
    2: '電子書籍'
} as const;
export type CreateBookRequestMaterialTypeEnum = typeof CreateBookRequestMaterialTypeEnum[keyof typeof CreateBookRequestMaterialTypeEnum];


/**
 * Check if a given object implements the CreateBookRequest interface.
 */
export function instanceOfCreateBookRequest(value: object): value is CreateBookRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('isbn' in value) || value['isbn'] === undefined) return false;
    if (!('publisher' in value) || value['publisher'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    if (!('material_type' in value) || value['material_type'] === undefined) return false;
    return true;
}

export function CreateBookRequestFromJSON(json: any): CreateBookRequest {
    return CreateBookRequestFromJSONTyped(json, false);
}

export function CreateBookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'author': json['author'],
        'isbn': json['isbn'],
        'publisher': json['publisher'],
        'genre': json['genre'],
        'material_type': json['material_type'],
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function CreateBookRequestToJSON(json: any): CreateBookRequest {
    return CreateBookRequestToJSONTyped(json, false);
}

export function CreateBookRequestToJSONTyped(value?: CreateBookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'author': value['author'],
        'isbn': value['isbn'],
        'publisher': value['publisher'],
        'genre': value['genre'],
        'material_type': value['material_type'],
        'location': value['location'],
    };
}

