/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 利用者登録リクエスト
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
    /**
     * 氏名
     * @type {string}
     * @memberof CreateUserRequest
     */
    name: string;
    /**
     * 連絡先
     * @type {string}
     * @memberof CreateUserRequest
     */
    contact?: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof CreateUserRequest
     */
    email: string;
    /**
     * 利用者種別
     * @type {CreateUserRequestUserTypeEnum}
     * @memberof CreateUserRequest
     */
    user_type: CreateUserRequestUserTypeEnum;
}


/**
 * @export
 */
export const CreateUserRequestUserTypeEnum = {
    : '一般',
    2: '学生',
    3: '児童'
} as const;
export type CreateUserRequestUserTypeEnum = typeof CreateUserRequestUserTypeEnum[keyof typeof CreateUserRequestUserTypeEnum];


/**
 * Check if a given object implements the CreateUserRequest interface.
 */
export function instanceOfCreateUserRequest(value: object): value is CreateUserRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('user_type' in value) || value['user_type'] === undefined) return false;
    return true;
}

export function CreateUserRequestFromJSON(json: any): CreateUserRequest {
    return CreateUserRequestFromJSONTyped(json, false);
}

export function CreateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'email': json['email'],
        'user_type': json['user_type'],
    };
}

export function CreateUserRequestToJSON(json: any): CreateUserRequest {
    return CreateUserRequestToJSONTyped(json, false);
}

export function CreateUserRequestToJSONTyped(value?: CreateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'contact': value['contact'],
        'email': value['email'],
        'user_type': value['user_type'],
    };
}

