/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InventoryResponseByGenreInner } from './InventoryResponseByGenreInner';
import {
    InventoryResponseByGenreInnerFromJSON,
    InventoryResponseByGenreInnerFromJSONTyped,
    InventoryResponseByGenreInnerToJSON,
    InventoryResponseByGenreInnerToJSONTyped,
} from './InventoryResponseByGenreInner';

/**
 * 在庫状況レスポンス
 * @export
 * @interface InventoryResponse
 */
export interface InventoryResponse {
    /**
     * 総蔵書数
     * @type {number}
     * @memberof InventoryResponse
     */
    total_books: number;
    /**
     * 在庫あり数
     * @type {number}
     * @memberof InventoryResponse
     */
    available_count: number;
    /**
     * 貸出中数
     * @type {number}
     * @memberof InventoryResponse
     */
    on_loan_count: number;
    /**
     * 延滞中数
     * @type {number}
     * @memberof InventoryResponse
     */
    overdue_count: number;
    /**
     * ジャンル別蔵書数
     * @type {Array<InventoryResponseByGenreInner>}
     * @memberof InventoryResponse
     */
    by_genre: Array<InventoryResponseByGenreInner>;
}

/**
 * Check if a given object implements the InventoryResponse interface.
 */
export function instanceOfInventoryResponse(value: object): value is InventoryResponse {
    if (!('total_books' in value) || value['total_books'] === undefined) return false;
    if (!('available_count' in value) || value['available_count'] === undefined) return false;
    if (!('on_loan_count' in value) || value['on_loan_count'] === undefined) return false;
    if (!('overdue_count' in value) || value['overdue_count'] === undefined) return false;
    if (!('by_genre' in value) || value['by_genre'] === undefined) return false;
    return true;
}

export function InventoryResponseFromJSON(json: any): InventoryResponse {
    return InventoryResponseFromJSONTyped(json, false);
}

export function InventoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total_books': json['total_books'],
        'available_count': json['available_count'],
        'on_loan_count': json['on_loan_count'],
        'overdue_count': json['overdue_count'],
        'by_genre': ((json['by_genre'] as Array<any>).map(InventoryResponseByGenreInnerFromJSON)),
    };
}

export function InventoryResponseToJSON(json: any): InventoryResponse {
    return InventoryResponseToJSONTyped(json, false);
}

export function InventoryResponseToJSONTyped(value?: InventoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_books': value['total_books'],
        'available_count': value['available_count'],
        'on_loan_count': value['on_loan_count'],
        'overdue_count': value['overdue_count'],
        'by_genre': ((value['by_genre'] as Array<any>).map(InventoryResponseByGenreInnerToJSON)),
    };
}

