/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 貸出レスポンス
 * @export
 * @interface LoanResponse
 */
export interface LoanResponse {
    /**
     * 貸出ID
     * @type {string}
     * @memberof LoanResponse
     */
    id: string;
    /**
     * 書籍ID
     * @type {string}
     * @memberof LoanResponse
     */
    book_id: string;
    /**
     * 書籍タイトル
     * @type {string}
     * @memberof LoanResponse
     */
    book_title: string;
    /**
     * 利用者ID
     * @type {string}
     * @memberof LoanResponse
     */
    user_id: string;
    /**
     * 貸出日
     * @type {Date}
     * @memberof LoanResponse
     */
    loan_date: Date;
    /**
     * 返却期限
     * @type {Date}
     * @memberof LoanResponse
     */
    due_date: Date;
    /**
     * 返却日
     * @type {Date}
     * @memberof LoanResponse
     */
    return_date?: Date;
    /**
     * 延滞フラグ
     * @type {boolean}
     * @memberof LoanResponse
     */
    is_overdue: boolean;
}

/**
 * Check if a given object implements the LoanResponse interface.
 */
export function instanceOfLoanResponse(value: object): value is LoanResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('book_id' in value) || value['book_id'] === undefined) return false;
    if (!('book_title' in value) || value['book_title'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('loan_date' in value) || value['loan_date'] === undefined) return false;
    if (!('due_date' in value) || value['due_date'] === undefined) return false;
    if (!('is_overdue' in value) || value['is_overdue'] === undefined) return false;
    return true;
}

export function LoanResponseFromJSON(json: any): LoanResponse {
    return LoanResponseFromJSONTyped(json, false);
}

export function LoanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'book_id': json['book_id'],
        'book_title': json['book_title'],
        'user_id': json['user_id'],
        'loan_date': (new Date(json['loan_date'])),
        'due_date': (new Date(json['due_date'])),
        'return_date': json['return_date'] == null ? undefined : (new Date(json['return_date'])),
        'is_overdue': json['is_overdue'],
    };
}

export function LoanResponseToJSON(json: any): LoanResponse {
    return LoanResponseToJSONTyped(json, false);
}

export function LoanResponseToJSONTyped(value?: LoanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'book_id': value['book_id'],
        'book_title': value['book_title'],
        'user_id': value['user_id'],
        'loan_date': value['loan_date'].toISOString().substring(0,10),
        'due_date': value['due_date'].toISOString().substring(0,10),
        'return_date': value['return_date'] == null ? value['return_date'] : value['return_date'].toISOString().substring(0,10),
        'is_overdue': value['is_overdue'],
    };
}

