/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoanResponse } from './LoanResponse';
import {
    LoanResponseFromJSON,
    LoanResponseFromJSONTyped,
    LoanResponseToJSON,
    LoanResponseToJSONTyped,
} from './LoanResponse';

/**
 * ページネーション付き貸出一覧
 * @export
 * @interface PaginatedLoanListResponse
 */
export interface PaginatedLoanListResponse {
    /**
     * 
     * @type {Array<LoanResponse>}
     * @memberof PaginatedLoanListResponse
     */
    items: Array<LoanResponse>;
    /**
     * 全件数
     * @type {number}
     * @memberof PaginatedLoanListResponse
     */
    total: number;
    /**
     * 現在ページ
     * @type {number}
     * @memberof PaginatedLoanListResponse
     */
    page: number;
    /**
     * 1ページあたり件数
     * @type {number}
     * @memberof PaginatedLoanListResponse
     */
    per_page: number;
}

/**
 * Check if a given object implements the PaginatedLoanListResponse interface.
 */
export function instanceOfPaginatedLoanListResponse(value: object): value is PaginatedLoanListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('per_page' in value) || value['per_page'] === undefined) return false;
    return true;
}

export function PaginatedLoanListResponseFromJSON(json: any): PaginatedLoanListResponse {
    return PaginatedLoanListResponseFromJSONTyped(json, false);
}

export function PaginatedLoanListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLoanListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(LoanResponseFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'per_page': json['per_page'],
    };
}

export function PaginatedLoanListResponseToJSON(json: any): PaginatedLoanListResponse {
    return PaginatedLoanListResponseToJSONTyped(json, false);
}

export function PaginatedLoanListResponseToJSONTyped(value?: PaginatedLoanListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(LoanResponseToJSON)),
        'total': value['total'],
        'page': value['page'],
        'per_page': value['per_page'],
    };
}

