/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationResponse } from './ReservationResponse';
import {
    ReservationResponseFromJSON,
    ReservationResponseFromJSONTyped,
    ReservationResponseToJSON,
    ReservationResponseToJSONTyped,
} from './ReservationResponse';

/**
 * ページネーション付き予約一覧
 * @export
 * @interface PaginatedReservationListResponse
 */
export interface PaginatedReservationListResponse {
    /**
     * 
     * @type {Array<ReservationResponse>}
     * @memberof PaginatedReservationListResponse
     */
    items: Array<ReservationResponse>;
    /**
     * 全件数
     * @type {number}
     * @memberof PaginatedReservationListResponse
     */
    total: number;
    /**
     * 現在ページ
     * @type {number}
     * @memberof PaginatedReservationListResponse
     */
    page: number;
    /**
     * 1ページあたり件数
     * @type {number}
     * @memberof PaginatedReservationListResponse
     */
    per_page: number;
}

/**
 * Check if a given object implements the PaginatedReservationListResponse interface.
 */
export function instanceOfPaginatedReservationListResponse(value: object): value is PaginatedReservationListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('per_page' in value) || value['per_page'] === undefined) return false;
    return true;
}

export function PaginatedReservationListResponseFromJSON(json: any): PaginatedReservationListResponse {
    return PaginatedReservationListResponseFromJSONTyped(json, false);
}

export function PaginatedReservationListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedReservationListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ReservationResponseFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'per_page': json['per_page'],
    };
}

export function PaginatedReservationListResponseToJSON(json: any): PaginatedReservationListResponse {
    return PaginatedReservationListResponseToJSONTyped(json, false);
}

export function PaginatedReservationListResponseToJSONTyped(value?: PaginatedReservationListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ReservationResponseToJSON)),
        'total': value['total'],
        'page': value['page'],
        'per_page': value['per_page'],
    };
}

