/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 予約レスポンス
 * @export
 * @interface ReservationResponse
 */
export interface ReservationResponse {
    /**
     * 予約ID
     * @type {string}
     * @memberof ReservationResponse
     */
    id: string;
    /**
     * 書籍ID
     * @type {string}
     * @memberof ReservationResponse
     */
    book_id: string;
    /**
     * 書籍タイトル
     * @type {string}
     * @memberof ReservationResponse
     */
    book_title: string;
    /**
     * 利用者ID
     * @type {string}
     * @memberof ReservationResponse
     */
    user_id: string;
    /**
     * 予約日時
     * @type {Date}
     * @memberof ReservationResponse
     */
    reserved_at: Date;
    /**
     * 予約順位
     * @type {number}
     * @memberof ReservationResponse
     */
    queue_position: number;
    /**
     * 予約状態
     * @type {ReservationResponseStatusEnum}
     * @memberof ReservationResponse
     */
    status: ReservationResponseStatusEnum;
}


/**
 * @export
 */
export const ReservationResponseStatusEnum = {
    Pending: 'pending',
    Reserved: 'reserved',
    Cancelled: 'cancelled'
} as const;
export type ReservationResponseStatusEnum = typeof ReservationResponseStatusEnum[keyof typeof ReservationResponseStatusEnum];


/**
 * Check if a given object implements the ReservationResponse interface.
 */
export function instanceOfReservationResponse(value: object): value is ReservationResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('book_id' in value) || value['book_id'] === undefined) return false;
    if (!('book_title' in value) || value['book_title'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('reserved_at' in value) || value['reserved_at'] === undefined) return false;
    if (!('queue_position' in value) || value['queue_position'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ReservationResponseFromJSON(json: any): ReservationResponse {
    return ReservationResponseFromJSONTyped(json, false);
}

export function ReservationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'book_id': json['book_id'],
        'book_title': json['book_title'],
        'user_id': json['user_id'],
        'reserved_at': (new Date(json['reserved_at'])),
        'queue_position': json['queue_position'],
        'status': json['status'],
    };
}

export function ReservationResponseToJSON(json: any): ReservationResponse {
    return ReservationResponseToJSONTyped(json, false);
}

export function ReservationResponseToJSONTyped(value?: ReservationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'book_id': value['book_id'],
        'book_title': value['book_title'],
        'user_id': value['user_id'],
        'reserved_at': value['reserved_at'].toISOString(),
        'queue_position': value['queue_position'],
        'status': value['status'],
    };
}

