/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatsResponsePopularBooksInner
 */
export interface StatsResponsePopularBooksInner {
    /**
     * 書籍ID
     * @type {string}
     * @memberof StatsResponsePopularBooksInner
     */
    book_id: string;
    /**
     * 書籍タイトル
     * @type {string}
     * @memberof StatsResponsePopularBooksInner
     */
    title: string;
    /**
     * 貸出回数
     * @type {number}
     * @memberof StatsResponsePopularBooksInner
     */
    loan_count: number;
}

/**
 * Check if a given object implements the StatsResponsePopularBooksInner interface.
 */
export function instanceOfStatsResponsePopularBooksInner(value: object): value is StatsResponsePopularBooksInner {
    if (!('book_id' in value) || value['book_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('loan_count' in value) || value['loan_count'] === undefined) return false;
    return true;
}

export function StatsResponsePopularBooksInnerFromJSON(json: any): StatsResponsePopularBooksInner {
    return StatsResponsePopularBooksInnerFromJSONTyped(json, false);
}

export function StatsResponsePopularBooksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsResponsePopularBooksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'book_id': json['book_id'],
        'title': json['title'],
        'loan_count': json['loan_count'],
    };
}

export function StatsResponsePopularBooksInnerToJSON(json: any): StatsResponsePopularBooksInner {
    return StatsResponsePopularBooksInnerToJSONTyped(json, false);
}

export function StatsResponsePopularBooksInnerToJSONTyped(value?: StatsResponsePopularBooksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'book_id': value['book_id'],
        'title': value['title'],
        'loan_count': value['loan_count'],
    };
}

