/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatsResponsePopularBooksInner } from './StatsResponsePopularBooksInner';
import {
    StatsResponsePopularBooksInnerFromJSON,
    StatsResponsePopularBooksInnerFromJSONTyped,
    StatsResponsePopularBooksInnerToJSON,
    StatsResponsePopularBooksInnerToJSONTyped,
} from './StatsResponsePopularBooksInner';
import type { StatsResponseByGenreInner } from './StatsResponseByGenreInner';
import {
    StatsResponseByGenreInnerFromJSON,
    StatsResponseByGenreInnerFromJSONTyped,
    StatsResponseByGenreInnerToJSON,
    StatsResponseByGenreInnerToJSONTyped,
} from './StatsResponseByGenreInner';
import type { StatsResponseMonthlyTrendInner } from './StatsResponseMonthlyTrendInner';
import {
    StatsResponseMonthlyTrendInnerFromJSON,
    StatsResponseMonthlyTrendInnerFromJSONTyped,
    StatsResponseMonthlyTrendInnerToJSON,
    StatsResponseMonthlyTrendInnerToJSONTyped,
} from './StatsResponseMonthlyTrendInner';

/**
 * 統計レスポンス
 * @export
 * @interface StatsResponse
 */
export interface StatsResponse {
    /**
     * 集計期間
     * @type {string}
     * @memberof StatsResponse
     */
    period: string;
    /**
     * 期間内総貸出回数
     * @type {number}
     * @memberof StatsResponse
     */
    total_loans: number;
    /**
     * 人気書籍ランキング
     * @type {Array<StatsResponsePopularBooksInner>}
     * @memberof StatsResponse
     */
    popular_books: Array<StatsResponsePopularBooksInner>;
    /**
     * 月別貸出推移
     * @type {Array<StatsResponseMonthlyTrendInner>}
     * @memberof StatsResponse
     */
    monthly_trend: Array<StatsResponseMonthlyTrendInner>;
    /**
     * ジャンル別貸出構成
     * @type {Array<StatsResponseByGenreInner>}
     * @memberof StatsResponse
     */
    by_genre?: Array<StatsResponseByGenreInner>;
}

/**
 * Check if a given object implements the StatsResponse interface.
 */
export function instanceOfStatsResponse(value: object): value is StatsResponse {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('total_loans' in value) || value['total_loans'] === undefined) return false;
    if (!('popular_books' in value) || value['popular_books'] === undefined) return false;
    if (!('monthly_trend' in value) || value['monthly_trend'] === undefined) return false;
    return true;
}

export function StatsResponseFromJSON(json: any): StatsResponse {
    return StatsResponseFromJSONTyped(json, false);
}

export function StatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'period': json['period'],
        'total_loans': json['total_loans'],
        'popular_books': ((json['popular_books'] as Array<any>).map(StatsResponsePopularBooksInnerFromJSON)),
        'monthly_trend': ((json['monthly_trend'] as Array<any>).map(StatsResponseMonthlyTrendInnerFromJSON)),
        'by_genre': json['by_genre'] == null ? undefined : ((json['by_genre'] as Array<any>).map(StatsResponseByGenreInnerFromJSON)),
    };
}

export function StatsResponseToJSON(json: any): StatsResponse {
    return StatsResponseToJSONTyped(json, false);
}

export function StatsResponseToJSONTyped(value?: StatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': value['period'],
        'total_loans': value['total_loans'],
        'popular_books': ((value['popular_books'] as Array<any>).map(StatsResponsePopularBooksInnerToJSON)),
        'monthly_trend': ((value['monthly_trend'] as Array<any>).map(StatsResponseMonthlyTrendInnerToJSON)),
        'by_genre': value['by_genre'] == null ? undefined : ((value['by_genre'] as Array<any>).map(StatsResponseByGenreInnerToJSON)),
    };
}

