/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatsResponseByGenreInner
 */
export interface StatsResponseByGenreInner {
    /**
     * ジャンル名
     * @type {string}
     * @memberof StatsResponseByGenreInner
     */
    genre: string;
    /**
     * 貸出回数
     * @type {number}
     * @memberof StatsResponseByGenreInner
     */
    count: number;
}

/**
 * Check if a given object implements the StatsResponseByGenreInner interface.
 */
export function instanceOfStatsResponseByGenreInner(value: object): value is StatsResponseByGenreInner {
    if (!('genre' in value) || value['genre'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function StatsResponseByGenreInnerFromJSON(json: any): StatsResponseByGenreInner {
    return StatsResponseByGenreInnerFromJSONTyped(json, false);
}

export function StatsResponseByGenreInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsResponseByGenreInner {
    if (json == null) {
        return json;
    }
    return {
        
        'genre': json['genre'],
        'count': json['count'],
    };
}

export function StatsResponseByGenreInnerToJSON(json: any): StatsResponseByGenreInner {
    return StatsResponseByGenreInnerToJSONTyped(json, false);
}

export function StatsResponseByGenreInnerToJSONTyped(value?: StatsResponseByGenreInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'genre': value['genre'],
        'count': value['count'],
    };
}

