/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 利用者更新リクエスト
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
    /**
     * 氏名
     * @type {string}
     * @memberof UpdateUserRequest
     */
    name: string;
    /**
     * 連絡先
     * @type {string}
     * @memberof UpdateUserRequest
     */
    contact?: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof UpdateUserRequest
     */
    email: string;
    /**
     * 利用者種別
     * @type {UpdateUserRequestUserTypeEnum}
     * @memberof UpdateUserRequest
     */
    user_type: UpdateUserRequestUserTypeEnum;
}


/**
 * @export
 */
export const UpdateUserRequestUserTypeEnum = {
    : '一般',
    2: '学生',
    3: '児童'
} as const;
export type UpdateUserRequestUserTypeEnum = typeof UpdateUserRequestUserTypeEnum[keyof typeof UpdateUserRequestUserTypeEnum];


/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(value: object): value is UpdateUserRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('user_type' in value) || value['user_type'] === undefined) return false;
    return true;
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestFromJSONTyped(json, false);
}

export function UpdateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'email': json['email'],
        'user_type': json['user_type'],
    };
}

export function UpdateUserRequestToJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestToJSONTyped(json, false);
}

export function UpdateUserRequestToJSONTyped(value?: UpdateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'contact': value['contact'],
        'email': value['email'],
        'user_type': value['user_type'],
    };
}

