/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 書籍更新リクエスト
 * @export
 * @interface UpdateBookRequest
 */
export interface UpdateBookRequest {
    /**
     * 書籍タイトル
     * @type {string}
     * @memberof UpdateBookRequest
     */
    title: string;
    /**
     * 著者名
     * @type {string}
     * @memberof UpdateBookRequest
     */
    author: string;
    /**
     * ISBN-13形式
     * @type {string}
     * @memberof UpdateBookRequest
     */
    isbn: string;
    /**
     * 出版社名
     * @type {string}
     * @memberof UpdateBookRequest
     */
    publisher: string;
    /**
     * 書籍ジャンル
     * @type {UpdateBookRequestGenreEnum}
     * @memberof UpdateBookRequest
     */
    genre: UpdateBookRequestGenreEnum;
    /**
     * 資料種別
     * @type {UpdateBookRequestMaterialTypeEnum}
     * @memberof UpdateBookRequest
     */
    material_type: UpdateBookRequestMaterialTypeEnum;
    /**
     * 配架場所
     * @type {string}
     * @memberof UpdateBookRequest
     */
    location?: string;
}


/**
 * @export
 */
export const UpdateBookRequestGenreEnum = {
    : '文学',
    2: '理工',
    3: '児童書',
    4: '社会科学',
    5: '自然科学',
    6: '芸術',
    7: 'その他'
} as const;
export type UpdateBookRequestGenreEnum = typeof UpdateBookRequestGenreEnum[keyof typeof UpdateBookRequestGenreEnum];

/**
 * @export
 */
export const UpdateBookRequestMaterialTypeEnum = {
    : '紙書籍',
    2: '電子書籍'
} as const;
export type UpdateBookRequestMaterialTypeEnum = typeof UpdateBookRequestMaterialTypeEnum[keyof typeof UpdateBookRequestMaterialTypeEnum];


/**
 * Check if a given object implements the UpdateBookRequest interface.
 */
export function instanceOfUpdateBookRequest(value: object): value is UpdateBookRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('isbn' in value) || value['isbn'] === undefined) return false;
    if (!('publisher' in value) || value['publisher'] === undefined) return false;
    if (!('genre' in value) || value['genre'] === undefined) return false;
    if (!('material_type' in value) || value['material_type'] === undefined) return false;
    return true;
}

export function UpdateBookRequestFromJSON(json: any): UpdateBookRequest {
    return UpdateBookRequestFromJSONTyped(json, false);
}

export function UpdateBookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'author': json['author'],
        'isbn': json['isbn'],
        'publisher': json['publisher'],
        'genre': json['genre'],
        'material_type': json['material_type'],
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function UpdateBookRequestToJSON(json: any): UpdateBookRequest {
    return UpdateBookRequestToJSONTyped(json, false);
}

export function UpdateBookRequestToJSONTyped(value?: UpdateBookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'author': value['author'],
        'isbn': value['isbn'],
        'publisher': value['publisher'],
        'genre': value['genre'],
        'material_type': value['material_type'],
        'location': value['location'],
    };
}

