/* tslint:disable */
/* eslint-disable */
/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 利用者レスポンス
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 利用者ID
     * @type {string}
     * @memberof UserResponse
     */
    id: string;
    /**
     * 利用者番号
     * @type {string}
     * @memberof UserResponse
     */
    user_number: string;
    /**
     * 氏名
     * @type {string}
     * @memberof UserResponse
     */
    name: string;
    /**
     * 連絡先
     * @type {string}
     * @memberof UserResponse
     */
    contact?: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof UserResponse
     */
    email: string;
    /**
     * 利用者種別
     * @type {string}
     * @memberof UserResponse
     */
    user_type: string;
    /**
     * 登録日
     * @type {Date}
     * @memberof UserResponse
     */
    registered_at: Date;
}

/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): value is UserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user_number' in value) || value['user_number'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('user_type' in value) || value['user_type'] === undefined) return false;
    if (!('registered_at' in value) || value['registered_at'] === undefined) return false;
    return true;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user_number': json['user_number'],
        'name': json['name'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'email': json['email'],
        'user_type': json['user_type'],
        'registered_at': (new Date(json['registered_at'])),
    };
}

export function UserResponseToJSON(json: any): UserResponse {
    return UserResponseToJSONTyped(json, false);
}

export function UserResponseToJSONTyped(value?: UserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_number': value['user_number'],
        'name': value['name'],
        'contact': value['contact'],
        'email': value['email'],
        'user_type': value['user_type'],
        'registered_at': value['registered_at'].toISOString().substring(0,10),
    };
}

