'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { SCRIPTS, CONFIG, freshContracts, outRoot } = require('./support');

const compileContracts = require(path.join(SCRIPTS, 'compileContracts'));
const genApiClient = require(path.join(SCRIPTS, 'genApiClient'));

function generate() {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  const out = outRoot();
  const r = genApiClient.run(contractsDir, { configPath: CONFIG, outRoot: out });
  const read = (f) => fs.readFileSync(path.join(out, 'packages/contracts/api', f), 'utf8');
  return { contractsDir, out, r, read };
}

test('types.ts / client.ts / server.ts を生成しヘッダを付ける', () => {
  const { r, read } = generate();
  assert.deepEqual(r.files.sort(), [
    'packages/contracts/api/client.ts',
    'packages/contracts/api/server.ts',
    'packages/contracts/api/types.ts',
  ]);
  for (const f of ['types.ts', 'client.ts', 'server.ts']) {
    const t = read(f);
    assert.match(t, /generated by distillery2/);
    assert.match(t, /\/\/ basis:/);
  }
});

test('types.ts は component スキーマを TypeScript 型へ変換する (enum / nullable / optional)', () => {
  const { read } = generate();
  const t = read('types.ts');
  assert.match(t, /export interface CreateLoan \{[\s\S]*bookId: string;[\s\S]*days\?: 7 \| 14 \| 28;/);
  assert.match(t, /export interface Loan \{[\s\S]*dueDate\?: string \| null;/);
  assert.match(t, /status: "borrowed" \| "returned";/);
  assert.match(t, /export interface Problem \{[\s\S]*code: "BOOK_NOT_AVAILABLE" \| "CONFLICT";/);
});

test('client.ts は operationId ごとに型付き fetch 関数を出す (path/body/response by status)', () => {
  const { read } = generate();
  const c = read('client.ts');
  assert.match(c, /import type \{ Book, CreateLoan, Loan, Problem \} from '\.\/types';/);
  // createLoan: body + status 別 response union
  assert.match(c, /export interface CreateLoanArgs \{\n  body: CreateLoan;\n\}/);
  assert.match(c, /export type CreateLoanResult =\n  \| \{ status: 201; data: Loan \}\n  \| \{ status: 409; data: Problem \};/);
  assert.match(c, /export async function createLoan\(args: CreateLoanArgs, options: ClientOptions = \{\}\): Promise<CreateLoanResult>/);
  assert.match(c, /method: "POST"/);
  // path パラメータは encodeURIComponent で埋める
  assert.match(c, /\/books\/\$\{encodeURIComponent\(String\(args\.id\)\)\}/);
  assert.match(c, /export async function getBook\(args: GetBookArgs/);
  // fetch は差し替え可能
  assert.match(c, /\(options\.fetch \?\? fetch\)/);
});

test('server.ts は operationId ↔ method/path 表を出す', () => {
  const { read } = generate();
  const s = read('server.ts');
  assert.match(s, /createLoan: \{ method: "POST", path: "\/loans" \}/);
  assert.match(s, /getBook: \{ method: "GET", path: "\/books\/\{id\}" \}/);
  assert.match(s, /export type OperationId = keyof typeof operations;/);
});

test('決定論的: 2 回生成しても同一', () => {
  const a = generate();
  const b = generate();
  for (const f of ['types.ts', 'client.ts', 'server.ts']) assert.equal(a.read(f), b.read(f));
});

test('--check は再生成不要のとき current (stale を投げない)', () => {
  const { contractsDir, out } = generate();
  const r = genApiClient.run(contractsDir, { configPath: CONFIG, outRoot: out, check: true });
  assert.equal(r.status, 'current');
});

test('schemaToTs 単体: $ref / array / nullable / enum', () => {
  assert.equal(genApiClient.schemaToTs({ $ref: '#/components/schemas/Loan' }), 'Loan');
  assert.equal(genApiClient.schemaToTs({ type: 'array', items: { $ref: '#/components/schemas/Book' } }), 'Book[]');
  assert.equal(genApiClient.schemaToTs({ type: ['string', 'null'] }), 'string | null');
  assert.equal(genApiClient.schemaToTs({ type: 'string', enum: ['a', 'b'] }), '"a" | "b"');
  assert.equal(genApiClient.schemaToTs({ type: 'integer' }), 'number');
});
