'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { SCRIPTS, CONFIG, freshContracts, outRoot } = require('./support');

const compileContracts = require(path.join(SCRIPTS, 'compileContracts'));
const genApiClient = require(path.join(SCRIPTS, 'genApiClient'));

function generate() {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  const out = outRoot();
  const r = genApiClient.run(contractsDir, { configPath: CONFIG, outRoot: out });
  const read = (f) => fs.readFileSync(path.join(out, 'packages/contracts/api', f), 'utf8');
  return { contractsDir, out, r, read };
}

test('types.ts / client.ts / server.ts を生成しヘッダを付ける', () => {
  const { r, read } = generate();
  assert.deepEqual(r.files.sort(), [
    'packages/contracts/api/client.ts',
    'packages/contracts/api/server.ts',
    'packages/contracts/api/types.ts',
  ]);
  for (const f of ['types.ts', 'client.ts', 'server.ts']) {
    const t = read(f);
    assert.match(t, /generated by distillery2/);
    assert.match(t, /\/\/ basis:/);
  }
});

test('types.ts は component スキーマを TypeScript 型へ変換する (enum / nullable / optional)', () => {
  const { read } = generate();
  const t = read('types.ts');
  assert.match(t, /export interface CreateLoan \{[\s\S]*bookId: string;[\s\S]*days\?: 7 \| 14 \| 28;/);
  assert.match(t, /export interface Loan \{[\s\S]*dueDate\?: string \| null;/);
  assert.match(t, /status: "borrowed" \| "returned";/);
  assert.match(t, /export interface Problem \{[\s\S]*code: "BOOK_NOT_AVAILABLE" \| "CONFLICT";/);
});

test('client.ts は operationId ごとに型付き fetch 関数を出す (path/body/response by status)', () => {
  const { read } = generate();
  const c = read('client.ts');
  assert.match(c, /import type \{ Book, CreateLoan, Loan, Problem \} from '\.\/types';/);
  // createLoan: body + status 別 response union
  assert.match(c, /export interface CreateLoanArgs \{\n  body: CreateLoan;\n\}/);
  assert.match(c, /export type CreateLoanResult =\n  \| \{ status: 201; data: Loan \}\n  \| \{ status: 409; data: Problem \};/);
  assert.match(c, /export async function createLoan\(args: CreateLoanArgs, options: ClientOptions = \{\}\): Promise<CreateLoanResult>/);
  assert.match(c, /method: "POST"/);
  // path パラメータは encodeURIComponent で埋める
  assert.match(c, /\/books\/\$\{encodeURIComponent\(String\(args\.id\)\)\}/);
  assert.match(c, /export async function getBook\(args: GetBookArgs/);
  // fetch は差し替え可能
  assert.match(c, /\(options\.fetch \?\? fetch\)/);
});

test('server.ts は operationId ↔ method/path 表を出す', () => {
  const { read } = generate();
  const s = read('server.ts');
  assert.match(s, /createLoan: \{ method: "POST", path: "\/loans" \}/);
  assert.match(s, /getBook: \{ method: "GET", path: "\/books\/\{id\}" \}/);
  assert.match(s, /export type OperationId = keyof typeof operations;/);
});

test('決定論的: 2 回生成しても同一', () => {
  const a = generate();
  const b = generate();
  for (const f of ['types.ts', 'client.ts', 'server.ts']) assert.equal(a.read(f), b.read(f));
});

test('--check は再生成不要のとき current (stale を投げない)', () => {
  const { contractsDir, out } = generate();
  const r = genApiClient.run(contractsDir, { configPath: CONFIG, outRoot: out, check: true });
  assert.equal(r.status, 'current');
});

test('schemaToTs 単体: $ref / array / nullable / enum', () => {
  assert.equal(genApiClient.schemaToTs({ $ref: '#/components/schemas/Loan' }), 'Loan');
  assert.equal(genApiClient.schemaToTs({ type: 'array', items: { $ref: '#/components/schemas/Book' } }), 'Book[]');
  assert.equal(genApiClient.schemaToTs({ type: ['string', 'null'] }), 'string | null');
  assert.equal(genApiClient.schemaToTs({ type: 'string', enum: ['a', 'b'] }), '"a" | "b"');
  assert.equal(genApiClient.schemaToTs({ type: 'integer' }), 'number');
});

test('schemaToTs 単体: allOf / additionalProperties 衝突', () => {
  // 名前付き object の allOf は交差型として保持する
  assert.equal(
    genApiClient.schemaToTs({ type: 'object', allOf: [{ $ref: '#/components/schemas/Base' }], required: ['id'], properties: { id: { type: 'string' } } }),
    'Base & { id: string }',
  );
  // 既知プロパティ (string) と additionalProperties (number) が衝突しても Record 交差でコンパイル可能にする
  assert.equal(
    genApiClient.schemaToTs({ type: 'object', properties: { name: { type: 'string' } }, additionalProperties: { type: 'number' } }),
    '{ name?: string } & Record<string, number>',
  );
});

// 生成した types.ts / client.ts / server.ts を実際に tsc でコンパイルし、境界スキーマを含めて型検査が通ることを確かめる。
test('生成物が tsc --strict でコンパイルできる (allOf / additionalProperties 衝突 / ハイフン path param / nullable / oneOf)', () => {
  const bundle = {
    openapi: '3.1.0',
    info: { title: 'Boundary', version: '1.0.0' },
    paths: {
      '/books/{book-id}': {
        parameters: [{ name: 'book-id', in: 'path', required: true, schema: { type: 'string' } }],
        get: {
          operationId: 'getBookByHyphen',
          parameters: [{ name: 'q', in: 'query', required: false, schema: { type: 'string' } }],
          responses: { 200: { description: 'ok', content: { 'application/json': { schema: { $ref: '#/components/schemas/Extended' } } } } },
        },
      },
      '/bags': {
        post: {
          operationId: 'createBag',
          requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Bag' } } } },
          responses: {
            201: { description: 'created', content: { 'application/json': { schema: { $ref: '#/components/schemas/Choice' } } } },
            400: { description: 'bad', content: { 'application/json': { schema: { $ref: '#/components/schemas/Nullable' } } } },
          },
        },
      },
    },
    components: {
      schemas: {
        Base: { type: 'object', required: ['id'], properties: { id: { type: 'string' } } },
        Extended: { type: 'object', allOf: [{ $ref: '#/components/schemas/Base' }], required: ['name'], properties: { name: { type: 'string' } } },
        Bag: { type: 'object', properties: { name: { type: 'string' } }, additionalProperties: { type: 'number' } },
        Nullable: { type: 'object', properties: { note: { type: ['string', 'null'] } } },
        Choice: { oneOf: [{ $ref: '#/components/schemas/Base' }, { $ref: '#/components/schemas/Bag' }] },
      },
    },
  };
  const head = '// generated by distillery2 — do not edit\n// basis: test@0000000';
  const filesMap = genApiClient.buildFiles({ bundle, contract: { id: 'api' }, head });
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'd2-tsc-'));
  for (const [rel, text] of filesMap) fs.writeFileSync(path.join(dir, path.basename(rel)), text);

  const tsc = path.resolve(__dirname, '../../../node_modules/.bin/tsc');
  assert.ok(fs.existsSync(tsc), 'node_modules/.bin/tsc が無い (npm install 済みか)');
  const args = ['--noEmit', '--strict', '--target', 'es2022', '--moduleResolution', 'bundler', '--module', 'esnext',
    path.join(dir, 'types.ts'), path.join(dir, 'client.ts'), path.join(dir, 'server.ts')];
  const res = spawnSync(tsc, args, { encoding: 'utf8' });
  assert.equal(res.status, 0, `tsc failed:\n${res.stdout || ''}${res.stderr || ''}`);

  // 生成された境界型が期待どおりであることも確かめる
  const types = fs.readFileSync(path.join(dir, 'types.ts'), 'utf8');
  assert.match(types, /export type Extended = Base & \{ name: string \};/);
  assert.match(types, /export type Bag = \{ name\?: string \} & Record<string, number>;/);
  assert.match(types, /export type Choice = Base \| Bag;/);
  const client = fs.readFileSync(path.join(dir, 'client.ts'), 'utf8');
  // ハイフン path param は args["book-id"] でアクセスする (args.["book-id"] にしない)
  assert.match(client, /"book-id": string;/);
  assert.match(client, /encodeURIComponent\(String\(args\["book-id"\]\)\)/);
  assert.ok(!client.includes('args.["book-id"]'), 'args.["book-id"] は構文エラー');
});
