'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { SCRIPTS, CONFIG, freshContracts, outRoot } = require('./support');

const compileContracts = require(path.join(SCRIPTS, 'compileContracts.js'));
const genContractTests = require(path.join(SCRIPTS, 'genContractTests.js'));

function generated(uc) {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  const out = outRoot();
  genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out, uc });
  return out;
}
const read = (out, rel) => fs.readFileSync(path.join(out, rel), 'utf8');

test('provider テスト・consumer stub のファイル名が期待どおり', () => {
  const out = generated();
  const files = [];
  (function walk(d) { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); e.isDirectory() ? walk(p) : files.push(path.relative(out, p)); } })(out);
  const set = new Set(files);
  for (const f of [
    'apps/backend-api/test/contract/createLoan.test.ts',
    'apps/backend-api/test/contract/getBook.test.ts',
    'apps/backend-api/test/contract/returnLoan.test.ts',
    'apps/backend-api/test/contract/messages.test.ts',
    'packages/contracts/api/stubs/createLoan.201.json',
    'packages/contracts/api/stubs/createLoan.409.json',
    'packages/contracts/api/stubs/getBook.200.json',
    'packages/contracts/events/validators.ts',
  ]) assert.ok(set.has(f), `missing ${f}`);
});

test('example の無い operation は it.todo になる', () => {
  const out = generated();
  const returnLoan = read(out, 'apps/backend-api/test/contract/returnLoan.test.ts');
  assert.match(returnLoan, /it\.todo\('responds 200/);
  const createLoan = read(out, 'apps/backend-api/test/contract/createLoan.test.ts');
  assert.match(createLoan, /it\('responds 201 \(example: created\)/);
  assert.match(createLoan, /it\('responds 409 \(example: unavailable\)/);
  assert.doesNotMatch(createLoan, /it\.todo/);
});

test('生成物は do-not-edit ヘッダを持ち、決定論的', () => {
  const a = generated(), b = generated();
  const rel = 'apps/backend-api/test/contract/createLoan.test.ts';
  assert.match(read(a, rel), /generated by distillery2 — do not edit/);
  assert.equal(read(a, rel), read(b, rel));
});

test('--uc は当該 UC の operation だけに絞る', () => {
  const out = generated('loan-register');
  assert.ok(fs.existsSync(path.join(out, 'apps/backend-api/test/contract/createLoan.test.ts')));
  assert.ok(fs.existsSync(path.join(out, 'apps/backend-api/test/contract/getBook.test.ts')));
  // returnLoan は loan-register に含まれないので生成されない
  assert.ok(!fs.existsSync(path.join(out, 'apps/backend-api/test/contract/returnLoan.test.ts')));
});

test('consumer stub は response example の中身', () => {
  const out = generated();
  const stub = JSON.parse(read(out, 'packages/contracts/api/stubs/createLoan.201.json'));
  assert.equal(stub.status, 'borrowed');
  assert.equal(stub.bookId, 'book-1');
});
