'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { SCRIPTS, CONFIG, freshContracts, outRoot } = require('./support');

const compileContracts = require(path.join(SCRIPTS, 'compileContracts.js'));
const genContractTests = require(path.join(SCRIPTS, 'genContractTests.js'));

function generated(uc) {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  const out = outRoot();
  genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out, uc });
  return out;
}
const read = (out, rel) => fs.readFileSync(path.join(out, rel), 'utf8');

test('provider テスト・consumer stub のファイル名が期待どおり', () => {
  const out = generated();
  const files = [];
  (function walk(d) { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); e.isDirectory() ? walk(p) : files.push(path.relative(out, p)); } })(out);
  const set = new Set(files);
  for (const f of [
    'apps/backend-api/test/contract/createLoan.test.ts',
    'apps/backend-api/test/contract/getBook.test.ts',
    'apps/backend-api/test/contract/returnLoan.test.ts',
    'apps/backend-api/test/contract/messages.test.ts',
    'packages/contracts/api/stubs/createLoan.201.json',
    'packages/contracts/api/stubs/createLoan.409.json',
    'packages/contracts/api/stubs/getBook.200.json',
    'packages/contracts/events/validators.ts',
  ]) assert.ok(set.has(f), `missing ${f}`);
});

test('example の無い operation は it.todo になる', () => {
  const out = generated();
  const returnLoan = read(out, 'apps/backend-api/test/contract/returnLoan.test.ts');
  assert.match(returnLoan, /it\.todo\('responds 200/);
  const createLoan = read(out, 'apps/backend-api/test/contract/createLoan.test.ts');
  assert.match(createLoan, /it\('responds 201 \(example: success\)/);
  assert.match(createLoan, /it\('responds 409 \(example: conflict\)/);
  assert.doesNotMatch(createLoan, /it\.todo/);
});

test('status ごとに同名の request example を送る (201=success, 409=conflict)', () => {
  const out = generated();
  const createLoan = read(out, 'apps/backend-api/test/contract/createLoan.test.ts');
  // 201 は success 入力 (book-1)、409 は conflict 入力 (book-2) を送る
  const send201 = /responds 201 \(example: success\)[\s\S]*?\.send\((\{[^;]*?\})\)/.exec(createLoan);
  const send409 = /responds 409 \(example: conflict\)[\s\S]*?\.send\((\{[^;]*?\})\)/.exec(createLoan);
  assert.ok(send201 && /book-1/.test(send201[1]), 'expected 201 to send book-1 request');
  assert.ok(send409 && /book-2/.test(send409[1]), 'expected 409 to send book-2 request');
});

test('response example に対応する request example が無い status は it.todo', () => {
  // createLoan の 409 response example と同名の request example (conflict) を消すと todo になる
  const { contractsDir } = freshContracts();
  const openapiPath = path.join(contractsDir, 'openapi', 'openapi.yaml');
  const y = fs.readFileSync(openapiPath, 'utf8').replace(/              conflict:\n                value:\n                  bookId: book-2\n                  days: 14\n/, '');
  fs.writeFileSync(openapiPath, y);
  compileContracts.run(contractsDir);
  const out = outRoot();
  genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out });
  const createLoan = read(out, 'apps/backend-api/test/contract/createLoan.test.ts');
  assert.match(createLoan, /it\.todo\('409: request example "conflict" missing/);
});

test('生成物は do-not-edit ヘッダを持ち、決定論的', () => {
  const a = generated(), b = generated();
  const rel = 'apps/backend-api/test/contract/createLoan.test.ts';
  assert.match(read(a, rel), /generated by distillery2 — do not edit/);
  assert.equal(read(a, rel), read(b, rel));
});

test('--uc は当該 UC の operation だけに絞る', () => {
  const out = generated('loan-register');
  assert.ok(fs.existsSync(path.join(out, 'apps/backend-api/test/contract/createLoan.test.ts')));
  assert.ok(fs.existsSync(path.join(out, 'apps/backend-api/test/contract/getBook.test.ts')));
  // returnLoan は loan-register に含まれないので生成されない
  assert.ok(!fs.existsSync(path.join(out, 'apps/backend-api/test/contract/returnLoan.test.ts')));
});

test('consumer stub は response example の中身', () => {
  const out = generated();
  const stub = JSON.parse(read(out, 'packages/contracts/api/stubs/createLoan.201.json'));
  assert.equal(stub.status, 'borrowed');
  assert.equal(stub.bookId, 'book-1');
});

test('全生成では旧 operation の生成テストを stale として削除する', () => {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  const out = outRoot();
  genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out });
  // 旧 operation を模した所有ファイル (OWNER_TAG 付き) を植える
  const orphan = path.join(out, 'apps/backend-api/test/contract/oldOp.test.ts');
  fs.writeFileSync(orphan, '// generated by distillery2 — do not edit\n// distillery2-owner: d2-contract/genContractTests\n');
  // genRdbDdl 由来の db-schema.test.ts (OWNER_TAG 無し) は消してはならない
  const foreign = path.join(out, 'apps/backend-api/test/contract/db-schema.test.ts');
  fs.writeFileSync(foreign, '// generated by distillery2 — do not edit\n');
  const r = genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out });
  assert.ok(!fs.existsSync(orphan), 'orphan test should be removed');
  assert.ok(r.removed.includes('apps/backend-api/test/contract/oldOp.test.ts'), 'removed should list orphan');
  assert.ok(fs.existsSync(foreign), 'foreign generated file must survive');
});

test('--check は stale な旧生成物を報告して throw する', () => {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  const out = outRoot();
  genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out });
  const orphan = path.join(out, 'apps/backend-api/test/contract/oldOp.test.ts');
  fs.writeFileSync(orphan, '// generated by distillery2 — do not edit\n// distillery2-owner: d2-contract/genContractTests\n');
  assert.throws(() => genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out, check: true }), /obsolete/);
});

test('手書き stub はマニフェスト外なので再生成でも消えない (Finding 2)', () => {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  const out = outRoot();
  genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out });
  // マニフェストが生成されている
  const manifest = path.join(out, 'packages/contracts/api/stubs/.distillery2-generated.json');
  assert.ok(fs.existsSync(manifest), 'stub manifest should be written');
  assert.ok(JSON.parse(fs.readFileSync(manifest, 'utf8')).includes('createLoan.201.json'));
  // 手書き stub を同じディレクトリに置く (マニフェスト外)
  const handwritten = path.join(out, 'packages/contracts/api/stubs/handwritten.json');
  fs.writeFileSync(handwritten, '{"hand":"written"}\n');
  // 再生成しても手書き stub は残る
  const r = genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out });
  assert.ok(fs.existsSync(handwritten), 'hand-placed stub must survive regeneration');
  assert.ok(!r.removed.includes('packages/contracts/api/stubs/handwritten.json'));
  // --check も手書き stub を obsolete 扱いしない
  assert.doesNotThrow(() => genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out, check: true }));
});

test('契約から消えた stub はマニフェスト基準で削除・報告する (Finding 2)', () => {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  const out = outRoot();
  genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out });
  // マニフェストに前回生成扱いの stub を追加し、実体も置く (契約から消えた状態を模す)
  const manifestPath = path.join(out, 'packages/contracts/api/stubs/.distillery2-generated.json');
  const names = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  names.push('gone.200.json');
  fs.writeFileSync(manifestPath, JSON.stringify(names.sort(), null, 2) + '\n');
  const gone = path.join(out, 'packages/contracts/api/stubs/gone.200.json');
  fs.writeFileSync(gone, '{}\n');
  // --check は obsolete として報告
  assert.throws(() => genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out, check: true }), /obsolete/);
  // 生成は削除する
  const r = genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out });
  assert.ok(!fs.existsSync(gone), 'stub listed in manifest but no longer generated must be removed');
  assert.ok(r.removed.includes('packages/contracts/api/stubs/gone.200.json'));
});

test('provider を別ティアへ移すと旧テストを orphan として削除・報告する (Finding 3)', () => {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  const out = outRoot();
  genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out });
  const oldTest = 'apps/backend-api/test/contract/createLoan.test.ts';
  assert.ok(fs.existsSync(path.join(out, oldTest)));
  // provider ティアの dir を apps/backend-api2 へ移した config を作る
  const moved = path.join(out, 'config-moved.yaml');
  fs.writeFileSync(moved, fs.readFileSync(CONFIG, 'utf8').replace('dir: apps/backend-api\n', 'dir: apps/backend-api2\n'));
  // --check は旧ティア配下のテストを obsolete 報告
  assert.throws(() => genContractTests.run(contractsDir, { configPath: moved, outRoot: out, check: true }), /obsolete/);
  // 生成すると旧テストを削除し、新ティアへ出力する
  const r = genContractTests.run(contractsDir, { configPath: moved, outRoot: out });
  assert.ok(!fs.existsSync(path.join(out, oldTest)), 'old provider test must be removed');
  assert.ok(r.removed.includes(oldTest), 'removed should list old provider test');
  assert.ok(fs.existsSync(path.join(out, 'apps/backend-api2/test/contract/createLoan.test.ts')), 'new provider dir must be generated');
});

test('--uc は slice が無いと exit 2 相当のエラー', () => {
  const { contractsDir } = freshContracts();
  // compileContracts を実行しない → slice 無し
  const out = outRoot();
  try {
    genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out, uc: 'loan-register' });
    assert.fail('should throw');
  } catch (e) {
    assert.match(e.message, /contract slice not found/);
    assert.equal(e.exitCode, 2);
  }
});

test('--uc は bundle が古いと stale として throw する', () => {
  const { contractsDir } = freshContracts();
  compileContracts.run(contractsDir);
  // source を書き換えて generated を古くする
  const openapiPath = path.join(contractsDir, 'openapi', 'openapi.yaml');
  fs.writeFileSync(openapiPath, fs.readFileSync(openapiPath, 'utf8').replace('title: Library', 'title: Library v2'));
  const out = outRoot();
  assert.throws(
    () => genContractTests.run(contractsDir, { configPath: CONFIG, outRoot: out, uc: 'loan-register' }),
    /stale/,
  );
});
