// generated by distillery2 — do not edit
// biome-ignore-all format: generated (do not edit)
// biome-ignore-all lint: generated (do not edit)
// basis: contracts@f75677ff4b363c1afb894735e67de64f767a55ea
// distillery2-owner: d2-contract/genContractTests
export interface OperationRoute {
  method: string;
  path: string;
}

export const operations = {
  registerLoan: { method: "POST", path: "/loans" },
  registerReturn: { method: "POST", path: "/returns" },
} as const satisfies Record<string, OperationRoute>;

export type OperationId = keyof typeof operations;
