// generated by distillery2 — do not edit
// biome-ignore-all format: generated (do not edit)
// biome-ignore-all lint: generated (do not edit)
// basis: contracts@78204463d891ad94ca15a2cc757ae230a2289d94
// distillery2-owner: d2-contract/genContractTests
export interface OperationRoute {
  method: string;
  path: string;
}

export const operations = {
  registerLoan: { method: "POST", path: "/loans" },
} as const satisfies Record<string, OperationRoute>;

export type OperationId = keyof typeof operations;
