// generated by distillery2 — do not edit
// biome-ignore-all format: generated (do not edit)
// biome-ignore-all lint: generated (do not edit)
// basis: contracts@f75677ff4b363c1afb894735e67de64f767a55ea
// distillery2-owner: d2-contract/genContractTests
export type BookId = string;

export type BookStatus = "available" | "on_loan" | "awaiting_pickup";

export interface FieldError {
  field: string;
  message: string;
}

export interface Loan {
  bookId: BookId;
  dueDate: string;
  loanId: LoanId;
  loanedOn: string;
  patronNumber: PatronNumber;
  reservationId: string | null;
  returnedOn: string | null;
  status: LoanStatus;
}

export type LoanId = string;

export interface LoanRegistration {
  bookStatus: BookStatus;
  loan: Loan;
}

export type LoanStatus = "on_loan" | "returned" | "overdue";

export type MediaType = "paper" | "ebook";

export type NotificationId = string;

export type NotificationType = "return_notice" | "reminder" | "overdue_notice";

export interface PageMeta {
  limit: number;
  offset: number;
  total: number;
}

export type PatronNumber = string;

export interface Problem {
  code: ProblemCode;
  detail?: string;
  errors?: FieldError[];
  instance?: string;
  status: number;
  title: string;
  type: string;
}

export type ProblemCode = "validation_error" | "unauthorized" | "forbidden" | "not_found" | "business_rule_violation" | "idempotency_key_conflict" | "internal_error" | "book_on_loan" | "not_first_in_reservation_queue" | "patron_not_registered" | "no_active_loan";

export interface RegisterLoanRequest {
  bookId: BookId;
  patronNumber: PatronNumber;
}

export interface RegisterReturnRequest {
  bookId: BookId;
}

export type ReportType = "inventory_status" | "popular_books" | "loan_statistics";

export type ReservationId = string;

export type ReservationStatus = "waiting" | "notified" | "completed" | "cancelled";

export interface ReturnRegistration {
  bookStatus: BookStatus;
  loan: Loan;
}

export type Role = "librarian" | "patron";
