// generated by distillery2 — do not edit
// basis: contracts@ef34ed2860a1541965f490aa00ad42e21db3d1d7
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PGlite } from '@electric-sql/pglite';

const here = dirname(fileURLToPath(import.meta.url));
const migration = readFileSync(join(here, '..', '..', 'migrations', '0001_schema.sql'), 'utf8');
const expected = [
  {
    "columns": [
      {
        "name": "book_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "isbn",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "title",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "author",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "publisher",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "genre",
        "nullable": true,
        "type": "books_genre"
      },
      {
        "name": "media_type",
        "nullable": false,
        "type": "books_media_type"
      },
      {
        "name": "registered_on",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "deleted_at",
        "nullable": true,
        "type": "timestamptz"
      },
      {
        "name": "created_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "books",
    "primary_key": [
      "book_id"
    ]
  },
  {
    "columns": [
      {
        "name": "copy_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "book_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "status",
        "nullable": false,
        "type": "copies_status"
      },
      {
        "name": "acquired_on",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "version",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "copies",
    "primary_key": [
      "copy_id"
    ]
  },
  {
    "columns": [
      {
        "name": "event_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "copy_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "sequence",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "event_type",
        "nullable": false,
        "type": "copy_events_event_type"
      },
      {
        "name": "from_status",
        "nullable": true,
        "type": "copy_events_from_status"
      },
      {
        "name": "to_status",
        "nullable": false,
        "type": "copy_events_to_status"
      },
      {
        "name": "occurred_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "actor_librarian_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "payload",
        "nullable": true,
        "type": "text"
      }
    ],
    "name": "copy_events",
    "primary_key": [
      "event_id"
    ]
  },
  {
    "columns": [
      {
        "name": "librarian_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "staff_id",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "name",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "login_id",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "idp_subject",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "deleted_at",
        "nullable": true,
        "type": "timestamptz"
      },
      {
        "name": "created_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "librarians",
    "primary_key": [
      "librarian_id"
    ]
  },
  {
    "columns": [
      {
        "name": "event_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "loan_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "sequence",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "event_type",
        "nullable": false,
        "type": "loan_events_event_type"
      },
      {
        "name": "from_status",
        "nullable": true,
        "type": "loan_events_from_status"
      },
      {
        "name": "to_status",
        "nullable": false,
        "type": "loan_events_to_status"
      },
      {
        "name": "occurred_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "actor_librarian_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "payload",
        "nullable": true,
        "type": "text"
      }
    ],
    "name": "loan_events",
    "primary_key": [
      "event_id"
    ]
  },
  {
    "columns": [
      {
        "name": "loan_rule_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "loan_period_days",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "reminder_days_before",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "effective_from",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "created_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "loan_rules",
    "primary_key": [
      "loan_rule_id"
    ]
  },
  {
    "columns": [
      {
        "name": "loan_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "patron_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "copy_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "loan_rule_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "loaned_on",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "due_on",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "returned_on",
        "nullable": true,
        "type": "date"
      },
      {
        "name": "status",
        "nullable": false,
        "type": "loans_status"
      },
      {
        "name": "loaned_by_librarian_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "returned_by_librarian_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "version",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "loans",
    "primary_key": [
      "loan_id"
    ]
  },
  {
    "columns": [
      {
        "name": "event_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "notification_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "sequence",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "event_type",
        "nullable": false,
        "type": "notification_events_event_type"
      },
      {
        "name": "from_status",
        "nullable": true,
        "type": "notification_events_from_status"
      },
      {
        "name": "to_status",
        "nullable": false,
        "type": "notification_events_to_status"
      },
      {
        "name": "occurred_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "payload",
        "nullable": true,
        "type": "text"
      }
    ],
    "name": "notification_events",
    "primary_key": [
      "event_id"
    ]
  },
  {
    "columns": [
      {
        "name": "notification_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "notification_type",
        "nullable": false,
        "type": "notifications_notification_type"
      },
      {
        "name": "target_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "loan_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "reservation_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "patron_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "recipient_email_encrypted",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "scheduled_on",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "status",
        "nullable": false,
        "type": "notifications_status"
      },
      {
        "name": "sent_at",
        "nullable": true,
        "type": "timestamptz"
      },
      {
        "name": "attempt_count",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "last_error",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "version",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "created_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "notifications",
    "primary_key": [
      "notification_id"
    ]
  },
  {
    "columns": [
      {
        "name": "patron_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "patron_number",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "name_encrypted",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "email_encrypted",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "login_id",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "idp_subject",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "registered_on",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "deleted_at",
        "nullable": true,
        "type": "timestamptz"
      },
      {
        "name": "created_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "patrons",
    "primary_key": [
      "patron_id"
    ]
  },
  {
    "columns": [
      {
        "name": "event_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "reservation_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "sequence",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "event_type",
        "nullable": false,
        "type": "reservation_events_event_type"
      },
      {
        "name": "from_status",
        "nullable": true,
        "type": "reservation_events_from_status"
      },
      {
        "name": "to_status",
        "nullable": false,
        "type": "reservation_events_to_status"
      },
      {
        "name": "occurred_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "actor_librarian_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "payload",
        "nullable": true,
        "type": "text"
      }
    ],
    "name": "reservation_events",
    "primary_key": [
      "event_id"
    ]
  },
  {
    "columns": [
      {
        "name": "reservation_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "patron_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "book_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "held_copy_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "reserved_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "queue_position",
        "nullable": true,
        "type": "integer"
      },
      {
        "name": "status",
        "nullable": false,
        "type": "reservations_status"
      },
      {
        "name": "hold_started_on",
        "nullable": true,
        "type": "date"
      },
      {
        "name": "active_key",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "version",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "reservations",
    "primary_key": [
      "reservation_id"
    ]
  }
];

let db: PGlite;
beforeAll(async () => { db = new PGlite(); await db.exec(migration); });
afterAll(async () => { await db.close(); });

describe('db schema contract', () => {
  for (const table of expected) {
    it(`${table.name} matches the contract bundle`, async () => {
      const cols = await db.query<{ column_name: string; data_type: string; udt_name: string; is_nullable: string }>(
        `SELECT column_name, data_type, udt_name, is_nullable FROM information_schema.columns WHERE table_name = $1`, [table.name]);
      const actual = new Map(cols.rows.map(r => [r.column_name, r]));
      expect(new Set(actual.keys())).toEqual(new Set(table.columns.map(c => c.name)));
      for (const col of table.columns) {
        const got = actual.get(col.name)!;
        const gotType = got.data_type === 'USER-DEFINED' ? got.udt_name : got.data_type;
        expect(normalize(gotType)).toBe(normalize(col.type));
        expect(got.is_nullable === 'YES').toBe(col.nullable);
      }
      const pk = await db.query<{ column_name: string }>(
        `SELECT kcu.column_name FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu ON kcu.constraint_name = tc.constraint_name
         WHERE tc.table_name = $1 AND tc.constraint_type = 'PRIMARY KEY'`, [table.name]);
      expect(new Set(pk.rows.map(r => r.column_name))).toEqual(new Set(table.primary_key));
    });
  }
});

function normalize(t: string): string {
  const map: Record<string, string> = { 'character varying': 'text', 'timestamp with time zone': 'timestamptz', 'timestamp without time zone': 'timestamp' };
  return map[t] ?? t;
}
