// generated by distillery2 — do not edit
// biome-ignore-all format: generated (do not edit)
// biome-ignore-all lint: generated (do not edit)
// basis: contracts@78204463d891ad94ca15a2cc757ae230a2289d94
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PGlite } from '@electric-sql/pglite';

const here = dirname(fileURLToPath(import.meta.url));
const migration = readFileSync(join(here, '..', '..', 'migrations', '0001_schema.sql'), 'utf8');
const expected = [
  {
    "columns": [
      {
        "name": "audit_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "actor_subject",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "actor_role",
        "nullable": false,
        "type": "audit_logs_actor_role"
      },
      {
        "name": "action",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "target_type",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "target_id",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "occurred_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "audit_logs",
    "primary_key": [
      "audit_id"
    ]
  },
  {
    "columns": [
      {
        "name": "event_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "book_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "sequence",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "event_type",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "payload",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "actor_subject",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "occurred_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "book_events",
    "primary_key": [
      "event_id"
    ]
  },
  {
    "columns": [
      {
        "name": "book_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "title",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "author",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "isbn",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "publisher",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "genre",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "media_type",
        "nullable": false,
        "type": "books_media_type"
      },
      {
        "name": "status",
        "nullable": false,
        "type": "books_status"
      },
      {
        "name": "registered_on",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "deleted_on",
        "nullable": true,
        "type": "date"
      },
      {
        "name": "version",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "books",
    "primary_key": [
      "book_id"
    ]
  },
  {
    "columns": [
      {
        "name": "idempotency_key",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "principal_subject",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "operation_id",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "request_hash",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "response_status",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "response_body",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "created_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "idempotency_keys",
    "primary_key": [
      "idempotency_key",
      "principal_subject",
      "operation_id"
    ]
  },
  {
    "columns": [
      {
        "name": "event_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "loan_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "sequence",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "event_type",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "payload",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "actor_subject",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "occurred_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "loan_events",
    "primary_key": [
      "event_id"
    ]
  },
  {
    "columns": [
      {
        "name": "loan_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "patron_number",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "book_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "reservation_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "loaned_on",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "due_date",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "returned_on",
        "nullable": true,
        "type": "date"
      },
      {
        "name": "status",
        "nullable": false,
        "type": "loans_status"
      },
      {
        "name": "version",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "loans",
    "primary_key": [
      "loan_id"
    ]
  },
  {
    "columns": [
      {
        "name": "notification_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "attempt_no",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "result",
        "nullable": false,
        "type": "notification_attempts_result"
      },
      {
        "name": "error_message",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "attempted_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "notification_attempts",
    "primary_key": [
      "notification_id",
      "attempt_no"
    ]
  },
  {
    "columns": [
      {
        "name": "notification_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "patron_number",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "email_encrypted",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "loan_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "reservation_id",
        "nullable": true,
        "type": "uuid"
      },
      {
        "name": "notification_type",
        "nullable": false,
        "type": "notifications_notification_type"
      },
      {
        "name": "requested_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "notifications",
    "primary_key": [
      "notification_id"
    ]
  },
  {
    "columns": [
      {
        "name": "patron_number",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "idp_subject",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "name",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "email_encrypted",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "registered_on",
        "nullable": false,
        "type": "date"
      },
      {
        "name": "deleted_on",
        "nullable": true,
        "type": "date"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "patrons",
    "primary_key": [
      "patron_number"
    ]
  },
  {
    "columns": [
      {
        "name": "event_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "reservation_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "sequence",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "event_type",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "payload",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "actor_subject",
        "nullable": true,
        "type": "text"
      },
      {
        "name": "occurred_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "reservation_events",
    "primary_key": [
      "event_id"
    ]
  },
  {
    "columns": [
      {
        "name": "reservation_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "patron_number",
        "nullable": false,
        "type": "text"
      },
      {
        "name": "book_id",
        "nullable": false,
        "type": "uuid"
      },
      {
        "name": "received_at",
        "nullable": false,
        "type": "timestamptz"
      },
      {
        "name": "queue_position",
        "nullable": true,
        "type": "integer"
      },
      {
        "name": "status",
        "nullable": false,
        "type": "reservations_status"
      },
      {
        "name": "notified_at",
        "nullable": true,
        "type": "timestamptz"
      },
      {
        "name": "completed_at",
        "nullable": true,
        "type": "timestamptz"
      },
      {
        "name": "cancelled_at",
        "nullable": true,
        "type": "timestamptz"
      },
      {
        "name": "version",
        "nullable": false,
        "type": "integer"
      },
      {
        "name": "updated_at",
        "nullable": false,
        "type": "timestamptz"
      }
    ],
    "name": "reservations",
    "primary_key": [
      "reservation_id"
    ]
  }
];

let db: PGlite;
beforeAll(async () => { db = new PGlite(); await db.exec(migration); });
afterAll(async () => { await db.close(); });

describe('db schema contract', () => {
  for (const table of expected) {
    it(`${table.name} matches the contract bundle`, async () => {
      const cols = await db.query<{ column_name: string; data_type: string; udt_name: string; is_nullable: string }>(
        'SELECT column_name, data_type, udt_name, is_nullable FROM information_schema.columns WHERE table_name = $1', [table.name]);
      const actual = new Map(cols.rows.map(r => [r.column_name, r]));
      expect(new Set(actual.keys())).toEqual(new Set(table.columns.map(c => c.name)));
      for (const col of table.columns) {
        const got = actual.get(col.name)!;
        const gotType = got.data_type === 'USER-DEFINED' ? got.udt_name : got.data_type;
        expect(normalize(gotType)).toBe(normalize(col.type));
        expect(got.is_nullable === 'YES').toBe(col.nullable);
      }
      const pk = await db.query<{ column_name: string }>(
        `SELECT kcu.column_name FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu ON kcu.constraint_name = tc.constraint_name
         WHERE tc.table_name = $1 AND tc.constraint_type = 'PRIMARY KEY'`, [table.name]);
      expect(new Set(pk.rows.map(r => r.column_name))).toEqual(new Set(table.primary_key));
    });
  }
});

function normalize(t: string): string {
  const map: Record<string, string> = { 'character varying': 'text', 'timestamp with time zone': 'timestamptz', 'timestamp without time zone': 'timestamp' };
  return map[t] ?? t;
}
