/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 書籍レスポンス
*/
export class BookResponse {
    /**
    * 書籍ID
    */
    'id': string;
    /**
    * タイトル
    */
    'title': string;
    /**
    * 著者
    */
    'author': string;
    /**
    * ISBN-13
    */
    'isbn': string;
    /**
    * 出版社
    */
    'publisher': string;
    /**
    * ジャンル
    */
    'genre': string;
    /**
    * 資料種別
    */
    'materialType': string;
    /**
    * 配架場所
    */
    'location'?: string;
    /**
    * 貸出状態
    */
    'status': BookResponse.StatusEnum;
    /**
    * 登録日時
    */
    'createdAt': Date;
    /**
    * 更新日時
    */
    'updatedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string"
        },
        {
            "name": "isbn",
            "baseName": "isbn",
            "type": "string"
        },
        {
            "name": "publisher",
            "baseName": "publisher",
            "type": "string"
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "string"
        },
        {
            "name": "materialType",
            "baseName": "material_type",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BookResponse.StatusEnum"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return BookResponse.attributeTypeMap;
    }
}

export namespace BookResponse {
    export enum StatusEnum {
        Available = <any> 'available',
        OnLoan = <any> 'on_loan',
        Overdue = <any> 'overdue'
    }
}
