/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 書籍登録リクエスト
*/
export class CreateBookRequest {
    /**
    * 書籍タイトル
    */
    'title': string;
    /**
    * 著者名
    */
    'author': string;
    /**
    * ISBN-13形式
    */
    'isbn': string;
    /**
    * 出版社名
    */
    'publisher': string;
    /**
    * 書籍ジャンル
    */
    'genre': CreateBookRequest.GenreEnum;
    /**
    * 資料種別
    */
    'materialType': CreateBookRequest.MaterialTypeEnum;
    /**
    * 配架場所（紙書籍の場合必須）
    */
    'location'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string"
        },
        {
            "name": "isbn",
            "baseName": "isbn",
            "type": "string"
        },
        {
            "name": "publisher",
            "baseName": "publisher",
            "type": "string"
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "CreateBookRequest.GenreEnum"
        },
        {
            "name": "materialType",
            "baseName": "material_type",
            "type": "CreateBookRequest.MaterialTypeEnum"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateBookRequest.attributeTypeMap;
    }
}

export namespace CreateBookRequest {
    export enum GenreEnum {
         = <any> '文学',
        2 = <any> '理工',
        3 = <any> '児童書',
        4 = <any> '社会科学',
        5 = <any> '自然科学',
        6 = <any> '芸術',
        7 = <any> 'その他'
    }
    export enum MaterialTypeEnum {
         = <any> '紙書籍',
        2 = <any> '電子書籍'
    }
}
