/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 貸出リクエスト
*/
export class CreateLoanRequest {
    /**
    * 貸出対象の書籍ID
    */
    'bookId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bookId",
            "baseName": "book_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateLoanRequest.attributeTypeMap;
    }
}

