/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DetectOverdue200Response {
    /**
    * 新規延滞検出件数
    */
    'detectedCount': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "detectedCount",
            "baseName": "detected_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DetectOverdue200Response.attributeTypeMap;
    }
}

