/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InventoryResponseByGenreInner } from './inventoryResponseByGenreInner';

/**
* 在庫状況レスポンス
*/
export class InventoryResponse {
    /**
    * 総蔵書数
    */
    'totalBooks': number;
    /**
    * 在庫あり数
    */
    'availableCount': number;
    /**
    * 貸出中数
    */
    'onLoanCount': number;
    /**
    * 延滞中数
    */
    'overdueCount': number;
    /**
    * ジャンル別蔵書数
    */
    'byGenre': Array<InventoryResponseByGenreInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalBooks",
            "baseName": "total_books",
            "type": "number"
        },
        {
            "name": "availableCount",
            "baseName": "available_count",
            "type": "number"
        },
        {
            "name": "onLoanCount",
            "baseName": "on_loan_count",
            "type": "number"
        },
        {
            "name": "overdueCount",
            "baseName": "overdue_count",
            "type": "number"
        },
        {
            "name": "byGenre",
            "baseName": "by_genre",
            "type": "Array<InventoryResponseByGenreInner>"
        }    ];

    static getAttributeTypeMap() {
        return InventoryResponse.attributeTypeMap;
    }
}

