/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 貸出レスポンス
*/
export class LoanResponse {
    /**
    * 貸出ID
    */
    'id': string;
    /**
    * 書籍ID
    */
    'bookId': string;
    /**
    * 書籍タイトル
    */
    'bookTitle': string;
    /**
    * 利用者ID
    */
    'userId': string;
    /**
    * 貸出日
    */
    'loanDate': string;
    /**
    * 返却期限
    */
    'dueDate': string;
    /**
    * 返却日
    */
    'returnDate'?: string;
    /**
    * 延滞フラグ
    */
    'isOverdue': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "bookId",
            "baseName": "book_id",
            "type": "string"
        },
        {
            "name": "bookTitle",
            "baseName": "book_title",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        },
        {
            "name": "loanDate",
            "baseName": "loan_date",
            "type": "string"
        },
        {
            "name": "dueDate",
            "baseName": "due_date",
            "type": "string"
        },
        {
            "name": "returnDate",
            "baseName": "return_date",
            "type": "string"
        },
        {
            "name": "isOverdue",
            "baseName": "is_overdue",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return LoanResponse.attributeTypeMap;
    }
}

