/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReservationResponse } from './reservationResponse';

/**
* ページネーション付き予約一覧
*/
export class PaginatedReservationListResponse {
    'items': Array<ReservationResponse>;
    /**
    * 全件数
    */
    'total': number;
    /**
    * 現在ページ
    */
    'page': number;
    /**
    * 1ページあたり件数
    */
    'perPage': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ReservationResponse>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "perPage",
            "baseName": "per_page",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PaginatedReservationListResponse.attributeTypeMap;
    }
}

