/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* RFC 7807 Problem Details エラーレスポンス
*/
export class ProblemDetails {
    /**
    * エラータイプURI
    */
    'type': string;
    /**
    * エラータイトル
    */
    'title': string;
    /**
    * HTTPステータスコード
    */
    'status': number;
    /**
    * エラー詳細メッセージ
    */
    'detail'?: string;
    /**
    * エラー発生インスタンスURI
    */
    'instance'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string"
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProblemDetails.attributeTypeMap;
    }
}

