/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 予約レスポンス
*/
export class ReservationResponse {
    /**
    * 予約ID
    */
    'id': string;
    /**
    * 書籍ID
    */
    'bookId': string;
    /**
    * 書籍タイトル
    */
    'bookTitle': string;
    /**
    * 利用者ID
    */
    'userId': string;
    /**
    * 予約日時
    */
    'reservedAt': Date;
    /**
    * 予約順位
    */
    'queuePosition': number;
    /**
    * 予約状態
    */
    'status': ReservationResponse.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "bookId",
            "baseName": "book_id",
            "type": "string"
        },
        {
            "name": "bookTitle",
            "baseName": "book_title",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        },
        {
            "name": "reservedAt",
            "baseName": "reserved_at",
            "type": "Date"
        },
        {
            "name": "queuePosition",
            "baseName": "queue_position",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ReservationResponse.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return ReservationResponse.attributeTypeMap;
    }
}

export namespace ReservationResponse {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Reserved = <any> 'reserved',
        Cancelled = <any> 'cancelled'
    }
}
