/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 返却レスポンス
*/
export class ReturnLoanResponse {
    /**
    * 貸出ID
    */
    'id': string;
    /**
    * 書籍タイトル
    */
    'bookTitle': string;
    /**
    * 返却日
    */
    'returnDate': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "bookTitle",
            "baseName": "book_title",
            "type": "string"
        },
        {
            "name": "returnDate",
            "baseName": "return_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnLoanResponse.attributeTypeMap;
    }
}

