/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StatsResponseByGenreInner } from './statsResponseByGenreInner';
import { StatsResponseMonthlyTrendInner } from './statsResponseMonthlyTrendInner';
import { StatsResponsePopularBooksInner } from './statsResponsePopularBooksInner';

/**
* 統計レスポンス
*/
export class StatsResponse {
    /**
    * 集計期間
    */
    'period': string;
    /**
    * 期間内総貸出回数
    */
    'totalLoans': number;
    /**
    * 人気書籍ランキング
    */
    'popularBooks': Array<StatsResponsePopularBooksInner>;
    /**
    * 月別貸出推移
    */
    'monthlyTrend': Array<StatsResponseMonthlyTrendInner>;
    /**
    * ジャンル別貸出構成
    */
    'byGenre'?: Array<StatsResponseByGenreInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "period",
            "baseName": "period",
            "type": "string"
        },
        {
            "name": "totalLoans",
            "baseName": "total_loans",
            "type": "number"
        },
        {
            "name": "popularBooks",
            "baseName": "popular_books",
            "type": "Array<StatsResponsePopularBooksInner>"
        },
        {
            "name": "monthlyTrend",
            "baseName": "monthly_trend",
            "type": "Array<StatsResponseMonthlyTrendInner>"
        },
        {
            "name": "byGenre",
            "baseName": "by_genre",
            "type": "Array<StatsResponseByGenreInner>"
        }    ];

    static getAttributeTypeMap() {
        return StatsResponse.attributeTypeMap;
    }
}

