/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 利用者更新リクエスト
*/
export class UpdateUserRequest {
    /**
    * 氏名
    */
    'name': string;
    /**
    * 連絡先
    */
    'contact'?: string;
    /**
    * メールアドレス
    */
    'email': string;
    /**
    * 利用者種別
    */
    'userType': UpdateUserRequest.UserTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "contact",
            "baseName": "contact",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "userType",
            "baseName": "user_type",
            "type": "UpdateUserRequest.UserTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return UpdateUserRequest.attributeTypeMap;
    }
}

export namespace UpdateUserRequest {
    export enum UserTypeEnum {
         = <any> '一般',
        2 = <any> '学生',
        3 = <any> '児童'
    }
}
