/**
 * LibraShelf API
 * 図書館蔵書管理システムの REST API。蔵書管理、貸出管理、予約管理、利用者管理、統計の各業務を提供する。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 利用者レスポンス
*/
export class UserResponse {
    /**
    * 利用者ID
    */
    'id': string;
    /**
    * 利用者番号
    */
    'userNumber': string;
    /**
    * 氏名
    */
    'name': string;
    /**
    * 連絡先
    */
    'contact'?: string;
    /**
    * メールアドレス
    */
    'email': string;
    /**
    * 利用者種別
    */
    'userType': string;
    /**
    * 登録日
    */
    'registeredAt': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "userNumber",
            "baseName": "user_number",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "contact",
            "baseName": "contact",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "userType",
            "baseName": "user_type",
            "type": "string"
        },
        {
            "name": "registeredAt",
            "baseName": "registered_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserResponse.attributeTypeMap;
    }
}

