// generated by distillery2 — do not edit
// basis: contracts@f5b408fe4a589b86fe4205021c086b01792e7604

export type BookEventsRow = {
  event_id: string;
  book_id: string;
  book_version: number;
  event_type: string;
  payload: string;
  actor_id: string;
  occurred_at: string;
};
export const BOOK_EVENTS_TABLE = 'book_events' as const;
export const BOOK_EVENTS_COLUMNS = { event_id: 'event_id', book_id: 'book_id', book_version: 'book_version', event_type: 'event_type', payload: 'payload', actor_id: 'actor_id', occurred_at: 'occurred_at' } as const;

export type BooksRow = {
  book_id: string;
  isbn: string | null;
  title: string;
  author: string;
  publisher: string | null;
  genre: 'literature' | 'history' | 'natural_science' | 'social_science' | 'art' | 'engineering' | 'children' | 'reference';
  media_type: 'paper' | 'electronic';
  status: 'available' | 'on_loan' | 'on_hold' | 'deleted';
  version: number;
  registered_on: string;
  updated_at: string;
};
export const BOOKS_TABLE = 'books' as const;
export const BOOKS_COLUMNS = { book_id: 'book_id', isbn: 'isbn', title: 'title', author: 'author', publisher: 'publisher', genre: 'genre', media_type: 'media_type', status: 'status', version: 'version', registered_on: 'registered_on', updated_at: 'updated_at' } as const;

export type IdempotencyKeysRow = {
  actor_id: string;
  idempotency_key: string;
  request_hash: string;
  response_status: number;
  response_body: string;
  created_at: string;
  expires_at: string;
};
export const IDEMPOTENCY_KEYS_TABLE = 'idempotency_keys' as const;
export const IDEMPOTENCY_KEYS_COLUMNS = { actor_id: 'actor_id', idempotency_key: 'idempotency_key', request_hash: 'request_hash', response_status: 'response_status', response_body: 'response_body', created_at: 'created_at', expires_at: 'expires_at' } as const;

export type JobRunsRow = {
  job_type: string;
  target_date: string;
  status: 'running' | 'succeeded' | 'failed';
  started_at: string;
  finished_at: string | null;
  last_error: string | null;
};
export const JOB_RUNS_TABLE = 'job_runs' as const;
export const JOB_RUNS_COLUMNS = { job_type: 'job_type', target_date: 'target_date', status: 'status', started_at: 'started_at', finished_at: 'finished_at', last_error: 'last_error' } as const;

export type LoanEventsRow = {
  event_id: string;
  loan_id: string;
  loan_version: number;
  event_type: string;
  payload: string;
  actor_id: string;
  occurred_at: string;
};
export const LOAN_EVENTS_TABLE = 'loan_events' as const;
export const LOAN_EVENTS_COLUMNS = { event_id: 'event_id', loan_id: 'loan_id', loan_version: 'loan_version', event_type: 'event_type', payload: 'payload', actor_id: 'actor_id', occurred_at: 'occurred_at' } as const;

export type LoansRow = {
  loan_id: string;
  book_id: string;
  patron_number: string;
  loaned_on: string;
  loan_period_days: number;
  due_on: string;
  returned_on: string | null;
  status: 'on_loan' | 'overdue' | 'returned';
  version: number;
  created_at: string;
  updated_at: string;
};
export const LOANS_TABLE = 'loans' as const;
export const LOANS_COLUMNS = { loan_id: 'loan_id', book_id: 'book_id', patron_number: 'patron_number', loaned_on: 'loaned_on', loan_period_days: 'loan_period_days', due_on: 'due_on', returned_on: 'returned_on', status: 'status', version: 'version', created_at: 'created_at', updated_at: 'updated_at' } as const;

export type NotificationEventsRow = {
  event_id: string;
  notification_id: string;
  notification_version: number;
  event_type: string;
  payload: string;
  actor_id: string;
  occurred_at: string;
};
export const NOTIFICATION_EVENTS_TABLE = 'notification_events' as const;
export const NOTIFICATION_EVENTS_COLUMNS = { event_id: 'event_id', notification_id: 'notification_id', notification_version: 'notification_version', event_type: 'event_type', payload: 'payload', actor_id: 'actor_id', occurred_at: 'occurred_at' } as const;

export type NotificationsRow = {
  notification_id: string;
  patron_number: string;
  type: 'hold_ready' | 'reminder' | 'overdue_notice';
  loan_id: string | null;
  reservation_id: string | null;
  reminder_timing: 'three_days_before' | 'one_day_before' | null;
  dedupe_key: string;
  recipient_email_encrypted: string;
  subject: string;
  body: string;
  status: 'pending' | 'sent' | 'failed';
  attempt_count: number;
  last_error: string | null;
  version: number;
  created_at: string;
  sent_at: string | null;
  updated_at: string;
};
export const NOTIFICATIONS_TABLE = 'notifications' as const;
export const NOTIFICATIONS_COLUMNS = { notification_id: 'notification_id', patron_number: 'patron_number', type: 'type', loan_id: 'loan_id', reservation_id: 'reservation_id', reminder_timing: 'reminder_timing', dedupe_key: 'dedupe_key', recipient_email_encrypted: 'recipient_email_encrypted', subject: 'subject', body: 'body', status: 'status', attempt_count: 'attempt_count', last_error: 'last_error', version: 'version', created_at: 'created_at', sent_at: 'sent_at', updated_at: 'updated_at' } as const;

export type PatronEventsRow = {
  event_id: string;
  patron_number: string;
  patron_version: number;
  event_type: string;
  payload: string;
  actor_id: string;
  occurred_at: string;
};
export const PATRON_EVENTS_TABLE = 'patron_events' as const;
export const PATRON_EVENTS_COLUMNS = { event_id: 'event_id', patron_number: 'patron_number', patron_version: 'patron_version', event_type: 'event_type', payload: 'payload', actor_id: 'actor_id', occurred_at: 'occurred_at' } as const;

export type PatronsRow = {
  patron_number: string;
  idp_subject: string | null;
  full_name_encrypted: string;
  email_encrypted: string;
  phone_encrypted: string | null;
  address_encrypted: string | null;
  category: 'general' | 'child' | 'student';
  status: 'active' | 'deleted';
  version: number;
  registered_on: string;
  updated_at: string;
};
export const PATRONS_TABLE = 'patrons' as const;
export const PATRONS_COLUMNS = { patron_number: 'patron_number', idp_subject: 'idp_subject', full_name_encrypted: 'full_name_encrypted', email_encrypted: 'email_encrypted', phone_encrypted: 'phone_encrypted', address_encrypted: 'address_encrypted', category: 'category', status: 'status', version: 'version', registered_on: 'registered_on', updated_at: 'updated_at' } as const;

export type ReservationEventsRow = {
  event_id: string;
  reservation_id: string;
  reservation_version: number;
  event_type: string;
  payload: string;
  actor_id: string;
  occurred_at: string;
};
export const RESERVATION_EVENTS_TABLE = 'reservation_events' as const;
export const RESERVATION_EVENTS_COLUMNS = { event_id: 'event_id', reservation_id: 'reservation_id', reservation_version: 'reservation_version', event_type: 'event_type', payload: 'payload', actor_id: 'actor_id', occurred_at: 'occurred_at' } as const;

export type ReservationsRow = {
  reservation_id: string;
  book_id: string;
  patron_number: string;
  reserved_at: string;
  queue_position: number | null;
  status: 'waiting' | 'on_hold' | 'picked_up' | 'cancelled';
  hold_started_on: string | null;
  hold_expires_on: string | null;
  version: number;
  created_at: string;
  updated_at: string;
};
export const RESERVATIONS_TABLE = 'reservations' as const;
export const RESERVATIONS_COLUMNS = { reservation_id: 'reservation_id', book_id: 'book_id', patron_number: 'patron_number', reserved_at: 'reserved_at', queue_position: 'queue_position', status: 'status', hold_started_on: 'hold_started_on', hold_expires_on: 'hold_expires_on', version: 'version', created_at: 'created_at', updated_at: 'updated_at' } as const;
