// generated by distillery2 — do not edit
// basis: contracts@ef34ed2860a1541965f490aa00ad42e21db3d1d7

export type BooksRow = {
  book_id: string;
  isbn: string | null;
  title: string;
  author: string | null;
  publisher: string | null;
  genre: 'literature' | 'history' | 'social_science' | 'natural_science' | 'technology' | 'arts' | 'children' | 'other' | null;
  media_type: 'paper' | 'electronic';
  registered_on: string;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
};
export const BOOKS_TABLE = 'books' as const;
export const BOOKS_COLUMNS = { book_id: 'book_id', isbn: 'isbn', title: 'title', author: 'author', publisher: 'publisher', genre: 'genre', media_type: 'media_type', registered_on: 'registered_on', deleted_at: 'deleted_at', created_at: 'created_at', updated_at: 'updated_at' } as const;

export type CopiesRow = {
  copy_id: string;
  book_id: string;
  status: 'available' | 'on_loan' | 'on_hold' | 'withdrawn';
  acquired_on: string;
  version: number;
  updated_at: string;
};
export const COPIES_TABLE = 'copies' as const;
export const COPIES_COLUMNS = { copy_id: 'copy_id', book_id: 'book_id', status: 'status', acquired_on: 'acquired_on', version: 'version', updated_at: 'updated_at' } as const;

export type CopyEventsRow = {
  event_id: string;
  copy_id: string;
  sequence: number;
  event_type: 'registered' | 'loaned' | 'returned_to_shelf' | 'held' | 'withdrawn';
  from_status: 'available' | 'on_loan' | 'on_hold' | 'withdrawn' | null;
  to_status: 'available' | 'on_loan' | 'on_hold' | 'withdrawn';
  occurred_at: string;
  actor_librarian_id: string | null;
  payload: string | null;
};
export const COPY_EVENTS_TABLE = 'copy_events' as const;
export const COPY_EVENTS_COLUMNS = { event_id: 'event_id', copy_id: 'copy_id', sequence: 'sequence', event_type: 'event_type', from_status: 'from_status', to_status: 'to_status', occurred_at: 'occurred_at', actor_librarian_id: 'actor_librarian_id', payload: 'payload' } as const;

export type LibrariansRow = {
  librarian_id: string;
  staff_id: string;
  name: string;
  login_id: string;
  idp_subject: string | null;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
};
export const LIBRARIANS_TABLE = 'librarians' as const;
export const LIBRARIANS_COLUMNS = { librarian_id: 'librarian_id', staff_id: 'staff_id', name: 'name', login_id: 'login_id', idp_subject: 'idp_subject', deleted_at: 'deleted_at', created_at: 'created_at', updated_at: 'updated_at' } as const;

export type LoanEventsRow = {
  event_id: string;
  loan_id: string;
  sequence: number;
  event_type: 'loaned' | 'marked_overdue' | 'returned';
  from_status: 'on_loan' | 'overdue' | 'returned' | null;
  to_status: 'on_loan' | 'overdue' | 'returned';
  occurred_at: string;
  actor_librarian_id: string | null;
  payload: string | null;
};
export const LOAN_EVENTS_TABLE = 'loan_events' as const;
export const LOAN_EVENTS_COLUMNS = { event_id: 'event_id', loan_id: 'loan_id', sequence: 'sequence', event_type: 'event_type', from_status: 'from_status', to_status: 'to_status', occurred_at: 'occurred_at', actor_librarian_id: 'actor_librarian_id', payload: 'payload' } as const;

export type LoanRulesRow = {
  loan_rule_id: string;
  loan_period_days: number;
  reminder_days_before: number;
  effective_from: string;
  created_at: string;
};
export const LOAN_RULES_TABLE = 'loan_rules' as const;
export const LOAN_RULES_COLUMNS = { loan_rule_id: 'loan_rule_id', loan_period_days: 'loan_period_days', reminder_days_before: 'reminder_days_before', effective_from: 'effective_from', created_at: 'created_at' } as const;

export type LoansRow = {
  loan_id: string;
  patron_id: string;
  copy_id: string;
  loan_rule_id: string;
  loaned_on: string;
  due_on: string;
  returned_on: string | null;
  status: 'on_loan' | 'overdue' | 'returned';
  loaned_by_librarian_id: string;
  returned_by_librarian_id: string | null;
  version: number;
  updated_at: string;
};
export const LOANS_TABLE = 'loans' as const;
export const LOANS_COLUMNS = { loan_id: 'loan_id', patron_id: 'patron_id', copy_id: 'copy_id', loan_rule_id: 'loan_rule_id', loaned_on: 'loaned_on', due_on: 'due_on', returned_on: 'returned_on', status: 'status', loaned_by_librarian_id: 'loaned_by_librarian_id', returned_by_librarian_id: 'returned_by_librarian_id', version: 'version', updated_at: 'updated_at' } as const;

export type NotificationEventsRow = {
  event_id: string;
  notification_id: string;
  sequence: number;
  event_type: 'queued' | 'sent' | 'send_failed';
  from_status: 'pending' | 'sent' | null;
  to_status: 'pending' | 'sent';
  occurred_at: string;
  payload: string | null;
};
export const NOTIFICATION_EVENTS_TABLE = 'notification_events' as const;
export const NOTIFICATION_EVENTS_COLUMNS = { event_id: 'event_id', notification_id: 'notification_id', sequence: 'sequence', event_type: 'event_type', from_status: 'from_status', to_status: 'to_status', occurred_at: 'occurred_at', payload: 'payload' } as const;

export type NotificationsRow = {
  notification_id: string;
  notification_type: 'reservation_ready' | 'due_reminder' | 'overdue_notice';
  target_id: string;
  loan_id: string | null;
  reservation_id: string | null;
  patron_id: string;
  recipient_email_encrypted: string;
  scheduled_on: string;
  status: 'pending' | 'sent';
  sent_at: string | null;
  attempt_count: number;
  last_error: string | null;
  version: number;
  created_at: string;
  updated_at: string;
};
export const NOTIFICATIONS_TABLE = 'notifications' as const;
export const NOTIFICATIONS_COLUMNS = { notification_id: 'notification_id', notification_type: 'notification_type', target_id: 'target_id', loan_id: 'loan_id', reservation_id: 'reservation_id', patron_id: 'patron_id', recipient_email_encrypted: 'recipient_email_encrypted', scheduled_on: 'scheduled_on', status: 'status', sent_at: 'sent_at', attempt_count: 'attempt_count', last_error: 'last_error', version: 'version', created_at: 'created_at', updated_at: 'updated_at' } as const;

export type PatronsRow = {
  patron_id: string;
  patron_number: string;
  name_encrypted: string;
  email_encrypted: string;
  login_id: string;
  idp_subject: string | null;
  registered_on: string;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
};
export const PATRONS_TABLE = 'patrons' as const;
export const PATRONS_COLUMNS = { patron_id: 'patron_id', patron_number: 'patron_number', name_encrypted: 'name_encrypted', email_encrypted: 'email_encrypted', login_id: 'login_id', idp_subject: 'idp_subject', registered_on: 'registered_on', deleted_at: 'deleted_at', created_at: 'created_at', updated_at: 'updated_at' } as const;

export type ReservationEventsRow = {
  event_id: string;
  reservation_id: string;
  sequence: number;
  event_type: 'reserved' | 'position_advanced' | 'held' | 'fulfilled' | 'cancelled';
  from_status: 'waiting' | 'on_hold' | 'fulfilled' | 'cancelled' | null;
  to_status: 'waiting' | 'on_hold' | 'fulfilled' | 'cancelled';
  occurred_at: string;
  actor_librarian_id: string | null;
  payload: string | null;
};
export const RESERVATION_EVENTS_TABLE = 'reservation_events' as const;
export const RESERVATION_EVENTS_COLUMNS = { event_id: 'event_id', reservation_id: 'reservation_id', sequence: 'sequence', event_type: 'event_type', from_status: 'from_status', to_status: 'to_status', occurred_at: 'occurred_at', actor_librarian_id: 'actor_librarian_id', payload: 'payload' } as const;

export type ReservationsRow = {
  reservation_id: string;
  patron_id: string;
  book_id: string;
  held_copy_id: string | null;
  reserved_at: string;
  queue_position: number | null;
  status: 'waiting' | 'on_hold' | 'fulfilled' | 'cancelled';
  hold_started_on: string | null;
  active_key: string | null;
  version: number;
  updated_at: string;
};
export const RESERVATIONS_TABLE = 'reservations' as const;
export const RESERVATIONS_COLUMNS = { reservation_id: 'reservation_id', patron_id: 'patron_id', book_id: 'book_id', held_copy_id: 'held_copy_id', reserved_at: 'reserved_at', queue_position: 'queue_position', status: 'status', hold_started_on: 'hold_started_on', active_key: 'active_key', version: 'version', updated_at: 'updated_at' } as const;
