// generated by distillery2 — do not edit
// basis: contracts@ef34ed2860a1541965f490aa00ad42e21db3d1d7
// distillery2-owner: d2-contract/genContractTests
import type { CreateLoanRequest, Loan, Problem } from './types';

export interface ClientOptions {
  /** ベース URL (末尾スラッシュ無し)。既定は同一オリジン。 */
  baseUrl?: string;
  /** 差し替え可能な fetch。テストで注入する。既定はグローバル fetch。 */
  fetch?: typeof fetch;
  /** 追加ヘッダ (認可トークン等)。 */
  headers?: Record<string, string>;
}

function withQuery(url: string, query?: Record<string, unknown>): string {
  if (!query) return url;
  const usp = new URLSearchParams();
  for (const [k, v] of Object.entries(query)) {
    if (v === undefined || v === null) continue;
    usp.append(k, String(v));
  }
  const qs = usp.toString();
  return qs ? `${url}?${qs}` : url;
}

async function parseBody(res: Response): Promise<unknown> {
  const text = await res.text();
  if (!text) return undefined;
  try { return JSON.parse(text); } catch { return text; }
}

export interface CreateLoanArgs {
  body: CreateLoanRequest;
}

export type CreateLoanResult =
  | { status: 201; data: Loan }
  | { status: 400; data: Problem }
  | { status: 404; data: Problem }
  | { status: 409; data: Problem };

export async function createLoan(args: CreateLoanArgs, options: ClientOptions = {}): Promise<CreateLoanResult> {
  const url = `${options.baseUrl ?? ''}/loans`;
  const res = await (options.fetch ?? fetch)(url, {
    method: "POST",
    body: JSON.stringify(args.body),
    headers: {
      'content-type': 'application/json',
      ...(options.headers ?? {}),
    },
  });
  const data = await parseBody(res);
  return { status: res.status, data } as CreateLoanResult;
}
