// generated by distillery2 — do not edit
// basis: contracts@ef34ed2860a1541965f490aa00ad42e21db3d1d7
// distillery2-owner: d2-contract/genContractTests
export interface OperationRoute {
  method: string;
  path: string;
}

export const operations = {
  createLoan: { method: "POST", path: "/loans" },
} as const satisfies Record<string, OperationRoute>;

export type OperationId = keyof typeof operations;
