// generated by distillery2 — do not edit
// basis: contracts@ef34ed2860a1541965f490aa00ad42e21db3d1d7
// distillery2-owner: d2-contract/genContractTests
export type AggregationUnit = "day" | "month" | "year";

export type CopyStatus = "available" | "on_loan" | "on_hold" | "withdrawn";

export interface CreateLoanRequest {
  copy_id: Id;
  patron_number: PatronNumber;
}

export interface FieldError {
  code: string;
  field: string;
  message: string;
}

export type Genre = "literature" | "history" | "social_science" | "natural_science" | "technology" | "arts" | "children" | "other";

export type Id = string;

export type InventoryCategory = "available" | "on_loan" | "waiting_reservation";

export type Isbn = string;

export interface JobRunResult {
  job: string;
  processed: number;
  run_date: string;
  skipped: number;
}

export interface Loan {
  book_title: string;
  copy_id: Id;
  copy_status: CopyStatus;
  due_on: string;
  fulfilled_reservation_id: Id | null;
  loan_id: Id;
  loaned_on: string;
  patron_number: PatronNumber;
  returned_on: string | null;
  status: LoanStatus;
}

export type LoanStatus = "on_loan" | "overdue" | "returned";

export type MediaType = "paper" | "electronic";

export type NotificationStatus = "pending" | "sent";

export type NotificationType = "reservation_ready" | "due_reminder" | "overdue_notice";

export interface PageMeta {
  page: number;
  size: number;
  total: number;
}

export type PatronNumber = string;

export interface Problem {
  code?: string;
  detail?: string;
  errors?: FieldError[];
  instance?: string;
  status: number;
  title: string;
  type: string;
}

export type ReservationStatus = "waiting" | "on_hold" | "fulfilled" | "cancelled";

export type SearchConditionType = "keyword" | "title" | "author" | "isbn" | "genre";

export type UserRole = "patron" | "librarian";
